### ISSUE TITLE
Press Back button of the browser just after login process

### ISSUE THREAD

**Issue by pamiel** [zmartzone/lua-resty-openidc#109]
I've deployed lua-resty-openidc following the exact configuration provided in section “Sample Configuration for Google+ Singin”, except that KeyCloak is used as the IdP.
Everything runs like a charm !... except the following specific use case:

1.	Enter the url of the protected web site in the Browser
2.	Once redirected to the Idp, enter login + password
3.	Once redirected to the originally navigated web page, directly click on the “Back” button of the Browser
4.	=> error 500, with stacktrace that says:

`2017/10/26 09:56:20 [error] 62#0: *247 [lua] openidc.lua:345: authenticate(): state from argument: 5954b628aad36f59c507fdcbabf48e71 does not match state restored from session: nil, client: 10.10.153.131, server: , request: "GET /secure?state=5954b628aad36f59c507fdcbabf48e71&code=uss.eCSlNvHNQypmVUwQxexwV1lFKMNfIXqoRgXI91yIAXs.b859a42d-ce28-42e4-a8a6-8fe1a0efb1a3.1fa139b5-f73f-4117-84e5-036a358940d8 HTTP/1.1", host: "test:8002"`

I can roughly understand what happens:
-	By pressing on Back button, the browser is trying to reload the last page that corresponds to the navigation of the IdP during the initial login process. This url includes the query parameters initially provided (including the response_code, scope, state, nonce, client_id, redirect_uri)
-	The IdP realizes that a session is already available and ok for this client: it immediately redirects the call to the redirect_uri (/secure), still with the “old” query parameters: state and code
-	When intercepted by lua-resty-openidc, lua-resty-openidc thinks it is the last step of the Authorization Code flow, and the execution of the `openidc.authenticate` function goes up to the call to the `openidc_authorization_response` function that finally checks the matching between the session state and the state received as query parameter.
-	However, the session state has been previously reset to nil at the end of the initial login phase => obviously, the state does not match and error is raised up to the generation of the HTTP 500

Testing the same use case with alternate implementation of OpenID Connect libraries makes the browser stay on the current Web page (no redirect to the login page nor to a HTTP 500 page)… which is definitely much better from user experience point of view!

Note that commenting the line `session.data.state = nil` of function `openidc_authorization_response` seems to solve the issue, but the code comments says “-- clear state and nonce to **protect against potential misuse**” so I don’t really measure the impact of commenting this line…
To be frank, among the numerous tests I did, I also faced error logs mentioning the nonce instead of the state “nonce xyz in id_token is not equal to the nonce that was sent in the request” (=> should we also comment the line `session.data.state = nil` ?)… but I’m no longer able to reproduce…

**Comment by zandbelt** [comment]
The point is that in principle state and nonce are one-time usage: one should not be able to guess these values, see https://tools.ietf.org/html/rfc6749#section-10.12 and http://openid.net/specs/openid-connect-core-1_0.html#NonceNotes. So re-using them in a 2nd authorization response is against that idea. Their values may have been leaked because query parameters end up in logs etc.

Also: providers may act differently on a browser back event. Google happens to just create a new authorization response with the same state/nonce, but some others will display an error.

Not sure where that leaves us.

**Comment by pamiel** [comment]
Makes sense! Neither `nonce` nor `state` data are “replayable”.

A possible workaround I experimented is the following: in case the `err` value returned by the `authenticate` function is not null, then I perform a redirect to the “logout” uri instead of returning a HTTP 500 (as mentioned in your default example)
```
if err then
   ngx.redirect(opts.logout_path)
end
```
This will force the session to terminate, and it will then display the page set in the `redirect_after_logout_uri` parameter (for me, this `redirect_after_logout_uri` points to my main page, thus this is intercepted again by the lua-resty-openidc that identifies that there is no active session and finally redirects the user to the login page).

Does it make sense to you ?

What I fear is that the glanularity of my check (simply "`err` is not null") is a bit wide: indeed, I have no other easy way to differentiate between the various error cases that may happen within the library, such as:
-	Refresh Token expired
-	Session ended on IdP
-	No Cookie provided
-	Bug or any other execution error within the lua-resty-openidc code
-	Etc.

If I may, I think lua-resty-openidc internal error management is maybe lacking an error code in complement to the `err` that are returned (`err` being a textual message), so that it could be possible to check the “error code” and take actions depending on it (while checking a full message is not really possible as the message content may be updated from one version of the library to another, or may contain information related to the context/current session).

**Comment by zandbelt** [comment]
That could work indeed if one can distinguish between errors: I don't think it is necessarily a bad idea to use `err` as is if only the messages are a bit more strict and well-defined like constants.

**Comment by zandbelt** [comment]
We may take up improvement of error generating/handling in another issue. The behavior on browser back is essentially correct so I'm closing it here.
