### ISSUE TITLE
Add parameter to allow optional SSL verification 

### ISSUE THREAD

**Issue by hugomcfonseca** [zmartzone/lua-resty-openidc#125]
Is it possible to add following parameter to allow SSL verification being optional? Currently, only userinfo endpoint is demanding to go through a SSL verification.
`ssl_verify = (opts.ssl_verify ~= "no")`

https://github.com/zmartzone/lua-resty-openidc/blob/aafa8903769bae569dc0a624949feea201cdb4f1/lib/resty/openidc.lua#L328-L330

**Comment by zandbelt** [comment]
thanks for catching this, I believe it was an oversight

**Comment by hugomcfonseca** [comment]
No problem @zandbelt. Btw, is there any expected date to the next release of this library?

**Comment by zandbelt** [comment]
a minor release will probably happen within a few weeks from now; in the mean time you can just use the .lua file from master

**Comment by zandbelt** [comment]
included in release 1.5.2
