### ISSUE TITLE
Clear browser cache on logout

### ISSUE THREAD

**Issue by irbull** [zmartzone/lua-resty-openidc#133]
This isn't likely a *bug*, maybe just a configuration error on my part.

Some background. I'm new to Lua, Resty, and Keycloak. I have very limited experience setting up simple nginx servers. Having said that, in a single evening I managed to setup KeyCloak, OpenResty and `lua-resty-openidc`. I managed to secure a simple site using OpenResty as an authenticating reverse proxy using KeyCloak as the identity provider. I was impressed at how easy and powerful this setup is.

However, I found very little docs on how to set this up (especially for someone unfamiliar with these technologies). I would like to document my setup, both so I can find it in the future, and in case others are interested. 

I hit one _small_ snag though. After I hit the logout link, I can still navigate back and see the page. This is because the browser has cached it. If I do a force reload, then I get properly directed to the sign-in page again. This isn't really a problem, although it does look a bit silly in the demo. 

So my question, do you know if OpenResty / Nginx can be configured to tell the browser to clear its cache after logout. I can set nginx `expires 0` which means no cache, but that seems like a bit of an overkill.

Thanks!

**Comment by zandbelt** [comment]
I don't think that would be possible: the logout handler would have to invalidate the cache of other pages; how would one specify the extent of the cache clearance and how is it protected against malicious use .

A writeup of your configuration would be great. You can put it in the Wiki of this project.

**Comment by irbull** [comment]
Thanks!

I've started a blog post, and I'll also turn it into a wiki page here. Once it's there, you can have a look. As I said, I'm pretty new to this, so I'm sure there are many improvements. 

Regarding the cache, yeah I agree. I don't know much about how browser pages decide to check if a cache is invalid? (etag?) and if there is any way to instruct the browser that this page may become invalid (other than time-based).

I'll close this, as it's not really an issue. More of my lack of knowledge in this area :)
