### ISSUE TITLE
Docker image build failure while cloning serpent

### ISSUE THREAD

**Issue by ankitvats24** [zmartzone/lua-resty-openidc#134]
Environment - Red Hat 7.4

Step 9/14 : RUN luarocks install serpent
 ---> Running in 38a89dcafcc7
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/local/openresty/luajit/bin//luarocks with sudo, you may want sudo's -H flag.
Warning: falling back to curl - install luasec to get native HTTPS support
Installing https://luarocks.org/serpent-0.28-1.rockspec
Cloning into 'serpent'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out

Error: Failed cloning git repository.
The command '/bin/sh -c luarocks install serpent' returned a non-zero code: 1

**Comment by bodewig** [comment]
github has been having hiccups today and your error message says there's been a timeout during the clone operation. You probably want to retry once github's health has been completely restored.

**Comment by ankitvats24** [comment]
Tried from a different system and it worked fine. Seems something is blocking at one of the server cluster. Thanks
