### ISSUE TITLE
id_token 'RS256' signature verification failed, client: xxx.xxx.170.207

### ISSUE THREAD

**Issue by ankitvats24** [zmartzone/lua-resty-openidc#135]
2018/01/15 06:13:11 [debug] 256#256: *78 [lua] openidc.lua:737: openidc_load_jwt_and_verify_crypto(): jwt: {"signature":"Jb9T5QlRDIJMdhcC_jQ9bZlCKuRBEWe9BJd70g0sw1UJbznKwXb46eGsaGgAF1aorsZaEQqefAxkL5rfgp9dPVETyAQrToGD74QloStLq_15oeCLa0wAeJvHGb4x_pEGNqAjLYHu04MaguQfVZsVulM80kxBLCQ7ILJvii06HuU","**reason**":"**too long**","valid":true,"raw_header":"eyJraWQiOiIwMDBjMDFiNy03M2QzLTE5ZTktYWVkNi1hMzRjMWU4NzQwNDAiLCJhbGciOiJSUzI1NiJ9","payload":{"exp":1515997091,"iat":1515996791,"sub":"CN=xxx1234,OU=dummOU,OU=usersAndGroups,DC=mygrp,DC=McDonald,DC=com","iss":"https:\/\/MASKED_URL","aud":"00085ed0-b23d-1a4f-ae2e-a34c1e875a5a","nonce":"9638421c0bf995280cb911aac871b58f","auth_time":1515996791},"header":{"kid":"000c01b7-73d3-19e9-aed6-a34c1e874040","alg":"RS256"},"verified":false,"raw_payload":"eyJzdWIiOiJDTj1BRjU0OTAyLE9VPW5vbkFzc29jaWF0ZXMsT1U9dXNlcnNBbmRHcm91cHMsREM9ZGV2YWQsREM9d2VsbHBvaW50LERDPWNvbSIsImF1ZCI6IjAwMDg1ZWQwLWIyM2QtMWE0Zi1hZTJlLWEzNGMxZTg3NWE1YSIsImF1dGhfdGltZSI6MTUxNTk5Njc5MSwiaXNzIjoiaHR0cHM6XC9cL3NlY3VyZS1nYXRld2F5LmRldi5vaWRjLnZhLmFudGhlbS5jb206OTQ0MyIsImV4cCI6MTUxNTk5NzA5MSwiaWF0IjoxNTE1OTk2NzkxLCJub25jZSI6Ijk2Mzg0MjFjMGJmOTk1MjgwY2I5MTFhYWM4NzFiNThmIn0"} ,valid: true, verified: false
2018/01/15 06:13:11 [error] 256#256: *78 [lua] openidc.lua:805: authenticate(): id_token 'RS256' signature verification failed, client: xxx.xxx.170.207, server: , request: "GET /path/to/index/redirect?state=b5e32629459b11e1298d976bd2881792&nonce=9638421c0bf995280cb911aac871b58f&code=NWJhMzc5ODEtZGY5ZC00ZWMyLWExM2QtZmQ2MGY4ZThhZDgwLVhiSTNZZ3B1Snc5NUhEaEJzeVF5UkUzWTQ5cz0= HTTP/1.1", host: "MASKED_URL_RP"

Is this due to very long signature? If yes, then any workaround ?

**Comment by zandbelt** [comment]
it may have to do with the public key/cert; perhaps you can validate the JWT elsewhere to check that, e.g. at jwt.io

**Comment by ankitvats24** [comment]
I am able to validate the token at jwt.io. Signature validation is also true using my public key. 

2018/01/15 06:13:11 [debug] 256#256: *78 [lua] openidc.lua:737: openidc_load_jwt_and_verify_crypto(): jwt: {"signature":"Jb9T5QlRDIJMdhcC_jQ9bZlCKuRBEWe9BJd70g0sw1UJbznKwXb46eGsaGgAF1aorsZaEQqefAxkL5rfgp9dPVETyAQrToGD74QloStLq_15oeCLa0wAeJvHGb4x_pEGNqAjLYHu04MaguQfVZsVulM80kxBLCQ7ILJvii06HuU","reason":"too long",

"reason":"too long" - what could be the reason it repeatedly shows "too long" and verification fails on nginx ?

**Comment by zandbelt** [comment]
`lua-resty-openidc` hands it off to `lua-resty-jwt` by calling `jwt:verify_jwt_obj` which seems to produce this error; perhaps worth asking there, maybe proving it with a separate example using this token/key independent of `lua-resty-openidc`

**Comment by zandbelt** [comment]
So it seems to have something to do with the keypair itself; at least it not something that can be fixed outside of lua-resty-jwt so I'm closing it here.
