### ISSUE TITLE
Session cookie headers forwarded to upstream servers

### ISSUE THREAD

**Issue by pamiel** [zmartzone/lua-resty-openidc#138]
Hi all!
Sorry, this is more a question than an issue: I'm using lua-resty-openidc as Relying Party, and thus setting the Access Token received from the OP in the `Authorization` header at the end of the `authenticate` function call.

I just realized something that I was not expecting to happen:  the  "session" cookies are also forwarded to the upstream server.
My question is: does it really make sense to forward these Cookie headers to the upstream servers, as the session is fully under the responsibility of the RP and the Access Token is the only information that is required by the upstream servers ?
I'm also afraid it could gives some sensitive information to servers that don't care about this data (the session id, and even the full session content in case of usage of the "client Cookie" for "storing" the session... even if in most of the deployments, this data will be set as encrypted).

Wouldn't it be better to remove these headers before proxying?

Thanks for sharing you point of view on that... and thanks for the great work around lua-resty-oipenidc !

**Comment by pamiel** [comment]
Deep diving within lua-resty-session, I see the that `session:hide()` could be used to do so.
As the session object is a return parameter of the `authenticate` function, I'm able to do this by my own, so I'm rephrasing my question above :P : do you think it makes sense to do this directly inside the lua-resty-openidc library, or is it rather the responsibility of the library caller to hide the cookies or not (as it is the library caller responsibility to set the Access Token in the `Authorization` header or not) ?

**Comment by zandbelt** [comment]
I'd leave it up to the caller indeed.

**Comment by pamiel** [comment]
Ok, fully make sense: very similar to the setting of the Authorization bearer.
Thanks for the advice !
