### ISSUE TITLE
Redirect blocked by CORS policy

### ISSUE THREAD

**Issue by FucskoD** [zmartzone/lua-resty-openidc#143]
Hi! 

I'm continuously running into an issue, where my requests to the upstream servers fail.
Our web app runs in docker containers. There is an nginx frontend container, and multiple microservices also running in containers. 
I'm experiencing that after some webservice requests, the attached CORS error happens. 
I'm for sure, I miss-configured something, but can't solve it. 
Attached You can find a webtrace har file, exported from chrome. It shows a full process from hitting the base URL through to when the error happens.
Beside I've attached a screenshot (from chrome dev tools network tab), the nginx access and debug log. 
Plus I copy my nginx conf here, also You can find it attached. (The config is a bit long, I'm sorry)
[access2.log](https://github.com/zmartzone/lua-resty-openidc/files/1712161/access2.log)
[error2.log](https://github.com/zmartzone/lua-resty-openidc/files/1712162/error2.log)
[nginx.conf.txt](https://github.com/zmartzone/lua-resty-openidc/files/1712163/nginx.conf.txt)
[webtrace.txt](https://github.com/zmartzone/lua-resty-openidc/files/1713550/webtrace.txt)
![sso_error](https://user-images.githubusercontent.com/29164702/36045698-df900d82-0dd6-11e8-87d7-57a21c59aeb0.PNG)

`
worker_processes auto;
events {

	worker_connections 1024;

}

http {

	include mime.types;
	default_type text/html;
	sendfile on;
	keepalive_timeout 65;

	log_format debug '$remote_addr - $remote_user [$time_local] "$request" '
	'$status $body_bytes_sent "$http_referer" '
	'"$http_user_agent" "$http_x_forwarded_for"'
	'$server_name to: $upstream_addr: $request';

	access_log logs/access2.log debug;
	error_log	logs/error2.log debug;

	#  lua_package_path '~/lua/?.lua;;';
	lua_package_path '/usr/local/openresty/lualib/resty/?.lua;;';

	resolver 10.220.220.220;

	lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
	lua_ssl_verify_depth 5;

	# cache for discovery metadata documents
	lua_shared_dict discovery 1m;

	# NB: if you have "lua_code_cache off;", use:
	# set $session_secret xxxxxxxxxxxxxxxxxxx;
	# see: https://github.com/bungle/lua-resty-session#notes-about-turning-lua-code-cache-off
	upstream bank-service {

		#default is round robin
		server 172.17.0.5:8183;
	}

	upstream subledger-service {

		#default is round robin
		server 172.17.0.6:8182;
	}

	upstream matching-service {

		#default is round robin
		server 172.17.0.7:8184;
	}
	upstream master-data-service {

		#default is round robin
		server 172.17.0.8:8185;
	}
	upstream auth-service {

		#default is round robin
		server 172.17.0.9:8186;
	}

	server {

		listen 8082;
		server_name nginx-angular;
		set $user '';
		proxy_cache_valid any 1m;

		location / {

			root /usr/local/openresty/nginx/html;
			index index.html index.htm;
			try_files $uri /index.html;
			include mime.types;
			default_type text/html;

			if ($request_method = 'OPTIONS') {

				add_header 'Access-Control-Allow-Origin' '*';
				add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
				#
				# Custom headers and headers various browsers *should* be OK with but aren't
				#
				add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
				#
				# Tell client that this pre-flight info is valid for 20 days
				#
				add_header 'Access-Control-Max-Age' 1728000;
				add_header 'Content-Type' 'text/plain; charset=utf-8';
				add_header 'Content-Length' 0;
				return 204;
			}
			if ($request_method = 'POST') {

				add_header 'Access-Control-Allow-Origin' '*';
				add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
				add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
				add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
			}
			if ($request_method = 'GET') {

				add_header 'Access-Control-Allow-Origin' '*';
				add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
				add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
				add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
			}
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}
		
		}
		location /userinfo {

			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}
			include mime.types;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;	
			default_type application/json;
			proxy_pass http://auth-service/userinfo;
			proxy_redirect default;

		}

		location /subledger {
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			include mime.types;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://subledger-service/listData;
			proxy_redirect default;
		}
		location /bank {
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			include mime.types;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;	
			default_type application/json;
			proxy_pass http://bank-service/listData;
			proxy_redirect default;
		}

		location /break {
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			include mime.types;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://matching-service/break;
			proxy_redirect default;
		}
		location /comment {
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			include mime.types;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://matching-service/comment;
			proxy_redirect default;
		}
		location /categoryList {
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			include mime.types;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://master-data-service/categoryList;
			proxy_redirect default;
		}
		location /treasuryCodeList {
			include mime.types;
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://master-data-service/treasuryCodeList;
			proxy_redirect default;
		}
		location /match {
			include mime.types;
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://matching-service/match;
			proxy_redirect default;
		}

		location /exportsl {
			include mime.types;
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://subledger-service/export;
			proxy_redirect default;
		}

		location /exportbank {
			include mime.types;
			access_by_lua_block {

				local opts = {

					redirect_uri_path = "/redirect_uri",
					discovery = "https://fssfed.ge.com/fss/.well-known/openid-configuration",
					client_id = <my_client_id>,
					client_secret = <my_client_secret>,
					scope = "openid profile"
				}

				-- call authenticate for OpenID Connect user authentication
				local res, err = require("resty.openidc").authenticate(opts)
				-- local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
				if err then
				ngx.status = 500
				ngx.say(err)
				ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
				end
				ngx.req.set_header("X-User-Sso", res.user.sub);
				ngx.req.set_header("X-User-Mail", res.user.mail);
				ngx.req.set_header("X-User-Employeetype", res.user.employeetype);
				ngx.req.set_header("X-User-Cn", res.user.cn);
				ngx.req.set_header("X-User-Gessocompanyname", res.user.gessocompanyname);
				ngx.req.set_header("X-User-Title", res.user.title);
				ngx.req.set_header("X-User-Country", res.user.country);
				ngx.req.set_header("X-User-Location", res.user.location);
				ngx.req.set_header("X-User-State", res.user.state);
				ngx.req.set_header("X-User-Firstname", res.user.firstname);
				ngx.req.set_header("X-User-Lastname", res.user.lastname);
			}

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-NginX-Proxy true;
			proxy_ssl_session_reuse off;
                	proxy_set_header Host $http_host;
			default_type application/json;
			proxy_pass http://bank-service/export;
			proxy_redirect default;
		}

	}
}

`

**Comment by zandbelt** [comment]
It seems you're triggering an authorization request in a XHR request, that's not supposed to happen.  Your XHR requests should not redirect but reload the parent frame in which the authorization request can  be completed.

**Comment by FucskoD** [comment]
Thank You, I was just thinking on the check auth only. I think that will solve the problem
Keep up the good work, and this issue can be closed.

**Comment by ivtikhon** [comment]
> You can use an option on those paths that serve XHR content to stop the redirect:
> https://github.com/zmartzone/lua-resty-openidc/#check-authentication-only
> so you can act on the 'nil' value returned by reloading the parent frame (which should be served from a path that is protected using a regular `authenticate` call without the `pass` option).

I'm experiencing the same issues with CORS blocking XHR redirects. Can you give me an example of code that triggers reload of the parent frame?  Is it supposed to be done in the access_by_lua_block? Something like ngx.redirect, right?

Thank you.
