### ISSUE TITLE
invalid (stale) JWKS cache causes an "file not found" error with the redirect/?code.

### ISSUE THREAD

**Issue by Lawri-van-Buel** [zmartzone/lua-resty-openidc#144]
Version: zmartzone/lua-resty-openidc 1.5.3
             openresty/1.13.6.1
             Ubuntu 16.04.3

I have noticed that when there is an error like `openidc.lua:819: authenticate(): id_token 'RS256' signature verification failed` the client gets a browser generated page saying "File not found", on the redirect endpoint. This is undesirable in a production site / stageing site.

Can we make a config element to sent errored authentications (for required authentications) to a specific URI? This would enable easy mitigation of stale cacheing and the capability to show a clean message to endusers. (or debug information for developers).

The OIDC provider we use unfortunetly does not use a 'KID' which would solve this problem but refreshes its key each day at some point. Unknown when exactly.

**Comment by Lawri-van-Buel** [comment]
So, I am doing something wrong with the return state... got a hint what that could be? (been scratching my head on this for quite a while now without a proper solution)

**Comment by bodewig** [comment]
If signature verification fails, `openidc.authenticate` should return with two values. The first one which is supposed to be the token will be `nil` and the second should contain an error message.

```
token, err = openidc.authenticate(your_params_here)
```

**Comment by Lawri-van-Buel** [comment]
this is a snippet of the code I allreadyt had that does not capture this error.

`
local res, err = require("resty.openidc").authenticate(opts)

if err then
  ngx.status = 500
  ngx.say(err)
  ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
end
`

**Comment by bodewig** [comment]
Sorry for the delay. Right now I don't see why `err` would be `nil` in this case, I added a unit test with commit 4ed96ce and it passes. Something must be different in your case when compared to the test.
