### ISSUE TITLE
Question about usage.

### ISSUE THREAD

**Issue by Caindrac** [zmartzone/lua-resty-openidc#147]
Hi,

I have question about using this library. What I currently have is just a basic webpage that has no users just a static page. What I would like to be able to do is just redirect users to that page if they are authenticated so essentially I don't care at the application level who the users are just that they had keycloak credentials. Can this be done the redirect_uri_path is throwing me off so I figured I would just ask.

**Comment by bodewig** [comment]
I'm afraid you won't get very far without some basic understanding of OpenID Connect.

If you take the example configuration for Google+ Signin from the README, then `redirect_uri_path` is the path of the redirect URI that needs to be configured on your keycloak server for the relying party. By default it is `/redirect_uri` and it is handled by lua-resty-openidc internally,

In you case you need to set up client credentials inside of keycloak (and as part of this you need to specify the redirect uri) and provide the credentials to the library. When the user tries to access your static page - assuming the `access_by_lua` handler is triggered - lua-resty-openidc will run the authorization code grant flow, obtain a token and redirect the user back to the original static page. If the user is not authenticated, the page will not be reached.
