### ISSUE TITLE
accessing token endpoint failed: network unreachable

### ISSUE THREAD

**Issue by noqcks** [zmartzone/lua-resty-openidc#149]
Occasionally, I will get an error about the token endpoint being unreachable. This only occurs ~1/20 times after attempting to authenticate with OIDC. 

> accessing token endpoint (https://www.googleapis.com/oauth2/v4/token) failed: network unreachable

If I hit the endpoint again and attempt to authenticate immediately after this error it will work without issue. 

My configuration is the same as the Sample Configuration in the README.

Release: 1.5.3

**Comment by zandbelt** [comment]
That must be an issue either with an outgoing proxy/firewall in your network or a local host networking issue.

**Comment by jimdigriz** [comment]
...it also occurs when the endpoints support and resolve to IPv6 addresses but the local host does not support it (for example using a GCP instance you see this problem):
```
2021/04/11 08:06:14 [error] 21706#21706: *1 connect() to [2607:f8b0:4001:c54::54]:443 failed (101: Network is unreachable), client: 192.0.2.0, server: server.example.com, request: "GET / HTTP/1.1", host: "server.example.com"
```

```
root@server:/home/alex# ip route
default via 10.128.0.1 dev ens4 
10.128.0.1 dev ens4 scope link 

root@server:/home/alex# ip -6 route
::1 dev lo proto kernel metric 256 pref medium
fe80::/64 dev ens4 proto kernel metric 256 pref medium
```
