### ISSUE TITLE
force_reauthorize option causes infinite redirect loop

### ISSUE THREAD

**Issue by roicostas** [zmartzone/lua-resty-openidc#150]
I am using this library in a reverse proxy to configure authentication to some services that just check a HTTP header for user name.

Authentication works but logout in a particular service just works for that service. Other services are still  accessible even if I drop the session in the OpenID provider.

I have tried force_reauthorize to make the proxy check authentication in every request but that causes an infinite redirect loop after authentication.

I am using openresty docker image openresty/openresty:1.13.6.1-alpine-fat and I have installed this library (version 1.5.3-1) through luarocks.

I have attached nginx log.

[nginx.log](https://github.com/zmartzone/lua-resty-openidc/files/1874680/nginx.log)

**Comment by bodewig** [comment]
`force_reauthorize` is really meant for a one-time use. You would call `authenticate` with that flag set only once and have it set to `false` once the redirect back from the OP happens. This is not what you need in your case.

You probably want to arrange for your logout flow to also hit the logout endpoint of lua-resty-openidc (`/logout` by default) as this deletes the session cookie held by lua-resty-openidc and the library will no longer consider the user logged in on subsequent requests.

**Comment by roicostas** [comment]
I see. Then I should hit the logout endpoint of all services because all of then run in different hosts and I guess there is a cookie per host.

Thank you.
