### ISSUE TITLE
Question: Why we see unhandled request to the redirect_uri sometimes

### ISSUE THREAD

**Issue by venkatmarepalli** [zmartzone/lua-resty-openidc#152]
The redirect_uri in my nginx.conf file is "/secured". Everything is working fine but sometimes we are seeing the below error for some users. Any idea what is causing this issue. 

```unhandled request to the redirect_uri: /secured?error=server_error&error_description=AADB2C%3a+An+exception+has+occured.%0d%0aCorrelation+ID%3a+2f12d187-0cfe-464f-8f6b-ee71b432aa85%0d%0aTimestamp%3a+2018-03-22+21%3a11%3a22Z%0d%0a&state=7e314ac9f035156db3f93fc786283efa```

Once logged in, users are expected to be redirected to the same url with a message from nginx. Below is my nginx conf file.

```
pid  %(NGINX_LOG_DIR)s/nginx.psgi.%(CNAME)s.pid;
error_log  %(NGINX_LOG_DIR)s/nginx_error_psgi.log %(NGINX_LOG_LEVEL)s;

events {
    worker_connections  %(NGINX_WORKER_CONNECTIONS)s;
}

http {
  include       nginx.mime.types.conf;
  server_tokens off;

  log_format compression '$proxy_add_x_forwarded_for - $remote_user [$time_local] '
             '"$uri" $status $body_bytes_sent '
             '"$http_referer" "$http_user_agent"';
  access_log %(NGINX_LOG_DIR)s/nginx_access_psgi.log compression;

  lua_package_path '~/lua/?.lua;;';

  resolver 8.8.8.8;

  # optional but highly recommended due to the large sizes of these files
  gzip on;
  gzip_min_length  500;
  gzip_types text/xml application/rdf+xml text/css application/x-javascript application/json application/xml text/javascript;
  gzip_vary on;

  # cache for JWT verification results
  lua_shared_dict introspection 10m;

  lua_ssl_trusted_certificate /etc/ssl/certs/ca-bundle.crt;
  lua_ssl_verify_depth 5;

  # cache for discovery metadata documents
  lua_shared_dict discovery 1m;

  # storage configuration for shared dictionary adapter
  lua_shared_dict sessions 10m;

  upstream django{
        server %(UPSTREAM_SERVER)s;
  }

  server {
    server_name localhost.;
    listen 80;
    root %(ROOT_DIR)s;

    # setting session storage
    set $session_storage shm;

    # Define email and IP_Address variables
    set $emailaddress "";
    set $IPAddress "";
    set $https_scheme "https";

# Authentication block
     location ~ (/|(^/(logout|secured)$)|(\.html$)){
        # Restricting urls with /int/
         if ($request_uri ~ .*/int/.*) {
         access_by_lua '
                ngx.log(ngx.DEBUG,"Permission Denied!! Cannot access /int/ urls")
         ';
           return 404 'Permission Denied!!';
        }
        set $auth_email "";
        set $auth_realname "";
        access_by_lua '
          local opts = {
            -- the full redirect URI must be protected by this script and becomes:
            -- ngx.var.scheme.."://"..ngx.var.http_host..opts.redirect_uri_path
            -- unless the scheme is overridden using opts.redirect_uri_scheme or an X-Forwarded-Proto header in the incoming request
            redirect_uri_path = "/secured",
            discovery = "%(DISCOVERY)s",
            -- Native App details registered on Azure AD B2C or Web API details for Azure AD Apps
            client_id = "%(CLIENT_ID)s",
            client_secret="%(CLIENT_SECRET)s",
            --ssl_verify = "no"
            --redirect_uri_scheme = "http",
            --authorization_params = { hd="pingidentity.com" },
            --scope = "openid email profile",
            iat_slack = 600,
            --Avoid infinite redirects after authentication
            renew_access_token_on_expiry=false,
            --logout_path = "/logout",
            --token_endpoint_auth_method = ["client_secret_basic"|"client_secret_post"],
          }
          ngx.DEBUG=0

          -- table print for debugging
          function tprint (tbl, indent)
            if not indent then indent = 0 end
            for k, v in pairs(tbl) do
              formatting = string.rep("  ", indent) .. k .. ": "
              if type(v) == "table" then
                ngx.log(ngx.DEBUG, formatting)
                tprint(v, indent+1)
              elseif type(v) == "boolean" then
                ngx.log(ngx.DEBUG, formatting .. tostring(v))
              elseif not (type(v) == "function") then
                ngx.log(ngx.DEBUG, formatting .. v)
              end
            end
          end

          ngx.log(ngx.STDERR, "call authenticate for ", ngx.var.request_uri)
          -- call authenticate for OpenID Connect user authentication
          local res, err = require("resty.openidc").authenticate(opts)

          ngx.log(ngx.STDERR, "authenticated, error=",err)
          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

          ngx.log(ngx.DEBUG, "URI set to ", ngx.var.request_uri)
          local session = require("resty.session").open(session_opts)
          local policy = session.data.id_token.acr
          local user = session.data.id_token["signInNames.emailAddress"] or session.data.id_token["name"]
          ngx.log(ngx.INFO,"Logged in user-->",user)
          if not string.match(ngx.var.request_uri,"getauthcode") then
                  ngx.say("Welcome ", user)
          end
        ';
       }
}
}
```

**Comment by bodewig** [comment]
Hmm, `/secured?error=server_error...` is the OpenID Connect Provider telling your redirect_uri that something has gone wrong on its side. You probably need to look at the logs (or ask the admin) of your OP.

**Comment by venkatmarepalli** [comment]
I think I can reproduce the issue. It seems to be not the issue with the OpenID provider. 

Lets say my URL is https://abc.com

**Good Case:**
1. User tried to navigate to https://abc.com, nginx spawns an authentication url with redirect_uri=https://abc.com/secured. After the login the page goes to Home page (https://abc.com)
2. On the same firefox window if user opens a new tab and navigates to the URL, Home page is seen because the session is already logged in.

**Bad Case**
1.  My application spawns a login url with custom redirect_uri=a.b.c://123. User logs in and my custom scheme kicks in after the login and my custom scheme invokes a script which gets executed
2. On the same firefox window if user opens a new tab and navigates to https://abc.com. user sees this error message.

Any pointers where I should be looking to resolve this issue ?

**Comment by zandbelt** [comment]
Your redirect URI cannot have a custom URI scheme: it must point back to a location handled by NGINX and processed by lua-resty-openidc's authenticate method; as such it must be an HTTP URL.

**Comment by venkatmarepalli** [comment]
Does it mean lua-resty-openidc doesn't support custom schemes as redirect uris? or if I have custom scheme configured in nginx will it help?

**Comment by zandbelt** [comment]
lua-resty-openidc and NGINX for that matter is a web client; it will consume/process information sent via HTTP parameters to a HTTP redirect URI

**Comment by bodewig** [comment]
lua-resty-openidc must be the one who handles the redirect from the OP. If you can arrange for it to receive the request via your custom protocol, that might work.

Note that lua-resty-openidc sends the redirect uri to the authorization endpoint and assumes the same protocol will be used that has been used by the request that triggers the redirect to the OP - this can be overridden by a `Forwarded` or `X-Forwarded-Proto` header.

**Comment by zandbelt** [comment]
@bodewig  in principle you're right but I'm not sure how stuff like `ngx.req.get_uri_args()` would work with a custom protocol (and I don't think it would be defined behavior anyhow)

**Comment by bodewig** [comment]
@zandbelt our responses crossed mid-air :-)

I said "might work" as I'm not sure it is going to work either. Chances will improve if you are technically using HTTP and just call it by a different name, but even then it is not something that can be expected to work out of the box.
