### ISSUE TITLE
Plans to support latest version of OpenResty with OpenSSL 1.1?

### ISSUE THREAD

**Issue by cdbattags** [zmartzone/lua-resty-openidc#160]
Is this in the works? What can I do to help?

**Comment by zandbelt** [comment]
that's dependent in lua-resty-jwt's support for OpenSSL 1.1 see: https://github.com/SkyLothar/lua-resty-jwt/pull/79

**Comment by cdbattags** [comment]
got this working on my fork of @SkyLothar's module found at cdbattags/lua-resty-jwt and at https://opm.openresty.org/ v0.1.14

will update with my latest changes shortly

**Comment by gene1wood** [comment]
This dependency change was merged into lua-resty-openidc in #165
