### ISSUE TITLE
Updating "lua-resty-jwt" and "lua-resty-hmac" for OpenSSL 1.1

### ISSUE THREAD

**Issue by cdbattags** [zmartzone/lua-resty-openidc#162]
Follow along as we get updated package added to root manifest: https://github.com/luarocks/luarocks-site/issues/133

Hopefully HMAC is close behind: https://github.com/jkeys089/lua-resty-hmac/issues/9

But until then can we get something temporary added on here to depend on @jkeys089 instead?

**Comment by cdbattags** [comment]
Just saw that y'all are already using `jkeys089/lua-resty-hmac` so no worries. As soon as we get my fork added to the root manifest we'll be all set.

**Comment by cdbattags** [comment]
Why are y'all using two different package dependencies for OPM and LuaRocks? Looks like for OPM it's `jkeys089/lua-resty-hmac` but on LuaRocks y'all are using `jamesmarlowe/lua-resty-hmac`?

**Comment by zandbelt** [comment]
I believe `lua-resty-jwt` from luarocks includes its own `lua-resty-hmac` version.

**Comment by cdbattags** [comment]
check out https://github.com/cdbattags/lua-resty-jwt for a working OpenSSL 1.1.x implementation

latest update can be found at https://opm.openresty.org/ with v0.1.14

**Comment by Lawri-van-Buel** [comment]
I had an error like
```
*1 lua entry thread aborted: runtime error: /usr/local/openresty/site/lualib/resty/evp.lua:216: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: EVP_MD_CTX_create
stack traceback:
coroutine 0:
	[C]: in function '__index'
	/usr/local/openresty/site/lualib/resty/evp.lua:216: in function 'verify'
	/usr/local/openresty/site/lualib/resty/jwt.lua:812: in function 'verify_jwt_obj'
	/usr/local/openresty/site/lualib/resty/openidc.lua:819: in function 'openidc_load_jwt_and_verify_crypto'
	/usr/local/openresty/site/lualib/resty/openidc.lua:884: in function 'authenticate'
	/usr/local/openresty/nginx/conf/lua/oidc.lua:2: in function </usr/local/openresty/nginx/conf/lua/oidc.lua:1>, client: 127.0.0.1, server: localhost.ld, request: "GET /redirect?code=<CODE>&state=<state> HTTP/1.1", host: "localhost.ld"
```

**Comment by zandbelt** [comment]
@cdbattags could you remove the `lua-resty-openidc` version 1.6.0 associated with your repo in the OPM listing at opm.openresty.org? That will only cause confusion.

**Comment by ChristianCiach** [comment]
@Lawri-van-Buel Thank you, that worked for us, too!

 @zandbelt Could you please update your OPM-dependency to the jwt module by @cdbattags ? The module by SkyLothar seems to be abandoned. A simple "yum update" just broke our production system just because it updated OpenResty, while the module by SkyLothar became incompatible.

**Comment by cdbattags** [comment]
Hola folks, sorry for the delay on this! So I realized this after the fact but OPM doesn't allow deletions from their registry. I figured the best scenario is to keep all tags up until when I took it over and go ahead and bump the versioning to v0.2.0 and move on from there. Would this satisfy y'all?

**Comment by cdbattags** [comment]
Ok! So we are all set with v0.2.0 on http://luarocks.org/modules/cdbattags/lua-resty-jwt/0.2.0-0 and at https://opm.openresty.org/!

We should be all set to update this package!

**Comment by cdbattags** [comment]
@agentzh hopefully will be removing everything else shortly!

**Comment by cdbattags** [comment]
More updates: my fork of this package has now been removed from OPM. Shall I submit a PR for this one-liner?
