### ISSUE TITLE
Question about configuration and workflow with Keycloak

### ISSUE THREAD

**Issue by Amiiya** [zmartzone/lua-resty-openidc#163]
Hi there,

I just setup OpenResty and I want to realize this kind of situation:
I have an Nginx with a suburl as WebUI and a secured "application" named dummy which is secured with Relying Party OpenID Connect. My dummy is representing my backend and returns a string, e.g. "Hello World".

1. Accessing WebUI --> calls the dummy backend via RP --> Redirect to Keycloak for authentification
2. Login via Keycloak --> JWT Token
3. Redirect to Dummy-Backend via RP with JWT which results: RP is accepting request and redirects to dummy via reverse proxy.
4. access dummy backend which return "Hello World" for display on my WebUI.

My NGINX config looks like this:
```
....
   lua_package_path '/opt/openresty/lualib/?.lua;;';
   resolver 8.8.8.8;
   lua_shared_dict discovery 1m;
   lua_shared_dict jwks 1m;

server {
    listen       5000;
    server_name  127.0.0.1;

    location / {
        root   /opt/openresty/nginx/html;
        index  index.html index.htm;
    }

    location /webui {
        root   /opt/openresty/nginx/html;
        index index.html index.htm;
    }

    location /dummy {
        access_by_lua '
          local opts = {
                discovery = "http://127.0.0.1:5000/auth/realms/internal/.well-known/openid-configuration",
                redirect_uri_path = "/webui",
                client_id = "dummy",
                client_secret = "126781aa-97e2-4e80-ae6d-f047c88df9be",
          }

          local res, err = require("resty.openidc").authenticate(opts)
          if err then
            ngx.status = 403
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end
       ';

       expires           0;
       add_header        Cache-Control private;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /opt/openresty/nginx/html;
    }

    include include/5000_*.conf;
}
```
I have my realm named internal and I have a client named "dummy". With my current configuration I get to login in to Keycloak but I am redirected the WebUI and not dummy.

I am pretty new to Keycloak, NGINX and OpenID Connect. I'm not sure if the workflow I'm thinking of is right...

Thanks for any help!! :)

**Comment by zandbelt** [comment]
Your redirect URI is a "vanity URL" that should be handled by lua-resty-openidc so I suggest you set it to: `/dummy/redirect_uri`

**Comment by Amiiya** [comment]
@zandbelt Thank you for you quick answer! I don't really understand your answer. Should i change it to `redirect_uri_path = "/dummy/redirect_uri"` or `redirect_uri_path = "/dummy/webui"`. I dont understand how I am able to access the information which is on my dummy. Sorry for these questions!

**Comment by Amiiya** [comment]
I updated my config. I added a reverse proxy for my backend. Dummy is renamed to RP for legibility.
I think it works with redirect_uri!

```
   lua_package_path '/opt/openresty/lualib/?.lua;;';
   resolver 8.8.8.8;
   lua_shared_dict discovery 1m;
   lua_shared_dict jwks 1m;

server {
    listen       5000;
    server_name  127.0.0.1;
    root   /opt/openresty/nginx/html;
    index  index.html index.htm;

    location / {
    }

    location /webui {
    } 

    location /rp {
        access_by_lua '
          local opts = {
                discovery = "http://127.0.0.1:5000/auth/realms/internal/.well-known/openid-configuration",
                redirect_uri_path = "/rp/redirect_uri",
                client_id = "dummy",
                client_secret = "126781aa-97e2-4e80-ae6d-f047c88df9be",
          }

          local res, err = require("resty.openidc").authenticate(opts)
          if err then
            ngx.status = 403
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end
       ';
       expires           0;
       add_header        Cache-Control private;
       proxy_pass        http://localhost:5050/;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /opt/openresty/nginx/html;
    }

    include include/5000_*.conf;
}
```

When I access http://localhost:5000/webui/ there is a button which redirects to http://localhost:5000/rp. I can login via Keycloak. The url is still http://localhost:5000/rp but i can see my Hello World from my backend!

**Comment by Amiiya** [comment]
But another minor question:
What kind of resolver should i use if i want to use localhost instead of 127.0.0.1 in my discovery url?
Until now just used `resolver 8.8.8.8;`

**Comment by dalu** [comment]
probably the one from /etc/resolv.conf

**Comment by Amiiya** [comment]
@dalu Thank you!! :) :+1:

**Comment by dalu** [comment]
Sure, anytime @Amiiya :) Did it work for you in general? It didn't for me, because it complained about ... 20 something and the cert's validity, altough it was or is a letsencrypt cert.
So I moved over to https://github.com/gambol99/keycloak-proxy , again.

```
server {
        server_name domain.tld.local;
        listen 80;
        
        location / {
                access_by_lua '
          local opts = {
                discovery = "https://connect.icod.de/auth/realms/domain.tld/.well-known/openid-configuration",
                redirect_uri_path = "/",
                client_id = "test-client",
          }

          local res, err = require("resty.openidc").authenticate(opts)
          if err then
            ngx.status = 403
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end
                ';
                proxy_pass http://unix:/tmp/domain.tld.sock/;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host              $http_host;
                proxy_set_header X-Real-IP         $remote_addr;
        }
}
```

¯\_(ツ)_/¯

ah there's the error
`failed: 20: unable to get local issuer certificate`

Oh and regarding 8.8.8.8 Google's DNS, don't assume Google has your best interests in mind. When they control the DNS, the browser and the search engine they have pretty much control over everything they want. Also by using 8.8.8.8 you're giving away your habits about sites you visit to Google, for free. Same if you're using Chrome/Chromium. Just saying. Google has a whole lot of power and they just recently removed the "don't be evil" clause from their code of conduct. Not that they have been following it recently anyway. Be careful with Google/Alphabet is all I'm saying. Grüße

**Comment by zandbelt** [comment]
looks like a matter of configuring `lua_ssl_trusted_certificate`

**Comment by dalu** [comment]
Ok I've added this, now I'm receiving a 403 response, a base64 encoded response of
`accessing discovery url (https://connect.icod.de/auth/realms/contested.de/.well-known/openid-configuration) failed: network is unreachable`
Why is it even base64 encoded?

Ok browing the logs I see
```
2018/06/14 13:53:57 [error] 8819#0: *56 connect() to [2a01:4f8:173:e04::2]:443 failed (101: Network is unreachable), client: 127.0.0.1, server: eq2.local, request: "GET /api/v1/raids/ HTTP/1.1", host: "eq2.local", referrer: "http://eq2.local/raids"
2018/06/14 13:53:57 [error] 8819#0: *56 [lua] openidc.lua:483: openidc_discover(): accessing discovery url (https://connect.icod.de/auth/realms/contested.de/.well-known/openid-configuration) failed: network is unreachable, client: 127.0.0.1, server: eq2.local, request: "GET /api/v1/raids/ HTTP/1.1", host: "eq2.local", referrer: "http://eq2.local/raids"
```
that is because IPv6 in Croatia, where I'm currently at is a loud confused ape grunt reaction...
Can I force IPv4, @zandbelt ?

**Comment by Amiiya** [comment]
@dalu Yes it did work for me. I mean it redirected me to localhost:5000/../ which was my intention. But the logout mechanism stopped working for me https://github.com/zmartzone/lua-resty-openidc/issues/169
