### ISSUE TITLE
Word about performance?

### ISSUE THREAD

**Issue by dalu** [zmartzone/lua-resty-openidc#166]
It's LUA, what can one expect in terms of performance on an average 5 year old CPU e.g. Xeon E3-1245v2 or thereabout?

How many concurrent connections and requests per second?

I'm currently on the fence between a middleware (proxy) in Go, which I know can handle at least 2000 concurrent connections or this and skipping the whole ordeal about running an extra instance for every web service. However using LUA it won't be a big difference.

So yeah, is there any info about performance available?

**Comment by zandbelt** [comment]
Feel feel free to add your own experience/numbers in a Wiki page.

**Comment by dalu** [comment]
Thanks for nothing

**Comment by dalu** [comment]
Performance must be really bad if you're not showing any numbers.

**Comment by zandbelt** [comment]
Thanks for your ontribution!
