### ISSUE TITLE
Custom debug level

### ISSUE THREAD

**Issue by arcivanov** [zmartzone/lua-resty-openidc#177]
Currently lua-resty-openidc has `ngx.DEBUG` hardcoded everywhere.
Nginx DEBUG level requires nginx being compiled with debug support, which is not present in production environment.
Before I submit a patch, would there be any objection to actually making the log level a module-scoped variable keeping ngx.DEBUG as a default?

**Comment by zandbelt** [comment]
No objection, that would be a very welcome contribution, thanks!
