### ISSUE TITLE
Cloudflare access validating JWT Tokens

### ISSUE THREAD

**Issue by harold-s** [zmartzone/lua-resty-openidc#185]
Hello,

First off thanks a lot for this great library. I went through the code to understand it and it is well structured and not too hard to understand !

I have been using your library to validate a JWT token sent by Cloudflare Acess :
https://blog.cloudflare.com/cloudflare-access-now-teams-of-any-size-can-turn-off-their-vpn/

JWT documentation here :
https://developers.cloudflare.com/access/setting-up-access/validate-jwt-tokens/

Here is a minimal viable VHOST using lua-resty-openidc I came up with :

```Nginx
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
lua_ssl_verify_depth 5;

# cache for JWT verification results
lua_shared_dict introspection 10m;

server {
  server_name DOMAIN.com;

  listen 443 ssl http2;
  root /usr/share/nginx/www

      access_by_lua '
          local access_token = ngx.req.get_headers()["cf-Access-Jwt-Assertion"]

          if not access_token then
            ngx.log(ngx.STDERR, "No Cloudflare token found")
            ngx.status = 403
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end

          local openidc = require("resty.openidc")

          local opts = {
              client_id = "CLIENT_ID_AKA_Cloudflare_Application_Audience__Tag",
              discovery = {
                jwks_uri = "https://DOMAIN.com/cdn-cgi/access/certs"
              },
              token_signing_alg_values_expected = { "RS256" },
          }

          local json, err = openidc.jwt_verify(access_token, opts)

          if err or not json then
            ngx.status = 403
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end
      ';
}
```

I've test this implementation and it works. (if you see anything do not hesitate). 

I have a few questions though, I could do a few small PRs but I would like to know what you think before coding :) :

1) I think I'm not the only one looking for implementing Cloudflare JWT Access with nginx, do you want me to create a PR with a Sample Configuration for Cloudflare in the [README.md](https://github.com/zmartzone/lua-resty-openidc/blob/master/README.md) ?

2) In the documentation [Sample Configuration for OAuth 2.0 JWT Token Validation](https://github.com/zmartzone/lua-resty-openidc/blob/master/README.md#sample-configuration-for-oauth-20-jwt-token-validation) it took me quite a long time to understand the 3rd option could be a table like :
```
 discovery = {
                jwks_uri = "https://DOMAIN.com/cdn-cgi/access/certs"
              },
```
The document specify only `discovery` to be a string.:
```
discovery = "https://accounts.google.com/.well-known/openid-configuration"
```
The other example in [Sample Configuration for Google+ Signin
](https://github.com/zmartzone/lua-resty-openidc/blob/master/README.md#sample-configuration-for-google-signin) shows also discovery as a string.
I discovered it by digging into the code.

Do you think I could do a PR to show both examples ?

3) As you can see I have used the `openidc.jwt_verify(access_token, opts)` method.

I couldn't use the `openidc.bearer_jwt_verify` because it calls the `openidc_get_bearer_access_token(opts)` method which looks for the 'Authorization' header.
```
  -- get the access token from the Authorization header
  local headers = ngx.req.get_headers()
  local header =  headers['Authorization']
```
(https://github.com/zmartzone/lua-resty-openidc/blob/24da8b18186c0db464d08968a7a4a4ae1dd92d98/lib/resty/openidc.lua#L1331)

Cloudflare sends the JWT token in the `cf-Access-Jwt-Assertion` header.

Do you think I could do a PR ? :
An entry could be added to `opts` `header_token_field` which would only be used if `auth_accept_token_as` is undefined or set to `"header"`.
If `header_token_field` is undefined it would automatically use the `"Authorization"` key.

**Comment by zandbelt** [comment]
1. I'd like to start creating product/service/integration specific pages is the Wiki for this type of content; feel free to create a "CloudFlare" page or something similar.
2. some text that describes the `opts.discovery` option better would be helpful indeed
3. I'd like to see `auth_accept_token_as` being extended to other header values, but also to consume access tokens from query and post parameters; I'd prefer to call the option for setting the header name something like `auth_accept_token_as_header_name`.

PRs that include test code are very welcome! (that would also get you added to the AUTHORS...)

Thanks for contributing, this thread is useful on its own.

**Comment by harold-s** [comment]
3 I've created the PR https://github.com/zmartzone/lua-resty-openidc/pull/186 for 3 (I'd rather post/query be in another PR :) )
1 and 2 I've created entries for every sample from the README in https://github.com/zmartzone/lua-resty-openidc/wiki and added Cloudflare. (delete it if you don't like it)
I was thinking the README could have a list of all the options (kind of like a man page) and have links to the Wiki for samples. Would that be OK to you ? (I'm happy to start a PR on this)

**Comment by zandbelt** [comment]
Thanks a bunch! Please add yourself to the AUTHORS file as well :-)

I would like the README to contain the "de-facto default" settings for both an OIDC and (2x) OAuth RS setup (which means Google+ OIDC and RFC 7662 introspection + local JWT respectively), then add a pointer to a Wiki page that in its turn contains a list of links to the sample pages with some introductory text for each entry (whether it is OIDC and/or OAuth 2.0 RS etc).

The manpage with an exhaustive listing of all options together with a detailed description should be its own Wiki page, with a link to it in the README.md

As you see I'd like to do some serious cleanup of the README.md ;-)

**Comment by harold-s** [comment]
OK I'll have a look on what I can do (bit later in the week :) )
My code was actually missing the cliend id verification. I've added it to the wiki

```lua
  if json.aud[1]~= opts.client_id then
    ngx.log(ngx.STDERR, "Client ID does not match")
    ngx.status = 403
    ngx.exit(ngx.HTTP_FORBIDDEN)
  end
```

**Comment by zandbelt** [comment]
Yes, that's a tricky point indeed: one typically doesn't want to allow *any* (valid) token that was issued by the Authorization Server, but restrict to certain clients/scopes/audiences. There's a few entries in the sample config in the README for that, I'll emphasize them.

**Comment by torarnv** [comment]
> Yes, that's a tricky point indeed: one typically doesn't want to allow any (valid) token that was issued by the Authorization Server

Cloudflare doesn't allow Access Policies covering multiple subdomains or wildcard domains, so in the case of foo.domain.com, bar.domain.com and baz.domain.com, you'd have to verify the audience against a map of hosts to audience tags.

I'm running a reverse proxy with CF in front, and the reverse proxy is handling many subdomains. Do I understand it correctly that if I just want to verify that the JWT is coming from Cloudflare Access and is valid, I can skip the aud-check, effectively allowing all the Access Policies of my domain to pass through? Eg:

```lua
local access_token = ngx.req.get_headers()["cf-Access-Jwt-Assertion"]

if not access_token then
  ngx.log(ngx.STDERR, "No Cloudflare token found")
  ngx.status = 403
  ngx.exit(ngx.HTTP_FORBIDDEN)
end

local openidc = require("resty.openidc")

local opts = {
  discovery = {
    jwks_uri = "https://mydomain.cloudflareaccess.com/cdn-cgi/access/certs"
  },
  token_signing_alg_values_expected = { "RS256" },
 }

local payload, err = openidc.jwt_verify(access_token, opts)

if err or not payload then
 ngx.status = 403
 ngx.exit(ngx.HTTP_FORBIDDEN)
end

-- Allow all audience tags through, or save for later and verify when mapping host to internal upstream servers
```

One improvement to the wiki/CF template is perhaps to move the `client_id` out of `opts`, and instead make it clear that it's only used further down to verify the audience?
