### ISSUE TITLE
OpenID Foundation Certified?

### ISSUE THREAD

**Issue by MobyWare** [zmartzone/lua-resty-openidc#195]
Is this plugin certified by the OpenID Foundation? There is a certification logo on the README.md. However, the plugins repository appears in the list of [uncertified solutions](https://openid.net/developers/uncertified/). Please clarify.

**Comment by zandbelt** [comment]
Yes it is: the authoritative source for certification is:
https://openid.net/certification/
where `lua-resty-openidc` is listed under the certified RP implementations. I'll see that it gets removed from the uncertified solutions page...

**Comment by MobyWare** [comment]
Great. I just checked your link.
