### ISSUE TITLE
State from argument does not match state restored from session

### ISSUE THREAD

**Issue by nqbao** [zmartzone/lua-resty-openidc#206]
Hi,

I am using this module to integrate with keycloak oidc, and once for a while I get this error

![image](https://user-images.githubusercontent.com/177742/46699554-05c0f280-cbcf-11e8-9029-92ddba677215.png)

I tried to debug but was not able to identify the issue. Do you have any hint why it has this problem?

**Comment by zandbelt** [comment]
@bodewig and I discussed this the other day and concluded that this message must occur when parallel unauthenticated requests are triggered: each request would generate its own state value and start its own session to store that state but only the last request will prevail and set the (final) cookie value: when the earlier request(s) return there will be a mismatch of state/session.

**Comment by nqbao** [comment]
Do you think is there a way we can fix it? Maybe keep track of all valid states instead of storing the last one?

**Comment by zandbelt** [comment]
It's a bit of a rabbit hole. I'd rather like to know what your application looks like i.e. why it fires off a bunch of parallel requests.

**Comment by nqbao** [comment]
My implementation is pretty much similar to this https://eclipsesource.com/blogs/2018/01/11/authenticating-reverse-proxy-with-keycloak/

It's actually user "error". User opens multiple tabs of the application, then when the session timeout, all the tabs redirects to the login page (the redirection is made by this module).

**Comment by zandbelt** [comment]
isn't the tab only refreshed when the user navigates to it? what browser is this?

**Comment by zandbelt** [comment]
I believe that's a valid approach and not so much ad-hoc: it is the only way to deal with requests that fail because of an invalid access token and this case needs to be handled anyhow.

**Comment by weisjohn** [comment]
@nqbao did you ever find a solution to this?

**Comment by nqbao** [comment]
No i don't, it's still a user pain right now. Do you have any suggestion?

**Comment by weisjohn** [comment]
@nqbao going this direction myself: https://github.com/bungle/lua-resty-session/issues/23

**Comment by weisjohn** [comment]
@nqbao setting nginx workers to 1 and specifying the session secret has solved the issue for me

**Comment by StanislavMakhrov** [comment]
@zandbelt and @bodewig, please help with this issue. I have the same problem.
In my application I have list of cards - with some information about our customers. When user click on any card then starts authentication -  fires authentication function of openidc.
Everything is correct if user is waiting until page with card will be loaded. If user will click on another card before previous card loaded then fires error:
state from argument: 

4c2365b9bee57094c7c16a69eb67b3b3 does not match state restored from session: 027d063f9418c29012198885a8a13dd4

It is also interesting that in some cases, if the user simultaneously tries to open several tabs, then there may not be errors, but the data on the card pages may be mixed. However, the early pages are not loaded to the end. Only the last page is fully loaded.

**Comment by StanislavMakhrov** [comment]
@nqbao, please write, did you find a solution of the problem?

**Comment by StanislavMakhrov** [comment]
@zandbelt and @bodewig, please help with this issue. I have the same problem.
In my application I have list of cards - with some information about our customers. When user click on any card then starts authentication - fires authentication function of openidc.
Everything is correct if user is waiting until page with card will be loaded. If user will click on another card before previous card loaded then fires error:
state from argument:

4c2365b9bee57094c7c16a69eb67b3b3 does not match state restored from session: 027d063f9418c29012198885a8a13dd4

It is also interesting that in some cases, if the user simultaneously tries to open several tabs, then there may not be errors, but the data on the card pages may be mixed. However, the early pages are not loaded to the end. Only the last page is fully loaded.

@nqbao, please write, did you find a solution of the problem?

**Comment by SMakhrov** [comment]
@zandbelt and @bodewig, please help with this issue. I have the same problem.
In my application I have list of cards - with some information about our customers. When user click on any card then starts authentication - fires authentication function of openidc.
Everything is correct if user is waiting until page with card will be loaded. If user will click on another card before previous card loaded then fires error:
state from argument:

4c2365b9bee57094c7c16a69eb67b3b3 does not match state restored from session: 027d063f9418c29012198885a8a13dd4

It is also interesting that in some cases, if the user simultaneously tries to open several tabs, then there may not be errors, but the data on the card pages may be mixed. However, the early pages are not loaded to the end. Only the last page is fully loaded.

@nqbao, please write, did you find a solution of the problem?
