### ISSUE TITLE
depracating redirect_uri_path - released?

### ISSUE THREAD

**Issue by phantastico** [zmartzone/lua-resty-openidc#211]
Hi - will you be doing a release of the latest updates (deprecating redirect_uri_path, replacing with redirect_uri) any time soon? I've hit an issue that the latest updates fixes which aren't available in 1.6.1 (via luarocks).

**Comment by zandbelt** [comment]
one more feature (#210) to merge and I'll release 1.7.0 shortly, hopefully tomorrow; you can always download the single file that `lua-resty-openidc` consists of from Github and copy it over your 1.6.1 installation

**Comment by phantastico** [comment]
That's exactly what I've done in the mean time - and thanks for the speedy response.

**Comment by vishnu2kmohan** [comment]
Eagerly awaiting an official release... (so I can stop maintaining a private copy) :grin: :pray:

**Comment by zandbelt** [comment]
all done now: https://github.com/zmartzone/lua-resty-openidc/releases/tag/v1.7.0
