### ISSUE TITLE
Version number for 1.7.0 is not updated

### ISSUE THREAD

**Issue by pamiel** [zmartzone/lua-resty-openidc#212]
Just to let you know that the version number here https://github.com/zmartzone/lua-resty-openidc/blob/v1.7.0/lib/resty/openidc.lua#L75 has not been updated and is still set to "1.6.1".

**Comment by zandbelt** [comment]
darn, could have sworn...

**Comment by pamiel** [comment]
Sorry, one extra small thing: 
Release note https://github.com/zmartzone/lua-resty-openidc/releases/tag/v1.7.0 says that

> Note that opts.secret and opts.redirect_uri are now deprecated and will be removed in the next release; a warning is issued in the log now.

But indeed this is `redirect_uri_path` that is deprecated and not `redirect_uri` (as correctly said a couple of lines after)

**Comment by zandbelt** [comment]
corrected, thanks again!
