### ISSUE TITLE
some js error

### ISSUE THREAD

**Issue by zhiyuazo** [zmartzone/lua-resty-openidc#218]
I configure the lua block in nginx.conf 
I can be redirected to keycloak AUTH page. 
I also can be redirected to the web-page. 
but, nginx report the error which seem unrelate to authentication.:

> ex.js?v=188ca45bd85ce843071e768d855722a9d9dabe03 HTTP/1.1", host: "135.1.237.202:8443", referrer: "https://135.1.237.202:8443/cpro4"
2018/10/24 22:52:28 [error] 21163#21163: *202 open() "/usr/local/openresty/nginx/html/static/js/graph/index.js" **failed (2: No such file or directory)**, client: 135.252.158.85, server: nginx_202s, request: "GET /static/js/graph/index.js?v=188ca45bd85ce843071e768d855722a9d9dabe03 HTTP/1.1", host: "135.1.237.202:8443", referrer: "https://135.1.237.202:8443/cpro4"
2018/10/24 22:52:28 [error] 21163#21163: *202 open() "/usr/local/openresty/nginx/html/static/js/graph/index.js" **failed (2: No such file or directory)**, client: 135.252.158.85, server: nginx_202s, request: "GET /static/js/graph/index.js?v=188ca45bd85ce843071e768d855722a9d9dabe03 HTTP/1.1", host: "135.1.237.202:8443", referrer: "https://135.1.237.202:8443/cpro4"

**Comment by zandbelt** [comment]
well, there's no such file or directory... that's unrelated to `lua-resty-openidc`
