### ISSUE TITLE
interaction_required issue

### ISSUE THREAD

**Issue by lbvffvbl** [zmartzone/lua-resty-openidc#220]
Hi we trying use lua-resty-openidc for kubernetes dashboard but see ptoblem with refresh token. if i try to reload page after refresh session interval i got error 
unhandled request to the redirect_uri: /oauth2/callback?state=afa6aac1a48e7ec960a51f68654b3438&error_subtype=access_denied&error=interaction_required
only if i reload page

`  nginx.conf: |-
    events {
      worker_connections 128;
    }
    error_log /dev/stdout debug;
    env OIDC_CLIENT_ID;
    env OIDC_CLIENT_SECRET;
    env SESSION_SECRET;
    http {
      resolver 8.8.8.8;
      lua_shared_dict introspection 10m;
      lua_shared_dict discovery 10m;
      server {
        listen 9000;
        set $session_secret os.getenv("SESSION_SECRET");
        set $session_cookie_secure off; # set this to 'on' in prod!
        large_client_header_buffers 4 32k;

        location / {
          access_by_lua_block {
            local opts = {
              redirect_uri_path = "/oauth2/callback",
              discovery = "https://accounts.google.com/.well-known/openid-configuration",
              client_id = os.getenv("OIDC_CLIENT_ID"),
              client_secret = os.getenv("OIDC_CLIENT_SECRET"),                                                                                                                    
              scope = "email openid",                                                                                                                                             
              refresh_session_interval = 900,                                                                                                                                     
              renew_access_token_on_expiry = true,
              expiry_claim = "exp",
              ssl_verify = "no",
              redirect_uri_scheme = "https"
            }
            local res, err, _target, session = require("resty.openidc").authenticate(opts)
            if err then
              ngx.status = 500
              ngx.say(err)
              ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
            end
            ngx.req.set_header("Authorization", "Bearer "..session.data.enc_id_token)
          }
          proxy_pass http://localhost:9090;
        }
      }
    }
`

**Comment by zandbelt** [comment]
which version of `lua-resty-openidc` are you on?

**Comment by lbvffvbl** [comment]
1.7.0-2

**Comment by zandbelt** [comment]
The `interaction_required` as returned by your OP indicates that the SSO session at the OP  is expired and explicit user interaction (i.e. authentication) is required to issue new tokens; so you'll have to make sure that the SSO session on the OP lasts longer than the `refresh_session_interval` or do not use "silent" token refresh by setting `refresh_session_interval` to `nil`. Hope that helps.

**Comment by zandbelt** [comment]
any comments to that?

**Comment by lbvffvbl** [comment]
actually it is not convenient with static pages which needed reload to update like kubernetes dashboard. for example if refresh_session_interval is 15 minutes and i do not doing any interaction with page in last seconds and after that i refresh the page i get this error

**Comment by lbvffvbl** [comment]
and if i try to reload page after i got error i will got the error again. in the same time if i try to open dashboard in another tab it will be opened successfully

**Comment by zandbelt** [comment]
you can set `refresh_session_interval` to `nil`
