### ISSUE TITLE
role based access control question

### ISSUE THREAD

**Issue by amiiya** [zmartzone/lua-resty-openidc#222]
Hi!

I'm currently following Keycloaks documentation for setting up an RBAC (https://www.keycloak.org/docs/4.5/authorization_services/index.html). But everything I do doesn't seem to effect Keycloak.

I want to have this:
1. Login to Web UI (--> /webui)
2. Access to dev area when you have a dev role otherwise deny (--> /webui/dev)
3. Access to premium area when you have a premium role otherwise deny (--> /webui/premium)

I enabled Authorization and setup each area as a resource. But the permission don't work no matter what I do. After the openresty redirect I'm always able to access ALL paths even though they should be restricted through Keycloak.

Thank you any help!

**Comment by zandbelt** [comment]
It would be helpful if you provide information such as: the version of `lua-resty-openidc` that you're using, the version of Keycloack, the log files of the NGINX server, and especially the configuration of the NGINX server.

**Comment by amiiya** [comment]
Sorry! Coming right up...

Versions:
```
Keycloak 4.5.0.Final
zmartzone/lua-resty-openidc                                  1.7.0
jkeys089/lua-resty-hmac                                      0.02
bungle/lua-resty-session                                     2.22
openresty/lua-resty-string                                   0.11
cdbattags/lua-resty-jwt                                      0.2.0
pintsized/lua-resty-http                                     0.12
```

Nginx Config:
```
location /webui {
    limit_req zone=backend burst=10 nodelay;
    access_by_lua '
      local opts = {
        discovery = "http://" .. ngx.var.http_host  .. "/auth/realms/internal/.well-known/openid-configuration",
        redirect_uri = "/webui/redirect_uri",
        client_id = "backend",
        client_secret = "%BACKEND_SECRET%",
        logout_path = "/webui/logout",
        post_logout_redirect_uri = "http://" .. ngx.var.http_host .. "/webui",
      }

      local oidc = require("resty.openidc")
      local res, err = oidc.authenticate(opts)

      if err then
        ngx.log(ngx.DEBUG, "authentication failed")
        ngx.exit(ngx.HTTP_FORBIDDEN)
      end

      local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
      if token_err then
        ngx.log(ngx.DEBUG, "access token is not a valid JWT")
        ngx.exit(ngx.HTTP_FORBIDDEN)
      end

      local cjson = require "cjson"
      --ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(parsed_token))
      --ngx.req.set_header("X-ACCESS_TOKEN", res.access_token)
      --ngx.req.set_header("X-ACCESS_TOKEN_DECODED", cjson.encode(parsed_token))

      --local at_cookie = "ACCESSTOKEN_COOKIE=" .. res.access_token
      --ngx.header["Set-Cookie"] = at_cookie
     ';
   expires           0;
   add_header        Cache-Control private;
}
```

I currently don't have valid client authorization configs because I couldn't get in to work but even trying to edit the default permissions don't make a difference. In the default policy (javascript) everyone gets access granted if they are logged in. I tried to change it to $evaluation.deny() so that nobody can access the default /* . But i still can access it.

**Comment by amiiya** [comment]
I'm still not sure how I can manage permission.. How do I setup my OpenResty when i want to do something like this? https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-uma-photoz Would I have to the configuration via OpenResty or as shown in the Keycloak Documentation?

**Comment by zandbelt** [comment]
I think you're mixing authorization in the Keycloak server with access control in the NGINX server: the latter can be done by doing things similar to:
```
if res.user.email ~= "hans.zandbelt@zmartzone.eu" then
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
```

instead of parsing the access token with `oidc.jwt_verify(res.access_token, opts)`

**Comment by amiiya** [comment]
Yes, i saw that solution in your README too. But how would i check assigned roles? I don't quite understand how i should differentiate between authorization in the Keycloak server and access control in NGINX

**Comment by zandbelt** [comment]
Something like:
```
if res.user.role ~= "admin" then
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
```
as you see things depend on the contents of the `id_token` and user info.

**Comment by amiiya** [comment]
So basically everything that is done under Keycloak > Client > Authorization is useless? I can only assign roles to users and how I handle them is with nginx?

**Comment by amiiya** [comment]
Well can you tell me an example where it is useful? In my short experience i couldn't do anything with it (in combination with this module)

**Comment by huegelc** [comment]
Thats the big point: the authorization tab is meant not to work like that in combination with this module

**Comment by DarthSlider** [comment]
@huegelc 
Did you find any solution? I`m also trying to authorize my users on Nginx using token content.

**Comment by zandbelt** [comment]
Just to make sure: anything that is returned by the OP/Keycloak in the `id_token` or from the `userinfo` endpoint can be used to perform access control in NGINX in the way as described. When `res.user` is `nil` it means that the userinfo endpoint call failed or no userinfo endpoint was defined.

**Comment by MaxWinterstein** [comment]
Thanks for the inspiration all, this is what I came out with after some small playaround timebox:

```conf
# inspired by https://eclipsesource.com/blogs/2018/01/11/authenticating-reverse-proxy-with-keycloak/


worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;
# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;
events {
    worker_connections 1024;
}
http {

   lua_ssl_verify_depth 2;
   lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;

   lua_package_path '/usr/local/openresty/lualib/?.lua;;';
   resolver 8.8.8.8;
   include /etc/nginx/conf.d/*.conf;
   # cache for discovery metadata documents
   lua_shared_dict discovery 1m;

   # cache for JWKs
   lua_shared_dict jwks 1m;
   index   index.html index.htm;
   server {
        listen       81 default_server;
        listen       [::]:80 default_server;
        root         /usr/share/nginx/html;
        access_by_lua '
          local opts = {
            redirect_uri_path = "/",
            discovery = "https://keycloak.example.org/auth/realms/master/.well-known/openid-configuration",
            client_id = "nginx-test",
            client_secret = "123-456-789",
            redirect_uri_scheme = "http",
            logout_path = "/logout",
            redirect_after_logout_uri = "https://keycloak.exampe/auth/realms/master/protocol/openid-connect/logout?redirect_uri=http%3A%2F%2Flocalhost%2Ffoo.html",
            redirect_after_logout_with_id_token_hint = false,
            session_contents = {id_token=true}
          }
          -- call introspect for OAuth 2.0 Bearer Access Token validation
          local res, err = require("resty.openidc").authenticate(opts)

          # https://stackoverflow.com/a/33511182
          local function has_value (tab, val)
              for index, value in ipairs(tab) do
                  if value == val then
                      return true
                  end
              end

              return false
          end

          if has_value(res.id_token.groups, "my-test-group") then
              ngx.say("Yep, you are fine and here could be the stuff")
          else
              ngx.say("Nope")

          end

          local cjson = require "cjson"
          ngx.say("<br>")
          ngx.say(cjson.encode(res))

          if err then
            ngx.status = 403
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end
       ';
       # I disbled caching so the browser won't cache the site.
       expires           0;
       add_header        Cache-Control private;
       location / {
       }
       # redirect server error pages to the static page /40x.html
       #
       error_page 404 /404.html;
           location = /40x.html {
       }
       # redirect server error pages to the static page /50x.html
       #
       error_page 500 502 503 504 /50x.html;
           location = /50x.html {
       }
   }
}
```

At keycloak side i added the 'groups' builtin mapper.
