### ISSUE TITLE
"Internal" vs. "External" path for redirections, when deploying with a front-end RP

### ISSUE THREAD

**Issue by pamiel** [zmartzone/lua-resty-openidc#226]
###### Environment
- lua-resty-openidc version (e.g. 1.7.0)
- OpenID Connect provider: Keycloak

###### Actual behaviour
I have an issue related to the redirect URI, whatever using the deprecated `redirect_uri_path` or the new `redirect_uri` parameters.

The issue is linked to my deployment model: the nginx hosting `lua-resty-openidc` is deployed behind another Reverve Proxy. No way to get rid of this front-end RP.
Until now, this front-end RP was managing virtual hosts only (i.e. domain names of the URL) but was not touching the path of incoming requests: `/ui` on the front-end RP was redirected to `/ui` on the Nginx hosting `lua-resty-openidc`, and declaring a `redirect_uri_path` or a `redirect_uri` to the value `/ui/redirect_uri` was working fine. 

Now, I’m requested that the front-end RP proxies to the Nginx (hosting `lua-resty-openidc`) on a different path: `/ui` on the front-end RP shall be proxied to `/internal_ui` on Nginx.
With this deployment, I’m facing the following issue:
-	If the `redirect_uri` field is set to `/ui/redirect_uri` to match the _external_ path (required so that the OP could redirect the flow properly to `lua-resty-openidc`), then `lua-resty-openidc` never catches this redirect as, internally, the URI is proxied to `/internal_ui/redirect_uri` that is not recognized by the library through this code here https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1290 (it is expecting to get `/ui/redirect_uri`)
-	If the `redirect_uri` field is set to `/internal_ui/redirect_uri` to be sure that `lua-resty-openidc` will recognize the call to the Redirect URI, then `/internal_ui/redirect_uri` is this exact path value that will be sent to the OP at the beginning of the authentication process… but this path is not a valid path for the front-end RP (only `/ui/...` is).

Setting a full URI `http://external.domain/ui/redirect_uri` thanks to the new `redirect_uri` parameter does not solve the problem as the Redirect URI path is computed by `lua-resty-openidc` by cutting the path from this full URI => `lua-resty-openidc` will try to detect the `/ui/redirect_uri` path that is never navigated (the front-end RP will transform such calls into `/internal_ui/redirect_uri`).

Indeed, I’m presenting the topic by saying that it is an issue on the Redirect URI… but it is not only on this URI: the issue also applies at the end of the authentication process, when `lua-resty-openidc` performs the last redirect to the original URL (i.e. the one originally navigated at the very beginning of the process, and that is accessed again thanks to a redirect, at the very end of the authentication process): https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1086
This redirection is done using the `session.data.original_url` value that contains the _internal_ URI received by `lua-resty-openidc` at the very beginning of the authentication process. As this is the URI from `lua-resty-openidc`’Nginx point of view, `session.data.original_url` will contain for example `/internal_ui/main.html` if the true _external_ original URL is `/ui/main.html`. So the redirect URI will use an _internal_ URL that is not navigable through the front-end RP. 

Logout does not generate any problem as soon as an _internal_ URL is set in the `logout_path` parameter (`lua-resty-openidc` is not generating any redirect on this URL; it is just detecting whether the path is navigated or not, so an _internal_ URL is mandated)

For the moment, I’ve temporarily solved the problem by patching the `lua-resty-openidc` library by using a string substitution to transform an _internal_ URL to an _external_ URL:
- At the end of function `openidc_get_redirect_uri`:
Instead of `return scheme .. "://" .. host .. path`, I implemented:
```
  if opts.internal_to_external_path_transformation then
    path = string.gsub(path, opts.internal_to_external_path_transformation.substitue, opts.internal_to_external_path_transformation.replace_by)
  end

  return scheme.."://"..host..path
```

- At the end of function `openidc_authorization_response`:
Instead of `ngx.redirect(session.data.original_url)`, I implemented:
```
  local url = session.data.original_url
  if opts.internal_to_external_path_transformation then
     url = string.gsub(url, opts.internal_to_external_path_transformation.substitue, opts.internal_to_external_path_transformation.replace_by)
  end
  ngx.redirect(url)
```

With, consequently, the presence of a new parameter `internal_to_external_path_transformation` that is indeed a table containing the `substitute` and `replace_by` parameters.
In my example, I would set `internal_to_external_path_transformation.substitute` to `”^/internal_ui/”` and `internal_to_external_path_transformation.replace_by` to `”/ui/”`.
I’m ready to push a PR for that, but I’m not sure this is a very smart way to solve the problem, so I prefer to have a talk with you first on the topic so that we agree on the best solution to implement!

So, feel free to give me your feedback about the issue, and to comment my proposal of solution (or recommend any other one): I don’t fully like the one I presented above because in terms of usability, it is not very clear for `lua-resty-openidc` users

1. Which of the URLs or paths to be provided as configuration data of the library should be set with _internal_ or _external_ values (maybe this should be clearly documented), 
2. And on which of them the “path transformation” should apply (it is not a simple rule like: any _internal_ is transformed into _external_).

Maybe documenting it clearly is enough, but I'm not sure.

**Comment by bodewig** [comment]
You can solve the `original_url` case by passing the rewritten URL as `target_url` when invoking `authenticate` but this doesn't solve the `redirect_uri` issue.

We could solve this by a mapping function like the one you suggest or by a static configuration like `local_redirect_uri_path` or similar. If we applied the transformation function to the `original_uri` unconditionally people who provide the `target_url` explicitly need to be warned.

**Comment by pamiel** [comment]
I knew it was good talking to you before pushing anything :smile: 

Starting from your idea: `original_url` can indeed be solved by rewriting the URL before calling `authenticate` (making the received _internal_ URL being now an _external_ URL)... but as soon as I'm doing this, _any_ URL that goes into `authenticate` are now _external_, and thus no longer matching the patterns I defined for `redirect_uri` and for `logout_path` (that were internal up to now !).
So I updated these configuration data to now set _external_ path... and everything magically (!) works, including the Redirect URI (that is still built the same way using `redirect_uri`, but with a value that now contains an _external_ path, so valid from the front-end RP perspective when set a as query parameter in the redirect to the OP).

At the end, I'm just questioning myself whether it is good to have configuration parameters that are using _external_ URIs (meaning that this layer has knowledge of how the solution is globally deployed while it could be agnostic to that and only consider _internal_, i.e. local URLs)... but at least the use case is working, so I think it is ok to close the issue.

**Comment by bodewig** [comment]
Actually I didn't think this through well enough to realize that rewriting `target_url` would solve the problem completely. Thanks for proving it :-)

As `authenticate` needs to know the *external* `redirect_uri` when it creates the parameter used for the authorization and token endpoints there probably is no way around requiring this one to use the external form explicitly. Using `(X-)Fowarded` headers is the built-in way to create external URIs for most deployment cases.
