### ISSUE TITLE
stateless cookie for HA

### ISSUE THREAD

**Issue by Triton-oidc** [zmartzone/lua-resty-openidc#227]
Hi,
I'm trying to do High Availability scenario :
The user should authenticate on an Nginx,
get a Cookie, then present the same Cookie to another Nginx with the same configuration, and i don't want the redirect to the OpenIDConnect Provider

###### Environment

- lua-resty-openidc version 1.7.0
- OpenID Connect provider google

###### Expected behaviour
Having a parameter in the module configuration with to choose between statefull and stateless cookie
And in case of a Stateless Cookie, being able to set the encryption cookie key
###### Actual behaviour
I think it's a statefull Cookie, and i didn't found anyway for the generated cookie to be use on a server which didn't generate it (in an HA scenario)
###### Minimized example
I used the example with the google auth
https://github.com/zmartzone/lua-resty-openidc#sample-configuration-for-google-signin
###### Configuration and NGINX server log files
i don't think the files are relevent, i left all the default options

**Comment by zandbelt** [comment]
that should work using the default (lua-resty-session) settings and using the same `$session_secret` setting on the two nodes

**Comment by Triton-oidc** [comment]
apologies I didn't saw the session_secret ...
I'll update soon, to say it worked ;)

**Comment by Triton-oidc** [comment]
Yeahhhh
success !

Thanks a lot for helping me, you saved me a lot of time finding this solution.
And i'm really sorry for not finding this by myself

Don't know if it was intended, but the 
> set $session_secret xxxxxxxxxxxxxxxxxxx;

line has to be set in the server section
