### ISSUE TITLE
How to properly set up multiple client IDs in he same nginx server?

### ISSUE THREAD

**Issue by pedroquien** [zmartzone/lua-resty-openidc#230]
What is the correct way to set up support for multiple client IDs or adfs style resource Uris using lua resty openidc?

I have tried using different session names as an option for different paths but not sure if there are better ways or if this is not supported.  I have tried to just specify different client IDs for different opts in different paths but it seems to assume to cookie name is the same and thus it doesn't work.  I then tried to specify a separate opt for the session itself for each path but is this really supported to be used this way?

Thanks
Peter

**Comment by zandbelt** [comment]
are you referring to multiple client_id's as in multiple "connections" to multiple OPs? or to a single OP?

**Comment by pedroquien** [comment]
For this example, I'm referring to one OP.  I need to be able to say / is public so no one needs to authenticate.  /foobar is secure and so I need to authenticate, /foobarbaz though is even more secure and so I need to use a different authenticator and possibly this is timebound to a shorter expiration period than just the /foobar secure one.  How does one best do this with lua resty openidc?  Not all OIDC providers allow specifying timeouts and/or authenticators in the same fashion so sometimes they do it by resource, sometimes they do it by clientid, etc.    I'm in need of two differently protected paths with different access tokens with different expirations and either clientids or resource uris associated with them.

**Comment by zandbelt** [comment]
firstly I would question the "design" of this solution; I don't think it makes sense to use different client_id's for a single client instance; you should work with scopes to differentiate between capabilities/entitlements if that's what you're aiming for

secondly: setting `opts.client_id` to a particular value where you need that is the way to go; and yes you'd have to rename the session cookie on a per path instance as well

**Comment by bodewig** [comment]
Using the same Cookie name but different `session_cookie_path` values would work as well as long as the paths don't overlap. In either case you need to configure lua-resty-session on a path by path basis.

**Comment by pedroquien** [comment]
What is the right way to set session cookie path per path?  Set $session_cookie_path seems to set it globally.  Do I set it in opt or do I set it in session opt?  Thanks.

**Comment by bodewig** [comment]
`session_opts` would be the way to go, yes. `{ cookie = { path = "/mypath" } }` for example, see https://github.com/bungle/lua-resty-session#string-sessioncookiepath and e.g. the last example in https://github.com/bungle/lua-resty-session#table-sessionnewopts-or-nil
