### ISSUE TITLE
No session state found after authentication with OP

### ISSUE THREAD

**Issue by JoshTheGoldfish** [zmartzone/lua-resty-openidc#231]
### Environment
kong: 0.14.x
kong-oidc: forked from nokia/kong-oidc - https://github.com/JoshTheGoldfish/kong-oidc
lua-resty-openidc version: 1.7.0 (updated dependency from nokia/kong-oidc to 1.7.0)
OpenID Connect provider: Keycloak

### Expected behaviour
I'm expecting resty-openidc to verify the Access Token passed in the header, and allow the request through.

### Actual behaviour
lua-resty-openidc is returning `request to the redirect_uri path but there's no session state found`

### Minimized example
1. RP (mobile device) authenticates successfully with Keycloak (OP) as client: iosapp
2. Redirect to URL (http://localhost:8000/mock, which is Kong in this case) 
3. Kong returns 500 Internal Server Error

### Configuration and NGINX server log files
Kong/nginx configuration files: [configs.zip](https://github.com/zmartzone/lua-resty-openidc/files/2566732/configs.zip)

Kong/Keycloak debug logs (truncated to contain only relevant info): 
[logs.zip](https://github.com/zmartzone/lua-resty-openidc/files/2566740/logs.zip)

Also, if you're interested, a Wireshark capture of the HTTP packets exchanges between the RP, Keycloak, and the RP & Nginx: 
[wireshark-cap.zip](https://github.com/zmartzone/lua-resty-openidc/files/2566802/kong-client-login-seq.pcapng.2.zip)

Keycloak config for Kong client:
![image](https://user-images.githubusercontent.com/11929593/48277495-194abd80-e408-11e8-8f27-b1b9ea133c88.png)

Keycloak config for iOS Mobile Application:
![image](https://user-images.githubusercontent.com/11929593/48277532-3089ab00-e408-11e8-8d87-7ac31d8ba266.png)

I'm only running a single instance of Kong. Please let me know if I can assist with any additional information.

**Comment by bodewig** [comment]
I don't see `request to the redirect_uri path but there's no session state found` in the `kong-logs.txt` you've provided.

**Comment by JoshTheGoldfish** [comment]
Ah, those were the success logs when I was hitting Kong from my browser. Error logs (debug level) attached.
[error-logs.zip](https://github.com/zmartzone/lua-resty-openidc/files/2567296/error-logs.zip)

**Comment by bodewig** [comment]
Sorry for the delay, I'm doing this in my spare time.

Looking through your pcap file I don't see any Cookies in the request that comes back from your OP to the RP (frame 177). I thinkl this is the reason lua-resty-openidc doesn't see any session.

**Comment by ross211** [comment]
Might be this issue https://bugs.webkit.org/show_bug.cgi?id=188165 which is impacting new macOS (Mojave) and iOS versions.

You could try setting `set $session_cookie_samesite "";` in your nginx config to test that.

**Comment by bodewig** [comment]
or `set $session_cookie_samesite off` if you like it explicit :-)

https://github.com/bungle/lua-resty-session#string-sessioncookiesamesite

Yes, this would explain the lack of Cookies.

**Comment by JoshTheGoldfish** [comment]
I tried setting this in my nginx-kong.conf. Relevant config below:

```
server {
    set $session_cookie_samesite off;

    server_name kong;
    listen 0.0.0.0:8000;
    listen 0.0.0.0:8443 ssl;
    error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
    error_page 500 502 503 504 /kong_error_handler;
...
}
```

However, I'm still getting the same error shown on the mobile device. Thanks for the suggestions @ross211  & @bodewig.

I checked out that pcap file and I am seeing both KEYCLOAK_SESSION and KEYCLOAK_REMEMBER_ME cookies set. However, they're in frame 171, not 177. I believe 177 is from the RP to Kong (policy enforcement point), and 171 is from OP to RP.

I'm seeing the same sequence of packets when I add the samesite config: [wireshark-cap-samesite.zip](https://github.com/zmartzone/lua-resty-openidc/files/2576811/wireshark-cap-samesite.zip)

Kong and Keycloak logs are nearly identical to what I shared before. Am I setting `$session_cooking_samesite` correctly?

**Comment by JoshTheGoldfish** [comment]
Just did a compare on of a successful browser login vs a iOS login w/ Wireshark. Besides the massive difference in the number of HTTP packets sent back and forth, I think the crux of the issue here is that iOS is not sending a session cookie.

After browser login:
![broswer-post-login](https://user-images.githubusercontent.com/11929593/48425799-c84a0a80-e722-11e8-860e-9989615cbfe7.png)

After iOS login:
![ios-post-login](https://user-images.githubusercontent.com/11929593/48425880-f0396e00-e722-11e8-843b-9166df564644.png)

**Comment by bodewig** [comment]
lua-resty-openidc sets its own session cookie and this one must be included inside the request to the RP. Without that, things just won't work.

The more interesting HTTP request when it comes to verifying `SameSite` actually is set correctly is the request that redirects from your RP to the OP.

**Comment by JoshTheGoldfish** [comment]
I'm fairly new to all of this stuff so I just want to verify I'm communicating this well: RP = Relying Party = iOS App (in this case)? In the picture below, "RP is 1 to n possible mobile apps"

I'm not sure how that session cookie could be in the request when the iOS app won't interact with lua-rest-openidc until after authentication, like below:

![screen shot 2018-11-13 at 09 17 13](https://user-images.githubusercontent.com/11929593/48427014-1b24c180-e725-11e8-9e71-47033b9d8615.png)

Am I just configuring this the wrong way entirely?

**Comment by bodewig** [comment]
RP to me was the server running lua-resty-openidc as I assumed you'd be calling `authenticate` which runs the authorization code grant flow. I'm not familiar with how Kong uses lua-resty-openidc at all.

So let's stop using the RP nomenclature :-)

Your mobile app tries to connect to an API which sits somewhere behind an nginx running lua-resty-openidc. If your app is using the authorization code grant flow then it make a request to the API is redirected to Keycloak and after login is redirected back, This is what `authenticate` supports. In this scenario your app should receive a cookie from lua-resty-openidc on the first request (the redirect to Keycloak) and it must come back to the redirect_uri presenting that same cookie. This doesn't seem to happen. But maybe this is not even the flow you are using.

**Comment by JoshTheGoldfish** [comment]
If I'm understanding the specs correctly (I'm using https://github.com/openid/AppAuth-iOS), the ONLY flow I can use is the authorization code grant flow.

Perhaps the issue is that my authentication is happening without open resty ever ever getting involved. How is it going to set a cookie if I never connect with it, right?

This is what we're doing:

![image](https://user-images.githubusercontent.com/11929593/48432245-10702980-e731-11e8-95a0-43ca8f3058e8.png)

Does lua-rest-openidc supports this? I'm doubting this because of what you said earlier.

> If your app is using the authorization code grant flow then it make a request to the API is redirected to Keycloak and after login is redirected back, This is what `authenticate` supports.

However, this isn't what we're trying to build. Instead, we're trying authenticate without getting lua-resty-openidc involved, get the access token, then make the request through the Nginx proxy.

**Comment by bodewig** [comment]
How do you obtain the token in 1?

Apart from being the client in the authorization code grant flow via `authenticate` lua-resty-openidc can also act as resource server and accept a token provided as a Bearer token in an `Authorization` header when the `bearer_jwt_verify` function is used. Of course I don't know whether Kong supports this.

**Comment by JoshTheGoldfish** [comment]
Just as an aside: Kong supports it though the [kong-oidc](https://github.com/nokia/kong-oidc) plugin. I know it well enough to modify it, if needed. It's really just calling the `authenticate` method from the lua-resty-openidc with some configuration parameters.

The token is being obtained like this (from perspective of the iOS app):

1. Get discovery data
2. Call to auth end point (endpoint returns HTML login form)
3. Enter login data
4. POST to localhost:8180/auth/realms/<realm>/login-actions/authenticate with username/password data in body of request. localhost:8180 is where Keycloak is running
5. Get access token (this is happening behind the scenes w/ AppAuth-iOS)

I saw the `bearer_jwt_verify` content in the code. From what I can tell, kong-oidc never calls this. Should I configure it to do so in the event that an Access Token is in the header?

**Comment by bodewig** [comment]
In what you describe the iOS app is the client in OAuth2 lingo. This is the role lua-resty-openidc wants to play itself when `authenticate` is used. What you describe asks Kong to act as the resource server which is `bearer_jwt_verify`'s purpose.
I wonder whether there is a different setup or plugin for Kong that makes it act that way. https://docs.konghq.com/hub/kong-inc/openid-connect/ has a section "Protecting Access to APIs with Stateless JWT Tokens" which sounds about right, but I haven't dug any deeper.

**Comment by JoshTheGoldfish** [comment]
Would love to use that, but we're using the CE version of Kong :)

I'm fairly certain I can modify the [kong-oidc](https://github.com/nokia/kong-oidc) plugin (free version) to do the task assigned.

At this point I think it's clear to me that the problem is because the plugin I'm using doesn't support what I'm trying to do. But the lua-resty-openidc project clearly does support what I'm trying to do. Thanks for all your help @bodewig!
