### ISSUE TITLE
Support for PKCE

### ISSUE THREAD

**Issue by rboykin** [zmartzone/lua-resty-openidc#237]
###### Environment
- lua-resty-openidc version (e.g. 1.7.0)
###### Expected behaviour
Support for the PKCE protocol as defined here https://tools.ietf.org/html/rfc7636
###### Actual behaviour
Does openidc support PKCE? I could not find support for the `code_challenge` on the authorization_endpoint flow or the `code_verifier` on the token_endpoint flow. I could support the `code_challenge` query param using the opts.authorization_params. But, I did not see a way to provide the `code_verifier` query param on the token_endpoint flow.

I am hoping I am just missing something. If not, are there plans to support PKCE anytime soon?

**Comment by rboykin** [comment]
@zandbelt We are trying to secure nginx where the end user has access to the nginx environment, thereby being able to access the client id and client secret. But, we don't want the client secret to be shared with that consuming user. PKCE appears to remove this need. It also removes the possibility of a man-in-the-middle exposure.

**Comment by zandbelt** [comment]
if the end user has access to the NGINX environment, why are you even trying to secure anything at all? the enduser would just undo this config and replace it by something he likes better

**Comment by zandbelt** [comment]
well just to be complete for the reason you mention: PCKE is usually used with OAuth 2.0
