### ISSUE TITLE
After successful authentication it would be good to have an option to not automatically redirect to original url

### ISSUE THREAD

**Issue by pedroquien** [zmartzone/lua-resty-openidc#245]
It would be good to allow the calling Lua code to do some additional checks after a successful authentication without causing a redirect and then flow back into nginx for an authentication check.  

One scenario is that sometime we want to check additional claims in the access token before redirecting back to original url.

###### Environment

- lua-resty-openidc version (e.g. 1.7.0)
- OpenID Connect provider (e.g. Keycloak, Azure AD)

###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*

###### Configuration and NGINX server log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
you can provide a callback URL to the `authenticate()` call

**Comment by pedroquien** [comment]
How do I set the callback after authentication?

It would also be good if the session can keep the additional parameters in
the cookie so that a callback can check for the parameters after
authentication instead of hardcoding in the nginx conf Lua code.

**Comment by zandbelt** [comment]
you can all do that from the calling code

**Comment by pedroquien** [comment]
Hi Hans,

I will take a look at the code again but it seemed like after a successful
authentication, if I don't use "pass" then it would always redirect to the
original url?  I did not see a callback that can be specified.

For example in ADFS, at least the version we're using, right now it uses
resources instead of scope so I must always pass a resource name during
login.  After login, I want to be able to validate the resource name of the
access token coming back from openidc.

Thanks for all the great work on lua resty openidc by the way.

Peter

**Comment by zandbelt** [comment]
instead of using:
```
          local res, err = require("resty.openidc").authenticate(opts)
```
one can use:
```
          local res, err = require("resty.openidc").authenticate(opts, target_url)
```
where `target_url` points to the location you want to be redirected to after returning from the OP

**Comment by pedroquien** [comment]
Ah.  I was hoping to be able to handle the validation of the resource after
the authentication event in Lua while still in nginx before redirecting to
the original url.

**Comment by zandbelt** [comment]
there should be no reason to do that: anything you wish to implement can be done after the validation of the resource
