### ISSUE TITLE
Lifecycle customization points

### ISSUE THREAD

**Issue by arcivanov** [zmartzone/lua-resty-openidc#251]
Advanced uses often require augmenting the session state with additional data that is based on the payloads retrieved during OIDC flow. Currently there is no way to differentiate between initial OIDC authentication result and session being restored from the cookie.

This feature proposes allowing to specify functions in configuration properties for lifecycle events such as "session created", "session restored", "session destroyed".

PR to follow.

**Comment by thomasleplus** [comment]
Hi @arcivanov, I am trying to add a custom value in the session so it seems like lifecycle.on_created would be a perfect hook for that. But I am a Lua beginner so I am afraid I don't know how to create a callable. Any idea where I could find an example? Thanks in advance for any help you can provide.
