### ISSUE TITLE
Function authenticate does not return enc_id_token

### ISSUE THREAD

**Issue by schuhmacherar2r** [zmartzone/lua-resty-openidc#256]
###### Environment

- 1.7.1
- GLUU 3.1.3
###### Expected behaviour
local opts = {
...
                session_contents = {enc_id_token=true}
            }
...
local res, err = openidc.authenticate(opts)
...
ngx.req.set_header("Authorization", "Bearer " .. res.enc_id_token)
###### Actual behaviour
 res.enc_id_token always null
###### Minimized example
https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua
Line 1345
-- main routine for OpenID Connect user authentication
function openidc.authenticate(opts, target_url, unauth_action, session_opts)

...

Line 1455
  -- return the id_token to the caller Lua script for access control purposes
  return
  {
    id_token = session.data.id_token,
    access_token = access_token,
    user = session.data.user
  },
  err,
  target_url,
  session
end

**Comment by bodewig** [comment]
Setting `session_contents = {enc_id_token=true}` makes lua-resty-openidc store the encrypted id token inside the session, which is returned as the forth item by `authenticate` and you should be able to pick it up from there. There is no relation between `session_contents` and the first table returned by `authenticate`.

We could add the encrypted id token to the first table as well, but I'm not sure where we'd want to draw the line. There are other "things" that could be in there as well.

**Comment by schuhmacherar2r** [comment]
Hello Stefan,
it would be better "add the encrypted id token to the first table". e.g.:

openidc.lua
return
  {
    id_token = session.data.id_token,
    access_token = access_token,
    user = session.data.user,
    **enc_id_token = session.data.enc_id_token**
  },
  err,
  target_url,
  session

otherwise I have to get `enc_id_token` from session. e.g.:

nginx.conf
local res, err, target_url, **session** = openidc.authenticate(opts)
...
ngx.req.set_header("Authorization", "Bearer " .. **session.data.enc_id_token**)

MfG
Arthur Schuhmacher

**Comment by zandbelt** [comment]
I don't see the problem with the current solution either.
