### ISSUE TITLE
Wiki error for Cloudflare access token validation

### ISSUE THREAD

**Issue by shiftie** [zmartzone/lua-resty-openidc#259]
Hi! I think that Cloudflare access token validation from wiki has an error: 
https://github.com/zmartzone/lua-resty-openidc/wiki/Sample-Configuration-for-Cloudflare-JWT-Token-validation

It looks like `if json.aud[1] ~= opts.client_id then` should be `if json.aud ~= opts.client_id then` since the `aud` is just a string.

**Comment by zandbelt** [comment]
feel free to edit that Wiki page by yourself
