### ISSUE TITLE
Pure OAuth2 scenario not supported because of id_token validation

### ISSUE THREAD

**Issue by mjameswh** [zmartzone/lua-resty-openidc#261]
Connecting to a pure OAuth2 server (that is, servers that do not comply with OpenID Connect) is almost working, but lead to a JWT validation error to a missing condition.

###### Expected behaviour

According to file README.md "lua-resty-openidc is a library for NGINX implementing the OpenID Connect Relying Party (RP) and/**or the OAuth 2.0 Resource Server (RS) functionality**." The pure OAuth2 scenario should therefore work without error.

###### Actual behaviour

Execution fails in `openidc_load_jwt_and_verify_crypto` because `id_token` is nil:

    bad argument #1 to 'match' (string expected, got nil)

###### Minimized example

Pure OAuth2 do not provide "discovery" mechanism; JWT based authentication is also generally not supported. It is therefore required to explicitly specify the authorization and token endpoints in `opts.discovery`, and to set option `token_endpoint_auth_method` to either `client_secret_post` or `client_secret_basic`. For example:

            local opts = {
                discovery = {
                    authorization_endpoint = "https://auth.example.net/oauth2/authorize.php",
                    token_endpoint = "https://auth.example.net/oauth2/token.php"
                },

                token_endpoint_auth_method = "client_secret_post",

                -- Might need more options here...

                session_contents = {
                    access_token = true
                }
            }

**Comment by zandbelt** [comment]
You're conflating an OAuth 2.0 access token only Authorization Code flow for a Client (which is what lua-resty-openidc is in the OIDC case) with the pure OAuth 2.0 Resource Server scenario: in the latter setup there's no authorization response and one would not call `authenticate` but just `bearer_jwt_verify ` or `introspect`. See also the examples in the `README.md` for the details on an OAuth 2.0 Resource Server setup.

**Comment by mjameswh** [comment]
Yes, you are indeed right... I really need openresty to act as an OAuth2 **client**, where as lua-resty-openidc's documentation discuss about being an OAuth2 resource server... My mistake.

Now, it so happen that lua-resty-openidc _can_ be used as a pure OAuth2 client, if configured as I described previously _and_ we do not assume that the token endpoint's reply actually contains field `id_token`. I have just done so here and it works great (see PR #262).

Note that I only filed this issue because many projects prefer that code contributions be associated with clear bug reports. For my part, the issue is actually resolved by the PR.

**Comment by zandbelt** [comment]
It may do what you what but it renders an insecure setup, see: 
https://oauth.net/articles/authentication/
http://www.thread-safe.com/2012/01/problem-with-oauth-for-authentication.html

OpenID Connect exists for a reason: because OAuth 2.0 cannot be used for user authentication.
