### ISSUE TITLE
Issues validating JWT

### ISSUE THREAD

**Issue by ncpe20012003** [zmartzone/lua-resty-openidc#263]
Obtaining JWT from AWS Cognito, so my discovery statement:
local opts = {discovery = "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_0AYEG944k/.well-known/openid-configuration"}

When I hit my endpoint:
accessing discovery url (https://cognito-idp.us-east-1.amazonaws.com/us-east-1_0AYEG944k/.well-known/openid-configuration) failed: 20: unable to get local issuer certificate

What am I missing here?

**Comment by bodewig** [comment]
Your default TLS configuration doesn't trust the certificate provided by the Cognito endpoint. You need to add the necessary certificates to complete the trust chain to the truststore used by `resty.http` i.e the file pointed to by `lua_ssl_trusted_certificate` (see https://github.com/openresty/lua-nginx-module#tcpsocksslhandshake for more details).

**Comment by zandbelt** [comment]
can we close this?

**Comment by ncpe20012003** [comment]
Yes please.

**Comment by henkesde** [comment]
Hey,

@ncpe20012003 Did you get your code working? Would you mind to share your code to make auth working with AWS cognito? I'm unable to get it running.

Best Regards,
Dennis
