### ISSUE TITLE
authorization code flow isn't working (without id_token, only access_token)

### ISSUE THREAD

**Issue by ebcflo** [zmartzone/lua-resty-openidc#267]
Hey,
I have used this lua-module without troubles for Auth0, but now I have a project where I need a different type of the Authorization Code Flow (without id_token returned!). In my opinion this should also work, because all necessary information is in the access_token and it should be supported.
See here: [Specification from IETF](https://tools.ietf.org/html/rfc6749#section-4.1)
Maybe I have trouble with my configuration or it isn't supported?

###### Environment

- lua-resty-openidc version (I think 1.7.1)
- OpenID Connect provider: F5 BigIP

###### Expected behaviour
lua-resty-openidc should parse the JWT and redirect to origin.

###### Actual behaviour
lua-resty-openidc redirects to the login page, after login a 500 http error appears.

###### Minimized example
I want to use the following OAuth2 Flow:

See here:
if openid is not included (authorization code flow defined in RFC 6749):
[Image: Authorization Code Flow without openid in scope](https://cdn-images-1.medium.com/max/1200/1*Pxdsn71Qm1liZu6glfvjag.png)
[Image: Issued tokens](https://cdn-images-1.medium.com/max/1200/1*Q9U3VBCYFf-uUMe15hR30A.png)

###### Configuration and NGINX server log files
Server config:
 `
worker_processes  1;
error_log /usr/local/openresty/nginx/logs/error.log debug;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    keepalive_timeout  65;
        lua_package_path '~/lua/?.lua;;';
 server {
    listen 80;
    server_name "nexus.example.com";
    location / {
        access_by_lua_block {
            local opts = {
                redirect_uri = "https://test-oidc.example.com/callback",
                discovery = "https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration",
                client_id = "XXX",
                client_secret = "XXX",
                scope = "",
                ssl_verify = "no",
                access_token_expires_leeway = 30,
                accept_none_alg = true,
                accept_unsupported_alg = true,
                token_endpoint_auth_method = "client_secret_basic",
                renew_access_token_on_expiry = true,
                use_nonce = false,
                session_contents = { id_token=true, access_token=true }
            }
          local res, err = require("resty.openidc").authenticate(opts)

          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

      }
      proxy_http_version 1.1;
      proxy_set_header Host "nexus.example.com";
      proxy_pass http://10.100.0.38/;
    }
    location /appgwhealth {
        stub_status on;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
    lua_shared_dict discovery 1m;
    resolver 1.1.1.1;
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
    lua_ssl_verify_depth 5;

}
`

Server logs:
`
2019/05/17 08:44:19 [debug] 36#36: *16 [lua] openidc.lua:1402: authenticate(): session.present=nil, session.data.id_token=false, session.data.authenticated=nil, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=true, try_to_renew=true, token_expired=false
2019/05/17 08:44:19 [debug] 36#36: *16 [lua] openidc.lua:560: openidc_discover(): openidc_discover: URL is: https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration
2019/05/17 08:44:19 [debug] 36#36: *16 [lua] openidc.lua:115: openidc_cache_get(): cache hit: type=discovery key=https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration
2019/05/17 08:44:19 [debug] 36#36: *16 [lua] openidc.lua:657: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_basic
2019/05/17 08:44:19 [debug] 36#36: *16 [lua] openidc.lua:1430: authenticate(): Authentication is required - Redirecting to OP Authorization endpoint
10.100.0.213 - - [17/May/2019:08:44:19 +0000] "GET / HTTP/1.0" 302 167 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:1362: authenticate(): Redirect URI path (/callback) is currently navigated -> Processing authorization response coming from OP
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:560: openidc_discover(): openidc_discover: URL is: https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:115: openidc_cache_get(): cache hit: type=discovery key=https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:657: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_basic
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:1087: authenticate(): Authentication with OP done -> Calling OP Token Endpoint to obtain tokens
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:429: call_token_endpoint(): client_secret_basic: authorization header 'Basic YzJmNGY3YTYyMGNiM2VhNWRiZTMxZjRiMGQ0ZTAwMGE0OWIyZDFmOGZkNjU0OTVjOjg0NWYyOWFmOTNiNDc2Yzg5YTg4OTA1ZjU0NWEwMDBhNDliMmQxZjhmZDY1NDk1Yw=='
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:484: call_token_endpoint(): request body for token endpoint call: redirect_uri=https%3A%2F%2Ftest-oidc.example.com%2Fcallback&grant_type=authorization_code&state=6a36ad4b50d7f556d978c4dd879206d4&code=cf45dd51fc6a732ec783fc260e1180faeb961d0a4472e6a43688a767cb89e4ce
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:407: openidc_configure_proxy(): openidc_configure_proxy : don't use http proxy
2019/05/17 08:44:34 [debug] 36#36: *17 [lua] http.lua:633: send_request():
POST /f5-oauth2/v1/token HTTP/1.1
User-Agent: lua-resty-http/0.12 (Lua) ngx_lua/10011
Content-Length: 197
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YzJmNGY3YTYyMGNiM2VhNWRiZTMxZjRiMGQ0ZTAwMGE0OWIyZDFmOGZkNjU0OTVjOjg0NWYyOWFmOTNiNDc2Yzg5YTg4OTA1ZjU0NWEwMDBhNDliMmQxZjhmZDY1NDk1Yw==
Host: oauth-d.example.com

2019/05/17 08:44:34 [debug] 36#36: *17 [lua] openidc.lua:501: call_token_endpoint(): token endpoint response: {
  "access_token":"ewogICJhbGciOiJSUzUxMiIsCiAgImtpZCI6InJiLWRfand0X3NpZ24iCn0.ewogICJ0b2tlbl90eXBlIjoiQmVhcmVyIiwKICAiaXNzIjoiaHR0cHM6Ly9vYXV0aC1kLnJlZGJ1bGwuY29tIiwKICAiYXVkIjpbCiAgICAicmVkYnVsbC5jb20iCiAgXSwKICAic3ViIjoiZnByb2JzdCIsCiAgImp0aSI6IjQ0M2IzMGEyOTkwY2ZiMzU0YzcwYjkwYTczZjE4Y2Y4OWUwYzg0NWYzNTEwZmYyMDU2YjE0YjM4ODIwMTg3MzEiLAogICJpYXQiOjE1NTgwODI2NzQsCiAgImV4cCI6MTU1ODA4NDQ3NCwKICAibmJmIjoxNTU4MDgyMzc0Cn0.JpnY7qZRJ1xVEj2Yy0qlx_yk09VkqtTftF1dxCMfsVq8O2rTCShz-yFSiQTX_5F7dvzmFBkkbYuVJrQMYJpIvS_54buhNVq9Zfd5EUzDWLSXrbiseKLtgnR1kbjrZakK3h5TQ7hkUGGQtteXyeuYjnzGNhZ8t5qL3IwbmdxTTxvRB1Y3-A8qqsnoriCMV_8kHbGHRlnrEswzGwdmtDyJn-jp9TJ85nB3lwQ-3i_lqPVPNxQI7OLE3SlKaihnROiqPQ9bDU9DDXYLY8voEf6xrbxpmploLf4Av8knpNzrIRyHsgB8h-5wEF7Ku4fXLvgMj8cqChk1FZOFwFUjs50nnQ",
  "expires_in":"1800",
  "token_type":"Bearer",
  "scope":"",
  "refresh_token":"P62-Quu5T0mrZbYGzg-ylVySipKgl698tYIOzX2-Q9qp5eFyFXIAtgeiAkEZBk8kWcdK4EPzwuz4Q7A_88DKE6bzAXSlCNkGcViVoP8VzATQ8UtvOULUjI_TyE4_JUIFITBygND2q7XMo1nNTljW8UbfEhcNMP_ahuJwkyyNTfsnGB_LI_i_r2SdutpqngV_N_HMFNkJy6c30wM14DLlwGRLeUjOCrmP6KxCMWZ9XEtdPR2Hmn6afp8TMzgSjWstBYMWSie3b_vft_5nbdU6yXRBXSkv0-j2nrK90jxHaB5cPcaMGAomzHXCY6VALtiFeFmqXqI3cAjooFsf-Z9YqCYcAbDa0_8YOdWzSUimnyfj8GCoYc0md3vDkgavRHU6tc1TH2V-NgLEL5VIWopS6OKfXOfn5L09qjYl9ocXI604BaI8Lb5bRcQZvP2Q2XEcP8Uu4S9D3xbKcvEfxu9ze9bv5O2Ze0e5roK6uTvbn2bGw0h2yth7rP3bBbo2Qg5Viu3S845oU0XkphIl1DyICw4Kt5JtOwHqQORKGZEdISycKapKIOSjICY4DfAs96o"
}

2019/05/17 08:44:34 [error] 36#36: *17 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/openidc.lua:923: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'match'
        /usr/local/openresty/lualib/resty/openidc.lua:923: in function 'openidc_load_jwt_and_verify_crypto'
        /usr/local/openresty/lualib/resty/openidc.lua:1009: in function 'openidc_load_and_validate_jwt_id_token'
        /usr/local/openresty/lualib/resty/openidc.lua:1097: in function 'authenticate'
        access_by_lua(nginx.conf:72):19: in function <access_by_lua(nginx.conf:72):1>, client: 10.100.0.213, server: nexus.example.com, request: "GET /callback?code=cf45dd51fc6a732ec783fc260e1180faeb961d0a4472e6a43688a767cb89e4ce&state=6a36ad4b50d7f556d978c4dd879206d4 HTTP/1.0", host: "test-oidc.example.com", referrer: "https://logon-d.example.com/"
10.100.0.213 - - [17/May/2019:08:44:34 +0000] "GET /callback?code=cf45dd51fc6a732ec783fc260e1180faeb961d0a4472e6a43688a767cb89e4ce&state=6a36ad4b50d7f556d978c4dd879206d4 HTTP/1.0" 500 541 "https://logon-d.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
2019/05/17 08:44:34 [debug] 36#36: *20 [lua] openidc.lua:1402: authenticate(): session.present=true, session.data.id_token=false, session.data.authenticated=nil, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=true, try_to_renew=true, token_expired=false
2019/05/17 08:44:34 [debug] 36#36: *20 [lua] openidc.lua:560: openidc_discover(): openidc_discover: URL is: https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration
2019/05/17 08:44:34 [debug] 36#36: *20 [lua] openidc.lua:115: openidc_cache_get(): cache hit: type=discovery key=https://oauth-d.example.com/f5-oauth2/v1/.well-known/openid-configuration
2019/05/17 08:44:34 [debug] 36#36: *20 [lua] openidc.lua:657: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_basic
2019/05/17 08:44:34 [debug] 36#36: *20 [lua] openidc.lua:1430: authenticate(): Authentication is required - Redirecting to OP Authorization endpoint
`

**Comment by zandbelt** [comment]
Please read https://oauth.net/articles/authentication/ to understand why this is not appropriate.

**Comment by indygoof** [comment]
So, i've read this myself and dont get why it isnt appropriate. There seems to be an issue with the timeout (try_to_renew=true) directly after the initial token retrieval even though the actual token should be valid for longer.

Maybe you can elaborate a bit further?
