### ISSUE TITLE
Suppress logout if no session is present?

### ISSUE THREAD

**Issue by bodewig** [zmartzone/lua-resty-openidc#273]
Context is a request to lua-resty-openidc's logout-URI when there is no session associated with the current request - and a OpenID Connect Provider that announces an `end_session_endpoint`.

###### Environment

- lua-resty-openidc version 1.7.1
- OpenID Connect provider ORY Hydra

###### Expected behaviour

I'm not sure whether this is really something I'd expect or just would want to see :-)

If there doesn't seem to be any logged in end user than I'd like to skip calling the `end_session_endpoint` completely. Or at least have the option to do so.

ORY Hydra rejects the request if there is no `Id_token_hint` which seems to contradict https://openid.net/specs/openid-connect-session-1_0.html#RPLogout and I'll open an issue there as well, but it might be worth suppressing the request altogether.

###### Actual behaviour

The `end_session_endpoint` is invoked without any `id_token_hint` parameter.

**Comment by bodewig** [comment]
Just an update, Hydra only requires `id_token_hint` when I request a post logout redirect as it requires them to be pre-configured by clients. The behavior looks reasonable to me. (context: https://github.com/ory/hydra/issues/1472)

**Comment by zandbelt** [comment]
I feel that in some edge cases it may still happen that the OP end session endpoint could be called even if there's no user session at the RP (e.g. perhaps because it was just deleted in a parallel logout request). But regardless, I think it would improve robustness to have the failing end session call deal with the error in a more elegant way.

**Comment by bodewig** [comment]
Unfortunately the OpenID Connect spec doesn't provide any error handling mechanisms. There is no callback if an error occurs or anything similar. In my particular case the OIDC provider presents an error message to the end user (well, I could override the error page to make it do what I want).

I agree there may be cases  where I want to have the RP initiated logout go through, I'm not sure how to deal with it myself. We could add more configuration options or a callback function allows me to construct the redirect from outside of lua-resty-openidc - or we can keep the code as it is and I need to ensure `opts` is set up correctly depending on whether a session exists before invoking `authenticate`.

**Comment by bodewig** [comment]
The case of logout being called when lua-resty-openidc doesn't know there is an active session seems to be a corner case that I really wouldn't want to pollute the code base with. Saying "don't call the OP" is not enough as you probably don't want to display lua-resty-openidc's default "Logged Out" page either.

I see two options:
1. leave things as they are
2. provide an optional configurable function that allows the caller to control what happens

For the second option I've sketched https://github.com/zmartzone/lua-resty-openidc/commit/026b981f25bfd52ab96e019d769bb19b1f491fe7 which I could grow into a real change (including a test and docs) if this is something you'd see in scope of this library @zandbelt . Otherwise I'd drop this case until it comes up for anybody else than me.

**Comment by zandbelt** [comment]
doesn't the "pollute" consist one if statement and an early return?

**Comment by bodewig** [comment]
I'm not sure, what would the "early return" do? Not call the OP but what else? This is what would likely need extra configuration as well.

In my case I'd want a redirect to a different URL than the OP's end_session_endpoint but I'm not sure this generally is the intended behavior.

**Comment by bodewig** [comment]
What would be the option you see with just one if?

**Comment by zandbelt** [comment]
I think we should leave it as it is then for now and keep the custom handler feature in our archive. If there's more demand in the future we can still add it. I don't want to complicate things more than they are now.

**Comment by bodewig** [comment]
that's fine with me
