### ISSUE TITLE
Question - Make Session survive a reload?

### ISSUE THREAD

**Issue by awalende** [zmartzone/lua-resty-openidc#275]
Hi there,

not really an issue, more a simple question.

I'm using lua-resty-openidc to protect various (reverse-proxied) locations in my config. 
User have to authenticate beforehand in order to reach the location via Google.

This works all great, really an awesome library.
However I have to frequently reload configuration snippets (adding and removing locations dynamically). A reload forces my users to authenticate again at google when refreshing proxied urls, it seems that the session is not able to survive this. Not really sure if this is even caused by a lost session.

Is it possible to make sessions survive a configuration reload?

**Comment by bodewig** [comment]
It really depends on how you have configured session management in nginx. We use https://github.com/bungle/lua-resty-session and it has a lot of options.

Unless you configure something explicitly you will be using Cookie based sessions where the Cookie's content is encrypted with a random key that is different for each instance and changes with each restart. This would lead exactly to the situation you describe. If this is what you do, then the trivial solution is to configure the session key `$session_secret` explicitly.

But the library offers a lot of different options with persistent server side session storage, for example.

**Comment by awalende** [comment]
Setting the `$session_secret` worked for me.
Thank you!
