### ISSUE TITLE
Support for NGINX Stream Servers?

### ISSUE THREAD

**Issue by timdagit** [zmartzone/lua-resty-openidc#281]
Hi,

I wondered if you had any plans to add support for NGINX Stream servers? I have used your module, within OpenResty, for http server blocks and it works like a charm. Very easy to set up and operate. 

I also have some upstream resources that require tcp Stream server config though, and I realised this is not currently supported by lua-resty-openidc. I don't how hard that would be to extend but it would be interesting if it was possible.

thanks,

**Comment by zandbelt** [comment]
that's not possible since OIDC is defined on HTTP
