### ISSUE TITLE
Add state parameter to logout redirect

### ISSUE THREAD

**Issue by fenech** [zmartzone/lua-resty-openidc#282]
Hi, I am trying to use this library along with ORY Hydra and I'm having an issue with logout, which I believe could be resolved by adding some functionality to this library.

The relevant parts of my config are:
```lua
        session_contents = { enc_id_token = true, access_token = true },
        logout_path = "/logout",
        redirect_after_logout_uri = "/hydra/oauth2/sessions/logout",
        redirect_after_logout_with_id_token_hint = true,
        post_logout_redirect_uri = "http://example.com/"
```
From their docs (https://www.ory.sh/docs/next/hydra/oauth2#logout):

> If post_logout_redirect_uri is set, the URL query SHOULD contain a state value. On successful redirection, this state value will be appended to the post_logout_redirect_uri. The functionality is equal to the state parameter when performing OAuth2 flows.

As I understand from the login code, the state is generated using:
```lua
 local state = resty_string.to_hex(resty_random.bytes(16))
```
so I guess that the logout code could do the same thing.

###### Environment

- lua-resty-openidc version 1.7.2
- ORY Hydra

###### Expected behaviour

GET `/logout` triggers a redirect to `/hydra/oauth2/sessions/logout`
with query parameters:
- `post_logout_redirect_uri`
- `id_token_hint`
- `state`

###### Actual behaviour

GET `/logout` triggers a redirect to `/hydra/oauth2/sessions/logout`
with query parameters:
- `post_logout_redirect_uri`
- `id_token_hint`

**Comment by fenech** [comment]
Opened a pull request #283 which adds the state parameter.

**Comment by zandbelt** [comment]
spec-wise the state parameter is a SHOULD and Ory must be able to deal with it lacking; implementation-wise I'd argue that a random state value that is unused, is just as useful as adding one statically in the configuration to the logout endpoint...

**Comment by fenech** [comment]
It's able to deal with it lacking (logout works fine), the issue is that if the `post_logout_redirect_uri` points to somewhere that the browser already has cached, then no request is made, so this library cannot redirect the logged-out user back to the login page.

If I added a state parameter statically to the configuration, I would end up with the same problem: no request from the browser, no redirect to login page.

**Comment by zandbelt** [comment]
I see: I'd still argue it is better to ask Hydra to add a `Cache-Control: no-cache, no-store, max-age=0` header returned from their logout endpoint to prevent this problem at the root. `lua-resty-openidc` had to do the same to its logout URL https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1226

**Comment by fenech** [comment]
OK, I added those headers and it works without any modification to this library.

I will close this issue and the corresponding pull request. Thanks for your input!
