### ISSUE TITLE
Opinion on nginx configuration

### ISSUE THREAD

**Issue by madtofan** [zmartzone/lua-resty-openidc#288]
###### Environment

- lua-resty-openidc version ( 1.7.2)
- OpenID Connect provider (Keycloak version 6.0.0)

###### Expected behaviour

React JS redirect to Keycloak Login page base on the lua-resty-openidc response

###### Actual behaviour

React JS not redirected to Keycloak Login page base on the lua-resty-openidc response

###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*

###### Configuration and NGINX server log files

server {
       listen     80;
       server_name  localhost;
       root     html;
       access_by_lua '
         local opts = {
           redirect_uri_path = "/redirect_uri",
           accept_none_alg = true,
           discovery = "http://localhost:8080/auth/realms/realm1/.well-known/openid-configuration",
           client_id = "login",
           client_secret = "b12345a1-f0d1-4e56-789a-db9d9e2eaad6",
           redirect_uri_scheme = "http",
           logout_path = "/logout",
           redirect_after_logout_uri = "http://localhost:8080/auth/realms/realm1/protocol/openid-connect/logout?redirect_uri=http://localhost:3000/",
           redirect_after_logout_with_id_token_hint = false,
           session_contents = {access_token=true}
         }
         local res, err = require("resty.openidc").authenticate(opts)
         if err then
           ngx.status = 403
           ngx.say(err)
           ngx.exit(ngx.HTTP_FORBIDDEN)
         end
         local inspect = require("resty.inspect")

      ';
      # I disabled caching so the browser won't cache the site.
      #expires           0;
      #add_header        Cache-Control private;
      location / {
        proxy_pass http://localhost:3000/;
      }
    }

**Comment by bodewig** [comment]
I'm afraid this is not the best place to ask for opinions on individual configurations. If you've got a concrete question about lua-resty-openidc, then please open a new issue.
