### ISSUE TITLE
Token Exchange support for SSO use case

### ISSUE THREAD

**Issue by pamiel** [zmartzone/lua-resty-openidc#289]
Hello,

The usual deployments of `lua-resty-openidc` I did are to protect my Web UI app thanks to authentication of users stored in a “local” Identity Provider (and this works like a charm!). The Identity Provider (namely KeyCloak) is deployed “close” to the `lua-resty-openidc`’s nginx, and is directly accessible from `lua-resty-openidc` for the Token retrieval at the end of the Authorization code flow (back-end to back-end communication).

However, I’m now requested by a customer to not use my own Identity Provider to perform the authentication, but rather to use my customer’s Identity Provider instead (a classical SSO use case, indeed!). Life would have been very simple if I could just configure `lua-resty-openidc` to target my customer’s Identity Provider :P, but the additional constraint I have is that I’m *not* able to have the famous “back-end to back-end” communication to get the Token at the end of the Authorization code flow :( : no way to contact the IdP like this (flow not allowed by my customer).

So, digging into OAuth and KeyCloak documentation, I found the “Token Exchange” use case that could be a good solution for me, and I’m questioning myself whether this could be an interesting feature to support in `lua-resty-openidc` (and I would be very happy to provide a PR for that as soon as you give me a “go” and we agree on how to do it).

So this post is really to share my proposal with you and to get challenged by you!

The assumption I have, as I cannot run a classical Authorization code flow, is that the authentication has been previously performed on my customer’s Identity Provider. Then, after browsing on my customer’s Web portal, the end-user will click on a link that will give him access to my Web UI.
- For this first request, as for the OIDC Authorization code flow, there is no session available in `lua-resty-openidc`. But contrary to OIDC Authorization code flow, a Token generated by the “external IdP” (i.e. my customer’s IdP) would be present in a specific HTTP header, as a proof of the previous authentication. It might be in the standard “Authorization” header.
- As this header is present, and as `lua-resty-openidc` would have been configured to run the Token Exchange flow and not the OIDC Authorization code flow, `lua-resty-openidc` would not perform any redirect but would rather directly call the Token endpoint of the local IdP (i.e. my KeyCloak), using the Token Exchange grant type and providing the received Token.
- The local Idp (i.e. my KeyCloak), being configured with the right external IdP knowledge (most probably a public key of the external IdP), could verify the validity of the provided Token, and then “exchange” it with a locally generated Token corresponding to a local User, with local roles inside.
- This local Token (indeed an Access Token and a Refresh Token) would then be managed by `lua-resty-openidc` the same way it is for the OIDC Authorization code flow: a session is created and filled with the Tokens, and the request is proxied up to the back-end UI server. When a later request is made and intercepted by `lua-resty-openidc`: whatever the request contains an Authorisation header, a valid session will be found in `lua-resty-openidc` so the request will be proxied.
- In case the Access Token stored in the session has expired, then a regular Token Refresh request will be done by `lua-resty-openidc` to the local IdP (as it is done today).

Sorry, a bit difficult to explain without being altogether around a white board ;), but I hope it was clear !

Is the Token exchange the right path to follow to address my SSO use case (I mean, with the specific constraints I have) ?
If so, what do you think about my proposal to integrate the Token Exchange support in `lua-resty-openidc` ?

If login looks properly managed, I’m less comfortable with logout…

Thanks in advance for your feedbacks.

Best regards,
Patrice

**Comment by zandbelt** [comment]
Token Exchange was not designed to solve the problem that you describe. In fact you're looking at a standard SSO use case that should have a "front channel only" binding, (where the SSO token is sent via the browser only) instead of a flow that requires a backchannel call to retrieve the token. The Implicit grant type was designed to cater for that scenario (amongst others). See https://openid.net/specs/openid-connect-implicit-1_0.html

So a possible approach would be to extend lua-resty-openidc to implement the Implicit profile.

But, a caveat: Implicit is inherently more insecure that the Authorization Code grant type and recent security best practises advise against it. I would still rather pressure the IDP to support the regular grant type as they should also be interested in the increased security that it brings along.

**Comment by pamiel** [comment]
Thanks @zandbelt for your answer.

We share the same concern related to security regarding the Implicit flow, and that's the reason why we are using the Authorization code flow for our regular authentication use cases... that would be a pity for us to come back on that.

Can you just clarify what is then the main usage of the Token Exchange, up to you?

**Comment by zandbelt** [comment]
The Identity Provider should make up its mind: by trying to be more secure (and not allowing backchannel calls) it will end up in a worse place, making Clients use less secure grant types.

The main usage of Token Exchange is to convert tokens between security domains, it is not about avoiding an awkward binding, it is not about the transport of those tokens.
