### ISSUE TITLE
Lost access token:token expired error

### ISSUE THREAD

**Issue by vavra5** [zmartzone/lua-resty-openidc#290]
###### Environment

- lua-resty-openidc version 1.7.2
- OpenID Connect provider Okta
- OpenResty docker container

###### Expected behavior

Access token is discarded or the session continues with no access token. User can navigate to web page as "anonymous".   I'm not sure I have the correct configuration to handle this scenario.

1. Require a valid access token for "/" location
2. User has/gets valid access token
3. Deploy OpenResty deployment where "/" is not protected anymore.
4. User's access token has expired and they access "/"
5. User's access token is set to nil

###### Actual behavior
Receive a 500 internal server error.

![500](https://user-images.githubusercontent.com/1078886/68133964-5e0c1600-feef-11e9-9d0b-debf4d6cce60.PNG)

###### Minimized example
I create a custom OpenResty docker image that adds my nginx.conf and lua-resty-openidc.conf. I'm using docker-compose to start the environment.

Steps to reproduce:
1. In Chrome navigate to http://localhost
2. http://localhost is redirected to https://dev-######.okta.com/login/login.htm?......
3. Login with credentials
4. Redirected back to http://localhost
5. Valid tokens exist
6. Wait 5 minutes for access token to expire
6. Refresh page (http://localhost)
7. Error on page reads "Internal Server Error"

###### Configuration and NGINX server log files

[500-error.txt](https://github.com/zmartzone/lua-resty-openidc/files/3809267/500-error.txt)

**lua-resty-openidc.conf:** 

    lua_package_path '/usr/local/openresty/lualib/resty/?.lua;;';

    lua_package_cpath '/usr/local/openresty/lualib/resty/?.so;;';

    lua_shared_dict discovery 1m;
    lua_shared_dict jwks 1m;
    lua_ssl_verify_depth 5;
    lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    resolver 127.0.0.11 8.8.8.8 ipv6=off;
    
    server {
        access_log /usr/local/openresty/nginx/logs/access.log main;

        error_log /usr/local/openresty/nginx/logs/error.log debug;

        server_name  localhost;

        listen 80 default_server;
        set $session_secret             ${SESSION_SECRET};
        location / {

            access_by_lua_block {
                local opts = {
                    redirect_uri = "/redirect_uri",
                    discovery = "${DISCOVERY_URL}",
                    client_id = "${CLIENT_ID}",
                    client_secret = "${CLIENT_SECRET}",
                    redirect_uri_scheme = "http",
                    logout_path = "/logout",
                    post_logout_redirect_uri = "http://localhost/",
                    redirect_after_logout_with_id_token_hint = true,
                    renew_access_token_on_expiry = false,
                    ssl_verify = "yes",
                    accept_unsupported_alg = false,
                    token_signing_alg_values_expected = { "RS256" },
                    access_token_expires_leeway = 30,
                    revoke_tokens_on_logout = true,
                    token_endpoint_auth_method = "client_secret_basic"
                }

                local res, err = require("resty.openidc").authenticate(opts, nil, "pass")
                if err then
                    ngx.status = 403
                    ngx.say(err)
                    ngx.exit(ngx.HTTP_FORBIDDEN)
                end
            }

            expires           0;
            add_header        Cache-Control private;
            proxy_pass  http://hello;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
    }

**nginx.conf**

    worker_processes  1;

    error_log /usr/local/openresty/nginx/logs/error.log debug;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $bytes_sent '
                        '"$http_referer" "$http_user_agent"';

        access_log /usr/local/openresty/nginx/logs/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        include /etc/nginx/conf.d/lua-resty-openidc.conf;
    }

**Dockerfile**

	FROM openresty/openresty:1.15.8.2-4-alpine-fat

	# Install ca-certificates
	RUN apk update && apk add --no-cache curl perl ca-certificates && rm -rf /var/cache/apk/*

	RUN update-ca-certificates -f -v

	# install dependencies
	RUN ["opm", "get", "zmartzone/lua-resty-openidc=1.7.2"]

	# nginx main config
	ADD nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

	# nginx primary vhost
	ADD lua-resty-openidc.template /etc/nginx/conf.d/lua-resty-openidc.template

	# template configuration
	CMD ["/bin/bash","-c","envsubst \"`for v in $(compgen -v);do printf '${%s} ' $v;done`'\" < /etc/nginx/conf.d/lua-resty-openidc.template > /etc/nginx/conf.d/lua-resty-openidc.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"]

	EXPOSE 80 443

	STOPSIGNAL SIGQUIT

**docker-compose.yml**

	version: '3'
	services:
	  openidc:
		build:
		  context: ./
		  dockerfile: Dockerfile
		image: openidc:local
		container_name: openidc
		restart: on-failure
		environment:
		  CLIENT_ID: removed
		  CLIENT_SECRET: removed
		  DISCOVERY_URL: removed
                  SESSION_SECRET: removed
		ports:
		- "80:80"
		expose:
		- 80
		links:
		- hello
	  hello:
		image: nginxdemos/hello:latest
		container_name: hello
		restart: on-failure
		ports:
		- "8400:80"
		expose:
		- 8400

**Comment by bodewig** [comment]
Your server logs says, this is the error causing the 500

```
2019/11/01 18:46:56 [error] 9#9: *1720 lua entry thread aborted: runtime error: access_by_lua(frontend.conf:298):34: attempt to concatenate field 'access_token' (a nil value)
stack traceback:
coroutine 0:
access_by_lua(frontend.conf:298): in main chunk, client: x.x.x.x, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2019/11/01 18
```

There seems to be a log statement or something like this in whatever `frontend.conf` is that does something like `'log the access_token' .. access_token`. In Lua trying to concatenate a string and a `nil` value yields an error.

**Comment by matth-c3** [comment]
Hello @vavra5 , 

did you manage to make it work with OKTA ? 

Each time  `local res, err require("resty.openidc").authenticate(opts)`  returns `nil`. Spent 2 days on that ... just wondering if I should not just stick to nodejs to handle that as the documentation is not really clear, especially the example.

THanks
