### ISSUE TITLE
Code Challenge formats cannot be passed in for Proof Key for Code Exchange (PKCE) authentication flow

### ISSUE THREAD

**Issue by frankcash** [zmartzone/lua-resty-openidc#291]
###### Environment

- lua-resty-openidc version: 1.7.2
- OpenID Connect provider: okta

###### Expected behaviour

When passing in `opts` adding `code_challenge` and `code_challenge_method` should be applied to the URI in the `openidc_combine_uri` step.

###### Actual behaviour

Passing in these values does not impact the URI

###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*

```lua
		access_by_lua_block{
			local opts = {
				redirect_uri = 'os.getenv("SERVERNAME")',
				client_id = os.getenv('CLIENT_ID'),
				discovery = os.getenv('DISCOVERY_ENDPOINT'),
				scope = 'openid email profile',
				session_contents = {id_token=true},
				ssl_verify = 'no',
				code_challenge_method = <method as string>,
				code_challenge = <challenge as string>
			}
			local res, err = require("open_idc").authenticate(opts)
			ngx.req.set_header("Authorization", res.access_token)
		}
```

###### Configuration and NGINX server log files
*Config and logs for the minimized example, possibly provided as attachments.*

`server: localhost:3000, request: "GET /callback_route?state=c371ddac350688dfb17001cfbbb80b98&error=invalid_request&error_description=PKCE+code+challenge+is+required+when+the+token+endpoint+authentication+method+is+%27NONE%27`

**Comment by bodewig** [comment]
this should be

```
... opt = {
  ...
  authorization_params = {
	code_challenge_method = <method as string>,
	code_challenge = <challenge as string>
  }
  ...
}
```

**Comment by frankcash** [comment]
Thanks, this wasn't clear to me.
