### ISSUE TITLE
Failed to protect two servers with two keycloak realms

### ISSUE THREAD

**Issue by yy8402** [zmartzone/lua-resty-openidc#293]
###### Environment
I have the following settings:
1. With Nginx, Server1 on port 443 and Server 2 on port 8843
2. With Keycloak, Client1/User 1 on Realm1 and Client2/User2 on Realm2
3. Server1 is set to be authenticated with Realm1 Client1, Server2 with Realm2 Client2

- the latest openresty/openresty:alpine-fat docker image
- lua-resty-openidc version: 1.7.2
- OpenID Connect provider: Keycloak 7.0.1

###### Expected behaviour
When a user is successfully authenticated to access Server1 with User1, she will be asked to re-login to Realm2 when trying to access Server2. As User1 is not a user in Realm2, if the user do not know username/password of User2, she will not be able to access Server2.
###### Actual behaviour
When a user is successfully authenticated to access Server1 with User1, she can access Server2 directly, not being requested to login to Realm2.

##### nginx.conf #####

events { worker_connections 1024; }

http {
    sendfile on;

    server {
        listen 443 ssl;

        ssl_certificate      /etc/x509/https/tls.crt;
        ssl_certificate_key  /etc/x509/https/tls.key;

        location / {
            proxy_pass http://mysite1/;
        }

        access_by_lua '
        local opts = {
            redirect_uri_path = "/redirect_uri",
            accept_none_alg = true,
            discovery = "https://KEYCLOAK_ADDR/auth/realms/realm1/.well-known/openid-configuration",
            client_id = "client1",
            client_secret = "bfd33e83-a924-445a-84b5-4de7e402abfe",
            logout_path = "/logout",
            redirect_after_logout_uri = "https://10.10.37.21:8443/auth/realms/supraccess/protocol/openid-connect/logout?redirect_uri=https://myserver/logout",
            redirect_after_logout_with_id_token_hint = false,
            session_contents = {id_token=true},
            ssl_verify = "no"
          }
         -- call introspect for OAuth 2.0 Bearer Access Token validation
         local res, err = require("resty.openidc").authenticate(opts)
         if err then
           ngx.status = 403
           ngx.say(err)
           ngx.exit(ngx.HTTP_FORBIDDEN)
         end
        ';
    }
    
    server {
        listen 8843 ssl;

        ssl_certificate      /etc/x509/https/tls.crt;
        ssl_certificate_key  /etc/x509/https/tls.key;

        location / {
            proxy_pass http://mysite2/;
        }

        access_by_lua '
        local opts = {
            redirect_uri_path = "/redirect_uri",
            accept_none_alg = true,
            discovery = "https://KEYCLOAK_ADDR/auth/realms/realm2/.well-known/openid-configuration",
            client_id = "client2",
            client_secret = "189c23e0-8562-4efb-8a58-2274f4cfde18",
            logout_path = "/logout",
            redirect_after_logout_uri = "https://KEYCLOAK_ADDR/auth/realms/supradmin/protocol/openid-connect/logout?redirect_uri=https://myserver/logout",
            redirect_after_logout_with_id_token_hint = false,
            session_contents = {id_token=true},
            ssl_verify = "no"
          }
         -- call introspect for OAuth 2.0 Bearer Access Token validation
         local res, err = require("resty.openidc").authenticate(opts)
         if err then
           ngx.status = 403
           ngx.say(err)
           ngx.exit(ngx.HTTP_FORBIDDEN)
         end
        ';
    }

}

**Comment by bodewig** [comment]
Is it possible the two servers are sharing the same Cookie domain and thus share a session?

You can easily test this by setting

```
        set $session_name session;
```

to different values inside of the two server blocks.

**Comment by yy8402** [comment]
Thank you very much for the information, Stefan! I have moved to another project and will check your solution later.

**Comment by bodewig** [comment]
any news?
