### ISSUE TITLE
Behaviour of openidc.jwt_verify() with a symmetric signing algorithm

### ISSUE THREAD

**Issue by bruceesmith** [zmartzone/lua-resty-openidc#294]
###### Environment

- lua-resty-openidc version 1.7.2)
- OpenID Connect provider Keycloak
- Access tokens are signed by RS256, a symmetric algorithm. Client in my case is using token_endpoint_auth_method=client_secret_basic with a client_id and a client_secret, however I suspect this problematic behaviour also applies to "client_secret_post" and "client_secret_jwt"

###### Expected behaviour

openidc.jwt_verify() should handle fallback for symmetric algorithms like it does for asymmetric algorithms

###### Actual behaviour

openidc.jwt_verify() calls openidc_load_jwt_and_verify_crypto(). When openidc_load_jwt_and_verify_crypto() detects an asymmetric algorithm but no certificate (i.e. no opts.secret or opts.opts.public_key), it tries to use discovery to obtain the jwks_uri endpoint, and then obtain the signing certificate from that endpoint. However when the signing algorithm is symmetric, no such fallback occurs.

**Comment by zandbelt** [comment]
well, there's a difference between the two: a symmetric key is a shared secret that should not be published so these keys are not available from a jwks_uri because it would violate the principle of a secret that is shared between two parties...
