### ISSUE TITLE
ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt)

### ISSUE THREAD

**Issue by chenglei12345** [zmartzone/lua-resty-openidc#297]
my teammate used docker run a project before, and it did good.
these days i tried to transfer it to kubenerts.

my Dockerfile 
RUN wget -O lua-resty-session.tar.gz 'https://github.com/bungle/lua-resty-session/archive/v2.3.tar.gz' \
    && cat lua-resty-session.tar.gz | tar -zxf - -C /opt/ \
    && cp -r /opt/lua-resty-session-2.3/lib/* /usr/local/openresty/lualib/ \
    && rm lua-resty-session.tar.gz && rm -rf /opt/lua-resty-session-2.3 \
    \
	&& wget -O lua-resty-http.tar.gz 'https://github.com/pintsized/lua-resty-http/archive/v0.07.tar.gz' \
	&& cat lua-resty-http.tar.gz | tar -zxf - -C /opt/ \
	&& cp -r /opt/lua-resty-http-0.07/lib/* /usr/local/openresty/lualib/ \
	&& rm lua-resty-http.tar.gz && rm -rf /opt/lua-resty-http-0.07 \
	\
	&& wget -O lua-resty-openidc.tar.gz 'https://github.com/pingidentity/lua-resty-openidc/archive/v1.0.tar.gz' \
	&& cat lua-resty-openidc.tar.gz | tar -zxf - -C /opt/ \
	&& cp -r /opt/lua-resty-openidc-1.0/lib/* /usr/local/openresty/lualib/ \
	&& rm lua-resty-openidc.tar.gz && rm -rf /opt/lua-resty-openidc-1.0/ \
	\

my nginx.conf 
lua_package_path '~/lua/?.lua;;';
lua_shared_dict discovery 1m;
resolver 119.29.29.29;
lua_ssl_trusted_certificate /etc/pki/tls/cert.pem;
lua_ssl_verify_depth 5;

my lua config
local opts = {
        redirect_uri_path = "",
        discovery = "",
        client_id = "",
        client_secret = "",
        scope = "openid",
        iat_slack = 600,
        --ssl_verify = "no",
        response_mode = "form_post"
    }

    -- call authenticate for OpenID Connect user authentication
    local res, err = require("resty.openidc").authenticate(opts)

    if err then
        ngx.status = 500
        ngx.say(err)
        ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
    end

when i run the job ,error comes 
ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt), client: , server: , request: "GET / HTTP/1.1", host: ""

2019/12/13 07:50:00 [error] 6#0: *4 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/openidc.lua:245: attempt to concatenate field 'state' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/openresty/lualib/resty/openidc.lua: in function 'authenticate'

can anybody help? thanks

**Comment by gabrieldesar** [comment]
Same problem here, it was working but started to happen this week

**Comment by chenglei12345** [comment]
https://github.com/bungle/lua-resty-session/issues/23 
it helped me , you can try.
I just add 'set $session_secret 623q4hR325t36VsCD3g567922IC0073T ' on my nginx.conf ,then the problem gone.


> Same problem here, it was working but started to happen this week

**Comment by jianzhiyao** [comment]
My problem is the same after adding 'set $session_secret 623q4hR325t36VsCD3g567922IC0073T '
