### ISSUE TITLE
Create session for already logged user in keycloak, but not redirect to keycloak login page

### ISSUE THREAD

**Issue by robertza93** [zmartzone/lua-resty-openidc#298]
Hi,
I'm using lua-resty-openidc. I am facing a problem where I have logged in to keycloak from another application, but not through lua-resty-openidc. Is it possible to create a session in lua if I am already logged in to keycloak, but without being redirected to the keycloak login page, but if I am not logged in to keycloak, then will I be redirected to the keycloak login page?

**Comment by bodewig** [comment]
In a situation like this keycloak will usually directly redirect the user back to lua-resty-openidc without ever showing a login screen - this is assuming the user doesn't need to consent to anything.

If this is not good enough then you need to somehow know the user is already logged in (I have no idea how you'd do that) and then completely skip lua-resty-openidc.
