### ISSUE TITLE
Client credentials grant_type

### ISSUE THREAD

**Issue by affanshahid** [zmartzone/lua-resty-openidc#299]
###### Environment

- lua-resty-openidc version 1.6.1-1
- OpenID Connect provider Keycloak

Not at all familiar with OIDC so this might be a dumb question. I am trying to use this lib inside of a middleware layer between our backend and frontend.

 I want to call the `authenticate()` function and use `grant_type: client_credentials` for it to generate a token for some requests to keycloak. Introspect etc works fine however when I call `authenticate()` it redirects me due to it using `grant_type: authorization_code`, is it possible for me to use other grant_types?

**Comment by ahmednawazkhan** [comment]
No one will reply good questions

**Comment by bodewig** [comment]
`authenticate` implements the OpenID Connect Authorization Code Grant Flow, it is not meant to be used for the Client Credentials Grant Flow (which doesn't even exist for OpenID Connect)

Currently there is no way to use the Client Credentials Grant Flow with lua-resty-openidc and it may just be out of scope for the project.

**Comment by okazakikirito** [comment]
local opts = {
          discovery = env_discovery_url,
          authorization_params = { kc_idp_hint=ngx.var.arg_idpHint },
          redirect_uri_scheme = "http",
          redirect_after_logout_with_id_token_hint = false,
          accept_unsupported_alg = false,
          scope = "openid microprofile-jwt",
  }
  local body = {
        grant_type = 'client_credentials',
        audience = "<your-audince-name>",
  }
  local discovery, err
  discovery,err = get_endpoint(opts.discovery,opts)
 if not err then 
   opts.discovery=discovery
 end

    if opts.client_id == '<Clinet that want to use the CC flow
    >' then
      local endpoint = opts.discovery.token_endpoint
      local httpc = http.new()
      local res, err = httpc:request_uri(endpoint,{
        method = "POST",
        body = ngx.encode_args(body),
        headers = {
          ["Content-Type"] = "application/x-www-form-urlencoded",
          ["Authorization"] = basic_auth
        },
        ssl_verify = (opts.ssl_verify ~= "no")
      })
      if (err or not res) then
        err = "accessing " .. ep_name .. " endpoint (" .. endpoint .. ") failed: " .. err
        log(ERROR, err)
        ngx.status = 401
        ngx.header["WWW-Authenticate"] = get_challenge(env_client_id)
        ngx.exit(ngx.HTTP_UNAUTHORIZED)
      end
      -- log(INFO,"THE RESPONSE FROM CLINET CRED IS " .. inspect(res))
     json,err= openidc_parse_json_response(res, ignore_body_on_success)


you can use something like this by using most of the existing functions in the Authorization header pass in the base64 encoded clientid and secret in the json response you'll have your token

**Comment by morvencao** [comment]
+1 to support `grant_type: client_credentials`

**Comment by zandbelt** [comment]
I consider this out of scope for this project, apart from struggling to understand what would be achieved with this. However, it should not be too hard to use the code above in its own project.
