### ISSUE TITLE
Different Sessions for Different Clients

### ISSUE THREAD

**Issue by okazakikirito** [zmartzone/lua-resty-openidc#300]
Hi I have come up with an issue where I'm using normal authorization code flow to login to the application and within that application I'm trying to reach another endpoint which is registered with different client but when I try to reach that endpoint I'll be given an access token that is in session for the first client which is not desirable is there a solution for this ?  or am I doing something wrong ?

**Comment by bodewig** [comment]
Are you using the Cookie Session Store? If so you may want to use different names for the session cookies (`$session_name`) or explicitly set the cookie path (`$session_cookie_path`) for each endpoint, see https://github.com/bungle/lua-resty-session#nginx-configuration-variables.

**Comment by okazakikirito** [comment]
I have tried out setting a different session name by passing in session options as
`session_opts ={name = second_session}` but when I use a different name session wouldn't get created :(
so I tried using the path as you have suggested 
`     local session_opts = {
          cookie = {
            path = "/offline"
          }
        }`
This didn't cause any issue like not generating a session but the earlier problem was still there

**Comment by bodewig** [comment]
Maybe we need to take a step back.

You've got two "endpoints" and those two are both hosted on the same nginx instance, they are both protected by lua-resty-openidc right? Can you share a bit of your config file so we can see actual URL paths, how they relate to each other and how you configure lua-resty-openidc in the two cases (not including any sensitive information, of course)?

**Comment by okazakikirito** [comment]
location = /redirect {
        access_by_lua_block {
            require("access").process_authentication()
        }
    }
    location /main/ {
        access_by_lua_block {
            require("access").process_authentication()
        }
        proxy_pass http://web:8080/main/applications/web/server/metadata/;
    }


    location /TokenValidator/ {
        access_by_lua_block {
            require("access").process_offline_token()
        }
        proxy_http_version 1.1;
        proxy_pass
http://jwt-validator:8080/TokenValidater/secured/Validated.jsp;
    }

   location /TokenValidater/redirect {
        access_by_lua_block {
            require("access").process_offline_token()
        }
    }





There are some more configs but these are the main paths that I'm trying to
access after some more playing around I was able to set a name and a path
for the session but when I try to reach the second path I get this error,
it seems like session created for /TokenValidator path is not working
correctly.

You are already authenticated as different user 'testuser' in this session.
Please log out first.


Thank you,
Best Regards,
Kirito.

**Comment by bodewig** [comment]
Unfortunately I cannot see how you use lua-resty-openidc here.

When using two different client-ids you will probably need two different redirect_urls and their session cookie definitions must be the same as for the corresponding locations they belong to.

**Comment by okazakikirito** [comment]
Ahh sorry about that in the process_authenticate and process_offline_token we call the openic.authenticate() 

yes I have different re-direct urls for those clients isn't having different session names enough do I also need to set the path ?

**Comment by bodewig** [comment]
What I was interested in was the options that affect sessions you pass to `authenticate`.

Whether you need different redirect URIs for your different clients depends on how you tell your different clients apart.

When you call `openidc.authenticate` while the redirect URI is navigated you tell it which cookie and which client_id to use. If you can do this in your Lua code before invoking `authenticate` than a single redirect URI will be enough (provided the Cookie paths include the redirect URIs in both cases).

**Comment by okazakikirito** [comment]
local opts = {
            redirect_uri = redirect_url,
            discovery = env_discovery_url,
            authorization_params = { kc_idp_hint=ngx.var.arg_idpHint },
            client_id = env_client_id,
            client_secret = os.getenv("CLIENT_SECRET"), 
            redirect_uri_scheme = "http",
            logout_path = get_logout_uri(),
            post_logout_redirect_uri = get_logout_redirect_uri(),
            redirect_after_logout_with_id_token_hint = false,
            session_contents = {id_token = true, access_token = true},
            scope = "openid"
        }
        session_opts ={
          name = second_session
        }
        res, err, target_url, session = openidc.authenticate(opts, nil, "pass",session_opts)

I tried passing the Cookie Paths but there are too many paths to add if I'm not going to use only the `root path` isn't only setting different name enough

**Comment by bodewig** [comment]
Ypu can only set one `Path` on a cookie anyway, so if your different apps can not be segregated by path, setting the path is no option.

Yes, different names should be enough. In that case you must ensure the call to `authenticate` is configured with the correct name when `redirect_uri` is invoked.
