### ISSUE TITLE
Configuring session storage with redis

### ISSUE THREAD

**Issue by bpauwels** [zmartzone/lua-resty-openidc#302]
I'm running nginx with resty-openidc on an OpenShift Cluster and would like to use redis for session storage. I have tried something like this but it seems that resty-session is ignoring the options:

access_by_lua '
         local opts = {
           redirect_uri = "...",        
           accept_none_alg = true,
           discovery = "...",
           client_id = "...",
           client_secret = "...",
           redirect_uri_scheme = "http",
           logout_path = "/logout",
           redirect_after_logout_uri = "...",
           redirect_after_logout_with_id_token_hint = false,
           session_contents = {id_token=true}
         }
         local session_opts = {
            storage = "redis",
            redis_prefix = "nginx",
            redis_host = "redis.in.my.cluster.svc",
            redis_port = 6379,
            redis_uselocking = "on",
            redis_spinlockwait = 10000,
            redis_maxlockwait = 30,
            redis_pool_timeout = 45,
            redis_pool_size = 10
         }
         local res, err = require("resty.openidc").authenticate(opts,nil,nil,session_opts)
         if err then
           ngx.status = 403
           ngx.say(err)
           ngx.exit(ngx.HTTP_FORBIDDEN)
         end
        -- Set Headers
        ngx.req.set_header("REMOTE_USER", res.id_token.email)
            
      ';

The session is still stored in a cookie. No nginx* keys redis...

Has anyone done this before?

**Comment by bodewig** [comment]
I am using the redis session store but am using static nginx configuration via `set $session_redis_prefix        sessions;` and so on. I'm not sure whether you can use session opts for the details of the storage adapter, https://github.com/bungle/lua-resty-session doesn't seem to be clear about it.

**Comment by bpauwels** [comment]
`set $session_storage redis;
set $session_redis_prefix        nginx;
set $session_redis_host          redis.in.my.cluster.svc;
set $session_redis_port          6379;
set $session_redis_uselocking    on;
set $session_redis_spinlockwait  10000;
set $session_redis_maxlockwait   30;
set $session_redis_pool_timeout  45;
set $session_redis_pool_size     10;`

Sadly this has no effect... 

But  `set $session_name              sess_auth;` works just fine.

**Comment by bodewig** [comment]
Works for me inside of `server`. If it doesn't work for you you may need to ask over at lua-resty-session instead.

**Comment by bpauwels** [comment]
Thanks, I will ask over there!
