### ISSUE TITLE
Regex not properly escaped

### ISSUE THREAD

**Issue by henrykuijpers** [zmartzone/lua-resty-openidc#303]
https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L928

This allows not just the character `.`, but in fact *any* character.

**Comment by bodewig** [comment]
This is a Lua Pattern http://www.lua.org/manual/5.3/manual.html#6.4.1 and not a regex. `%.` matches a dot and not any character. Which of the several dots do you think needs to be escaped but isn't?

**Comment by bodewig** [comment]
@henrykuijpers ping?

**Comment by henrykuijpers** [comment]
I'm sorry. Very busy. This is indeed not an issue then.

**Comment by bodewig** [comment]
Thank you.
