### ISSUE TITLE
Auth redirect not working with Ajax call (CORS header not correct in preflight request)

### ISSUE THREAD

**Issue by freegroup** [zmartzone/lua-resty-openidc#304]
The normal OpenID-Connect flow works perfectly in my app. But after a minute (depends on my settings) it is not possible to make Ajax calls to my backend. I get a 302 (redirect) response, which is totally ok,  to the auth server. But the auth server rejects this redirect because of CORS policy. 

Is there any way to set the response header in the case of an auth-redirect? My configuration didn'T work.

###### Environment

- lua-resty-openidc version  1.7.2
- OpenID Connect provider , SAP Identity Provider

###### Expected behaviour
Ajax call is possible even after 302 redirect.

###### Actual behaviour
didn'T work because of CORS policy.

*Access to XMLHttpRequest at 'https://###################/oauth2/authorize?response_type=code&client_id=T000019&state=62fd6754d081e70935de2718adc25b54&redirect_uri=https%3A%2F%2Fwww.anybackend.com%2Foauth2%2Fcallback&prompt=none&nonce=31b75eaa829ece370e2ce25982f48fd7&scope=openid' (redirected from 'https://www.anybackend.com/api/v1/costcenter/220550810763084674600583470829320455985') from origin 'https://www.anybackend.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.*

###### Minimized example
``` 
    events {
      worker_connections 128;
    }
    error_log /dev/stdout debug;

    http {
      lua_package_path '~/lua/?.lua;;';
      resolver 100.64.0.10;
      # cache for JWT verification results
      lua_shared_dict introspection 10m;
      # cache for jwks metadata documents
      lua_shared_dict discovery 1m;
      server {
        listen 8080;

        # handle web socket connection in the correct way. Upgrade call of WS.
        location ^~ /socket.io {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Frame-Options SAMEORIGIN;
            proxy_pass http://ui.frontend.svc.cluster.local;
        }

        location / {

          access_by_lua '
            ngx.header["Access-Control-Allow-Origin"] = "*"
            ngx.header["Access-Control-Allow-Credentials"] = "true"

            local opts = {
              client_id = "#############",
              client_secret = "############",
              redirect_uri = "https://###########/oauth2/callback",
              discovery = "https://###########/.well-known/openid-configuration",
              scope = "openid",
              ssl_verify = "no",
              refresh_session_interval = 60,
              -- This is really, really important
              accept_none_alg = false,
              accept_unsupported_alg = false,
              renew_access_token_on_expiry = true,
              access_token_expires_in = 60,
              session_contents = {access_token=true, id_token=true},
            }

            -- call authenticate for OpenID Connect user authentication
            local res, err = require("resty.openidc").authenticate(opts)
            if err or not res then
              ngx.status = 403
              ngx.say("forbidden")
              ngx.exit(ngx.HTTP_FORBIDDEN)
            end

            -- Set valid access token and email as request header
            ngx.req.set_header("Authorization", "Bearer " .. res.access_token)
            ngx.req.set_header("X-Mail", res.id_token.mail)
            ngx.req.set_header("X-LastName", res.id_token.last_name)
            ngx.req.set_header("X-FirstName", res.id_token.first_name)
          ';
          proxy_pass http://ui.frontend.svc.cluster.local;
        }
      }
    }
``` 
###### Configuration and NGINX server log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by bodewig** [comment]
Your request going to the OpenID Connect provider **is** a cross origin request, so CORS comes into play no matter what. If you look through the CORS spec you'll see it is all about the browser and the server receiving the cross origin request, there isn't anything lua-resty-openidc as the party that issues the redirect to the OpenID Connect Provider can do.

**Comment by freegroup** [comment]
Hi,

thanks for the fast response.

on https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L314 is a redirect call in the OpenResty OIDC code. 

Below the call which is denied by the IDP

``` 
1.       Request URL: https://cpkernel.accounts400.ondemand.com/oauth2/authorize?response_type=code&client_id=T000019&state=89c0b9983ba75390f5e326faf8a439e9&redirect_uri=https%3A%2F%2Fcontrolling.klacksgroup.com%2Foauth2%2Fcallback&nonce=41b8c6670a97588b04edc3569f032326&scope=openid
2.       Request Method: OPTIONS
3.       Status Code: 403
4.       Remote Address: 155.56.128.152:443
5.       Referrer Policy: no-referrer-when-downgrade

Response Headersview source
1.       Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
2.       Cache-Control: private,no-cache,no-store
3.       Connection: Keep-Alive
4.       Content-Length: 20
5.       Content-Type: text/html;charset=utf-8
6.       Date: Tue, 28 Jan 2020 11:30:09 GMT
7.       Expires: 0
8.       Keep-Alive: timeout=5, max=100
9.       Pragma: no-cache
10.   Server: SAP
11.   Strict-Transport-Security: max-age=31536000;includeSubDomains;preload
12.   Vary: X-CSP-STRIP
13.   X-Content-Type-Options: nosniff
14.   X-IDS-ID: C8394A92-400E-464C-A6DE-1F9D9829B2A1
15.   X-IDS-Landscape: eu-de-1
16.   X-IDS-Node: idp03
17.   X-IDS-Pool: green
18.   X-IDS-Project: qa
19.   X-Robots-Tag: none
20.   X-XSS-Protection: 1; mode=block

Request Headersview source
1.       Accept: */*
2.       Accept-Encoding: gzip, deflate, br
3.       Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,it;q=0.6,fr;q=0.5
4.       Access-Control-Request-Headers: content-type
5.       Access-Control-Request-Method: PUT
6.       Connection: keep-alive
7.       Host: cpkernel.accounts400.ondemand.com
8.       Origin: https://controlling.klacksgroup.com
9.       Referer: https://controlling.klacksgroup.com/costcenter
10.   Sec-Fetch-Mode: cors
11.   Sec-Fetch-Site: cross-site
12.   User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

Query String Parametersview sourceview URL encoded
1.       response_type: code
2.       client_id: T000019
3.       state: 89c0b9983ba75390f5e326faf8a439e9
4.       redirect_uri: https://controlling.klacksgroup.com/oauth2/callback
5.       nonce: 41b8c6670a97588b04edc3569f032326
6.       scope: openid
```

the OpenId Provider told me that the "OPTION" call for the request isn't allowed. 

Is this true?

**Comment by bodewig** [comment]
The redirect call is telling your browser to go over to the OpenID Connect provider. It does not make lua-resty-openidc talk to the OIDC provider itself. Your browser then decides this is a CORS request (which is correct) and wants to make a CORS preflight OPTIONS request (which may not strictly be necessary for a GET request, this depends on circumstances).

Your OpenID Connect provider then says it does not want to support CORS here. It's the decision of the OpenID Connect provider.

**Comment by bodewig** [comment]
One more thing. `Access-Control-Request-Method: PUT` looks as if your browser want to make a PUT request which is wrong in either case. The whole OpenID Connect redirect dance will only work properly for GET requests.

**Comment by freegroup** [comment]
the problem is, that I have an XMLHttpRequest (Ajax) call with PUT as verb. Which seems to end as `Access-Control-Request-Method: PUT` on the IAS. 

Question: what is the best practice to handle `PUT` Ajax call with authentication and OpenId-Connect?

**Comment by bodewig** [comment]
This question is not really specific to lua-resty-openidc and I'm not sure I can talk about best practices with authority.

But before I send you working on something that is bound to fail: even if the request that triggers the redirect to the OpenID Connecr provider is a GET request, it will end up being a CORS request. If your OpenID Connect provider simply doesn't want to support CORS, then you are stuck.

Sometimes you may be able to put a reverse proxy in front of your OpenID Connect provider that handles CORS for you, but this really would be a hack more than a solution.

In an AJAX-heavy environment you may be better off with the implicit flow.

Finally with a bit of custom code around lua-resty-openidc you can try to ensure the redirect only happens on GET requests and simply deny all other methods if the token is expired. And then you'd have to handle the denied response in JavaScript by issuing a GET to refresh the token and then retry the other method. Without CORS support in your OpenID Connect provider there is no need to try this, though.

**Comment by freegroup** [comment]
thanks.

by the way - I have setup my scenario with Auth0 as Idp and it is working well. Maybe he accepts the CORS/PUT request. Thanks for your support. I try to refresh my session with a simple GET call.

**Comment by freegroup** [comment]
`Gitlab` and `Auth0` accepts the put call for the refresh/redirect calls.
However, it helps a frontend developer enormously to build a REST compliant web application...how else would it work.
