### ISSUE TITLE
Authorization Code - Chrome struck with code= and no further process of getting a token

### ISSUE THREAD

**Issue by satscreate** [zmartzone/lua-resty-openidc#310]
**Version:**

```
nginx -V
nginx version: openresty/1.15.8.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
```
**Problem:**
When i try to go to this url /login in browser , it redirect me to the right IDp server and after logging in it redirect me to this url: (which is my redirect URI)
`http://127.0.0.1:8082/?code=NhVcYjXHDNQ5vMKdjdjdhddAH&state=19c72ef154a745938a95ac6fa4a736363
`
But whats next process i dont see token generation being happening in server side (nginx-openresty). 
Do nginx should have listen the same and grab the code from the url and acquire the token on behalf???
 
**Server Block:**
```
server {
    set $api_name -; # Start with an undefined API name, each API will update this value
    access_log /var/log/nginx/api_access.log api_main; # Each API may also log to a separate file

    listen 443 ssl;
    server_name iam-work2.hpecorp.net;

      location /login {
			access_by_lua_block {
                        local opts = {
                                redirect_uri="http://127.0.0.1:8000/",
				--redirect_uri_path="/callback", --i dont have one 
                                discovery="https://sample.com/.well-known/openid-configuration",
                                client_id="sample",
                                --client_secret="sample",
                                scope="openid",
                                ssl_verify="no",
				--session_contents = {id_token=true}
                        }
                        local res, err =require("resty.openidc").authenticate(opts)
                        if err then
                                ngx.status = 500
                                ngx.say(err)
                                ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                        end
.......................................
                }
 }

    # TLS config
    ssl_certificate      /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key  /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_session_cache    shared:SSL:10m;
    ssl_session_timeout  5m;
    ssl_ciphers          HIGH:!aNULL:!MD5;
    ssl_protocols        TLSv1.1 TLSv1.2;



    location = /_NULL {
        internal;
        return 204;
    }

}
```
in my case both idp server token url IP and redirect_uri IP's are different.
What am i missing here to get an access & id token from IDp server from nginx itself? Please help

**Comment by bodewig** [comment]
Your redirect_uri is where your IdP sends you in order to perform the client side part of the authorization code grant flow. You don't show the location that would consume the redirect_uri - which should contain a lua-resty-openidc authenticate using the same configuration as well.

**Comment by satscreate** [comment]
> Your redirect_uri is where your IdP sends you in order to perform the client side part of the authorization code grant flow. You don't show the location that would consume the redirect_uri - which should contain a lua-resty-openidc authenticate using the same configuration as well.

Thanks @bodewig ,
Here is my setup look like right now,  added new uri into IdP server and that actually redirect back to nginx itself now am seeing accesstoken & id_token created followed by some errors.

```
location /callback {
			access_by_lua_block {
                        local opts = {
                                redirect_uri="http://<my_nginx_machine_ip>:8000/callback",
				discovery="https://sample.com/.well-known/openid-configuration",
                                client_id="sample",
                                scope="openid",
                                ssl_verify="no",
                        }
                        local res, err =require("resty.openidc").authenticate(opts)
                        if err then
                                ngx.status = 500
                                ngx.say(err)
                                ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                        end
.......................................
                }
 }
```
But my biggest question is this, am trying to make nginx itself to do the oidc with just getting authenticated from user and on behalf. in this case i always had to redirect user calls to /callback to make it work. so that actual oidc kicks in then again redirect back to /callback itself to do the further token generation & validation. Is this direction correct??

**Comment by bodewig** [comment]
I'm sorry, but I don't really understand what you are trying to do.

Lets say you only want to let authenticated users in then you'd create a `location` for `/` and add an `access_by_lua_block` calling `authenticate`. If your users is logged in this block should return `ngx.OK` (or nothing which has the same effect). If the user is not logged in the authorization code grant flow will be triggered.

The Redirect-URI is something that is internal to the flow. Your OpenID Connect Provider and luar-resty-openidc need to know it (and `authenticate` must be called for this URI) but this is not an URI your users would navigate directly. By default this is `/redirect_uri` and thus covered by your `/` location automatically. lua-resty-openidc will redirect your user back to the URI that was navigated before the flow started when it has obtained the tokens.

You may want to read up on the OpenID Connect Authorization Code Grant Flow.

**Comment by satscreate** [comment]
Many thanks @bodewig 
I understood now. right now am able to get it working by just placed authenticate under location /
With that callback url registered with Idp.

**Comment by bodewig** [comment]
Great. Does this also resolve #309 ?

**Comment by satscreate** [comment]
Hi @bodewig ,
Quick question, which is may be related to using this.
Right now am able to hit some /api/getsomthing url from browser and it redirects me to correct Idp and final requests been passed to actual api/getsomething.

It all works well in Browser. But how do i consume the same /api/getsomthing (which may be POST req) in client side like desktop client? do i need to especially configure javascript to emulate the same?

because the same /api/getsomthing am trying to consume via postman.
it results in below,

```
<html>

<head>
	<title>Submit Form</title>
</head>

<body onload="javascript:document.forms[0].submit()">
	<noscript>
		<p>
			<strong>Note:</strong> Since your browser does not support JavaScript, you must press the Resume button once
			to proceed.
		</p>
	</noscript>
	<form method="post" action="https://<idp_ip>/idp/singlesign.saml2">
		<input type="hidden" name="SAMLRequest" value="1sOklzc3Vlcj48c2FtbHA6TmFtZUlEUG9saWN5IEFsbG93Q3JlYXRlPSJ0cnVlIi8+PC9zYW1scDpBdXRoblJlcXVlc3Q+"/>
		<input type="hidden" name="RelayState" value="AmlJ57crfeprkgmermerpmcqAcOKHE"/>
		<noscript><input type="submit" value="Resume"/></noscript>
	</form>
</body>

</html>
```
The whole point of this module is to keep the auth flow inside nignx right including token generation and validation. if everything goes fine then redirect req to upstream.

**Comment by bodewig** [comment]
This really is a JavaScript question more than an OpenID Connect one.

Your JavaScript client must

* be willing to follow redirects
* be able to deal with CORS as the request becomes a CORS request when it gets redirected to the OpenID Connect provider
* must send Cookies - even with CORS calls - for the `fetch`-API this means the `include` `credentials` mode.

All this is assuming your browser has already authenticated and the OpenID Connect provider knows it so that you will not see a login page but rather get redirected back with an authorization code. POST is still likely to fail in such a case as the body will likely be lost on the redirects.

Putting this together your best bet is to obtain authentication via a "normal" web page and make the JavaScript request using the Cookie obtained before. An alternative is to not use the authorization code grant flow at all (but the implicit or hybrid flow via JavaScript) and a separate means of transmitting the token to the server - `Authorization` Header with bearer tokens for example.

More details are really beyond the scope of this issue-

**Comment by satscreate** [comment]
Thanks for the detailed explanation @bodewig .
The reason behind my question is that one of my client (desktop) actually does OIDC 
`(enable browser -> grab code & state from query string -> call token req endpoint -> get acc_token -> call api post) 
`
and send POST request to API and if we use and utilize this module in NGINX (as API_Gateway) then we could potentially remove auth layer from client is what i thought. But that's not the case isn't?

**Comment by bodewig** [comment]
In a scenario where your client already obtains a token by itself, you don't need to run the authorization code grant flow on the server, right. In that case you are better off with a bearer token and lua.resty-openidc can at least help you with verifying it is present and valid (see `introspect` and if your access token is a JWT even `bearer_jwt_verify`).

**Comment by satscreate** [comment]
> In a scenario where your client already obtains a token by itself, you don't need to run the authorization code grant flow on the server, right. In that case you are better off with a bearer token and lua.resty-openidc can at least help you with verifying it is present and valid (see `introspect` and if your access token is a JWT even `bearer_jwt_verify`).

Yes correct @bodewig that's what i tested already by just introspect the token in nginx and forward the request to API. That works like charm. 
This use case is something which is new for me by centralizing the whole auth into nginx so that the client can just talk to API calls via nginx and nginx can take care of the rest like oidc and add token into the request. 

So that's not something can be achievable using this module is it?  or 
Will this support only protected resources from WEB interface API only? not really any API calls (post or get)?

**Comment by bodewig** [comment]
At the heart of the Authorization Code Grant Flow is a redirect to the OpenID Connect provider which will eventually show HTML forms for login and maybe user consent. nginx can not do this all by its own, the user needs to provide credentials to the OP at one point.

Your desktop client could embed a web-view and invoke an HTML page from your nginx, make the user authenticate, grab the Cookie created by lua-resty-openidc and pass this along with every API request. The client need to be prepared to deal with expiring cookies or tokens, though.

**Comment by satscreate** [comment]
> At the heart of the Authorization Code Grant Flow is a redirect to the OpenID Connect provider which will eventually show HTML forms for login and maybe user consent. nginx can not do this all by its own, the user needs to provide credentials to the OP at one point.
> 
> Your desktop client could embed a web-view and invoke an HTML page from your nginx, make the user authenticate, grab the Cookie created by lua-resty-openidc and pass this along with every API request. The client need to be prepared to deal with expiring cookies or tokens, though.

Yes right @bodewig .
It seems i can simply get the validation done by accessing one page inside nginx and grab the cookie response and add to every subsequent calls so that things will be smooth except client has to deal with expiring cookies. Thanks.

So usually this modules help in accessing the protected web resources. Not a Web API calls. Am i right. Practically it can handle GET requests but not POST. because i have below html form




```
<html>

<head>
	<title>Submit Form</title>
</head>

<body onload="javascript:document.forms[0].submit()">
	<noscript>
		<p>
			<strong>Note:</strong> Since your browser does not support JavaScript, you must press the Resume button once
			to proceed.
		</p>
	</noscript>
	<form method="post" action="https://<nginx_ip>/postsomthing">
		<noscript><input type="submit" value="Resume"/></noscript>
	</form>
</body>

</html>
```
if i load this html in browser then it actually redirect things to authenticate against idp and redirect back to https://<nginx_ip>/postsomthing. Which is expected but what i get the result is that,

`405 Method not allowed.`

my location is like this,

```
location /postsomething {
    limit_except POST {
        deny all;
    }
    error_page 403 = @405; # Convert response from '403 (Forbidden)' to '405 (Method Not Allowed)'
    set $upstream my_api;
    rewrite ^ /_api last;
}
```
Why its converting POST into GET? Any idea?

**Comment by bodewig** [comment]
WebAPI Calls and Authorization Code Grant Flow on the site of the API-Host simply don't go well together.

And yes, lua-resty-openidc does not preserve the original HTTP method used nor the body of a request when it triggers the authorization code grant flow, so you should avoid making it trigger a new flow on POSTs (or PUTs or OPTIONS or ...).

It would be possible to store the body and re-issue POSTs with the help of server side storage and JavaScript but this is (currently?) not implemented.

**Comment by satscreate** [comment]
Thanks @bodewig .So i assume this whole module will help in just a finalized version of auth_code flow and forward the proxy pass which is configured and to protect some resources. which may be site or host.
**Final Assumptions:**

1. Not being very useful for API calls, - especially if any API operations outside browser this wont help anyway
2. Any other suggestions or modules to archive https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce to configure the step by step process so that client does not require all those things?
3. are you sure this cant be used for API calls?

**Comment by bodewig** [comment]
No, this is not what I tried to say.

I'll respond in #312 to your points 1 and 3 - and my answer is that for API calls it is a conceptional problem, not one of the implementation.

As for your second point, we currently do not support PKCE but probably should.
