### ISSUE TITLE
URL-Encoded secret/key in Authorisation header

### ISSUE THREAD

**Issue by freegroup** [zmartzone/lua-resty-openidc#314]
###### Environment

- Version 1.7.2
- OpenID Connect provider: All

###### Expected behaviour
The `Authorisation` header is set with base64(user+":"password) as described in https://tools.ietf.org/html/rfc7617

###### Actual behaviour

The `Authorisation` header is set with base64(url_encode(user)+":"url_encode(password)) which breaks passwords with special characters.
 
https://github.com/zmartzone/lua-resty-openidc/blob/v1.7.2/lib/resty/openidc.lua#L428

I think the OpenResty implementation breaks the standard in this case.

**Comment by zandbelt** [comment]
why does it "breaks passwords with special characters", as a matter of fact that is exactly why the encoding is done...

**Comment by freegroup** [comment]
base64 is good enough for the encoding. The https://tools.ietf.org/html/rfc7617 says nothing
about url_encoding....this is definitely not required

The used IDP didn't url_decode the password after getting them from the header. In this case, he checks `urlencoded_password===password`

in the end the url_encoding makes no sense for me.

**Comment by zandbelt** [comment]
see: https://github.com/zmartzone/lua-resty-openidc/issues/204; your IDP needs to be fixed...

**Comment by freegroup** [comment]
thanks for your support. I forward this info to our IDP team.
