### ISSUE TITLE
How to add multiple access_by_lua_file directive under same location = /_sample

### ISSUE THREAD

**Issue by satscreate** [zmartzone/lua-resty-openidc#315]
Using openidc module introspection under location and calling using below,

```
 Policy section
#
location = /_sample {
    internal;
    set $api_name "sample"; 
	access_by_lua_file /etc/nginx/path/oauth_introspection.lua;
     Proxypass......
}
```

Now i want to include below lua file to add some contents and validate something under the same request. 

```
 Policy section
#
location = /_sample {
    internal;
    set $api_name "sample"; 
	access_by_lua_file /etc/nginx/path/oauth_introspection.lua;
        access_by_lua_file /etc/nginx/path/do_something.lua; //Error with duplicate
     Proxypass......
}
```

And my oauth_introspection.lua has this openidc introspect logic,
`          local res, err = require("resty.openidc").introspect(opts)`

**Comment by bodewig** [comment]
This really looks more like a mix of Lua and lua-nginx-module question :-)

I believe there can only be one `access_*` directive. But you could certainly combine the two via Lua code. `access_by_lua_block` could be an approach or `access_by_lua_file`  which uses a new Lua file. This custom code would then load the two files and execute them in sequence.

**Comment by satscreate** [comment]
> This really looks more like a mix of Lua and lua-nginx-module question :-)
> 
> I believe there can only be one `access_*` directive. But you could certainly combine the two via Lua code. `access_by_lua_block` could be an approach or `access_by_lua_file` which uses a new Lua file. This custom code would then load the two files and execute them in sequence.

Thanks for clarification @bodewig . Can you help me with some example or may be with the above code?

**Comment by bodewig** [comment]
I'm guessing how the lua module works when you do `access_by_lua_file`, really. Most likely it uses [loadfile](https://www.lua.org/manual/5.1/manual.html#pdf-loadfile). If this is true then

```
access_by_lua_block {
    loadfile('/etc/nginx/path/oauth_introspection.lua')()
    loadfile('/etc/nginx/path/do_something.lua')()
}
```

should do something like you describe.

Most likely you are better off refactoring the Lua code into modules and `require` them rather then using `loadfile`.
