### ISSUE TITLE
Role based access not working if user has multiple roles

### ISSUE THREAD

**Issue by larkoie** [zmartzone/lua-resty-openidc#322]
Hi,
I was able to put SSO authentication in place which is authorizing any user to access to a restricted area of our webapp.
However i'm not able to make it work with role based access because I can't have LUA to parse my roles in the res.user.groupNAME because it returns value "nil".

Here is the userinfo returned by the discovery :
`{
  cn = "Doe, Jon",
  country = "US",
  employeetype = "Employee",
  firstname = "Jon",
  businesssegment = "Corporate Digital",
  hrid = "1234",
  groupNAME = { "@group 1", "@group 2", "@group 3" },
  lastname = "Doe",
  location = "Boston",
  mail = "Jon.Doe@company.com",
  title = "CEO"
} `

If I add a rule to allow users from "location" = "Boston" it works : 

```
location /test {
          access_by_lua_block {
            local opts = {
            redirect_uri = "http://openresty-test.com/test/sso",
            discovery = "https://myisp.com/fss/.well-known/openid-configuration",
            client_id = "my_application",
            client_secret = "my_secret",
            scope = "openid profile",
            ssl_verify = "no"
          }
        local res, err = require("resty.openidc").authenticate(opts)
                
          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

          if res.user.location ~= "Boston" then
          ngx.exit(ngx.HTTP_FORBIDDEN)
          end
         }
```
Now if I want to make sure that the user is in "group 2" it doesn't work. "groupNAME" is a table within the claims returned from the user info endpoint but i'm not able to access it by any mean.
Here I tried to parse it with a function but it says it can't work with a null value (I know that in the example a user belonging to "group 2" would be denied access but it was just to test if the function works):
```
function contains(list, x)
      for _, v in pairs(list) do
          if v == x then return true end
      end
      return false
end

if contains(res.user.groupNAME, "@group 2") then
    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
end
```

So i tried to debug and wanted to return only the "groupNAME" attribute but it returns "nil" value. I tried lots of things to get this value but no success so far. A few examples:
```
ngx.print(res.user.groupNAME) => "nil"
ngx.print(res.user["groupNAME"]) => error : "attempt to index field 'groupNAME' (a nil value)"
ngx.print(res.user[1]) => "nil"
```

I tried other things with "inspect.lua" which resulted in more "nil".

**My question:**
Do you have an example of parsing a table returned as a claim? At first I was thinking it would be very easy to do but after a full day on it i'm still unable to make it work :(

###### Environment
- CentOS 7
- openresty.x86_64    1.15.8.3-1.el7
- lua.x86_64               5.1.4-15.el7
- lua-resty-openidc   1.7.2

Thanks

**Comment by bodewig** [comment]
is `res.user.groupNAME` nil as well?

I'd expect `type(res.user.groupNAME)` to be `table`.

**Comment by larkoie** [comment]
Yes it returns "table".
I did check it with type to understand why it would not be parsed because openresty was returning "not an array table" for one of my test (don't remember which because I tried lots of things ^^ )

**Comment by bodewig** [comment]
Sorry, if it is nil it can't be a table at the same time :-)

We use `cjson_safe` (see https://www.kyne.com.au/~mark/software/lua-cjson-manual.html) as decoder and I'd expect it to parse your claim into a table (likely of the  array flavor). You could `cjson.encode` your `res.user` to get something loggable. Sorry, I don't have time for testing it myself right now.

**Comment by larkoie** [comment]
I don't know why it returns "nil" when printing and "table" when checking with "type" but I swear it's the case, I just retested it right now:
```
local typp = type(res.user.groupNAME)
ngx.print(typp)
```
returns => table


`ngx.print(res.user.groupName)`
returns => nil

I'll have a look at your tips, thanks for pointing to a solution, i'll update with my results.

**Comment by larkoie** [comment]
Ok I solve the mystery. After your comment saying it could not return table and nil at the same time I double checked everything and ... I had a typo in the key name.
The key is groupNAME and i started to test groupName at some point, hence the "nil". So a big fail for me but here is my working Lua if someone has the same need (then this issue might be helpful to others ;) ): 

```
location /test {
          access_by_lua_block {
            local opts = {
            redirect_uri = "http://openresty-test.com/test/sso",
            discovery = "https://myisp.com/fss/.well-known/openid-configuration",
            client_id = "my_application",
            client_secret = "my_secret",
            scope = "openid profile",
            ssl_verify = "no"
          }
        local res, err = require("resty.openidc").authenticate(opts)
                
          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

         function contains(list, x)
            for _, v in pairs(list) do
                if v == x then return true end
            end
            return false
          end

          if contains(res.user.groupNAME, "group 2") then
            ngx.exit(ngx.OK)
          else
            ngx.exit(ngx.HTTP_FORBIDDEN)
          end
```
So it checks if the user is member of "group 2" from the group list "res.user.groupNAME" returned by the user info endpoint. If it does he gets access to the content, else he gets a forbidden access error.

@bodewig thank you for your kind help, sorry for this mistake :)

**Comment by bodewig** [comment]
I'm glad you figured it out. Thank you for sharing.
