### ISSUE TITLE
Redirect Loop with lua-resty-session 3.X

### ISSUE THREAD

**Issue by xurxofp** [zmartzone/lua-resty-openidc#323]
###### Environment

- lua-resty-openidc version: 1.7.2
- OpenID Connect provider Keycloak

###### Expected behaviour

One redirect from login to the page itself

###### Actual behaviour

Infinite redirect loop

###### Explanation

I'm developing an integration with keycloak and this tool, but the things that where working last week did not work today. 
After searching the internet I've found #32, and definetly I was getting something similar. Following that, I've found that lua-resty-session was updated this weekend. Going back to previous version solved the problem.

**Comment by 1wpro2** [comment]
What's the version you have been restoring to make it work? I have reverted to as old as `lua-resty-session (using 2.25-1)`, still facing the infinite redirect loop.

**Comment by bodewig** [comment]
by now several newer issues indicates lua-resty-openidc works with more recent lua-resty-session versions, even thoguh I haven't tried it myself.
