### ISSUE TITLE
How to make it work with OpenAM ?

### ISSUE THREAD

**Issue by AramshamFedaykin** [zmartzone/lua-resty-openidc#324]
Please help me to make it work...

#### Environment
- OpenResty 1.15.8.2
- lua-resty-openidc 1.7.2
- OpenID Connect provider OpenAM (ForgeRock)
- Java Springboot app for REST api with angular frontend

Test in localhost and on kubernetes

###### Actual behaviour
1) In localhost, it seems the module consumes the authZ code, as in my app when in the redirect_uri I try to get an access_token from that code, openam tells me it's already expired. Is it the good behaviour ? Because on kubernetes, it doesn't, so my app can get that access_token

2) It seems there's no caching, or maybe I didn't configure it correctly, as I'm still redirected to authZ grant after a page refresh

3) There's no Authorization header set, even with ngx.req.set_header("Authorization", "Bearer " .. res.access_token)

###### Minimized example

worker_processes  1;

error_log  logs/error.log;
error_log  logs/error.log  notice;
error_log  logs/error.log  debug;

events {
    worker_connections  1024;
}

http {
	lua_package_path '~/lua/?.lua;;';

	resolver ${dns.ip};

	lua_ssl_trusted_certificate /ssl/certs/chain.pem;
	lua_ssl_verify_depth 5;

	lua_shared_dict discovery 1m;
	lua_shared_dict jwks 1m;
	lua_shared_dict introspection 10m;
	
	lua_shared_dict sessions 10m;
	
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
		server_name  _;
        listen       80;
		
        location / {
			access_by_lua_block {
				local opts = {
					discovery = "https://${openam}/.well-known/openid-configuration",
					redirect_uri = "/OAuth2Client/REST/v1/authorization-code/callback",
					client_id = "${clientId}",
					client_secret = "${clientSecret}",
					scope = "openid profile email",
				}
				
				local ah = ngx.req.get_headers()["Authorization"]

				if ah and string.find(ah, "Bearer ") then
					local res, err = require("resty.openidc").bearer_jwt_verify(opts)

					if err or not res then
						ngx.status = 403
						ngx.exit(ngx.HTTP_FORBIDDEN)
					end

					ngx.req.set_header("X-USER", res.name)

				else				
					-- OIDC Authentication
					local res, err = require("resty.openidc").authenticate(opts)

					if err then
						ngx.status = 500
						ngx.say(err)
						ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
					end

					ngx.req.set_header("Authorization", "Bearer " .. res.access_token)
					ngx.req.set_header("X-USER", res.id_token.sub)
				end
			}

			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header X-Forwarded-Scheme $scheme;
			proxy_set_header X-Scheme $scheme;
			
			proxy_pass  http://${localhost or clusterIP}/OAuth2Client;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
		
        location /OAuth2Client {
        	proxy_pass  http://${localhost or clusterIP}/OAuth2Client;
        }

        location /OAuth2Client/REST/v1/authorization-code/callback {
        	proxy_pass  http://${localhost or clusterIP}/OAuth2Client/REST/v1/authorization-code/callback;
        }
    }
}

###### Configuration and NGINX server log files
In localhost, nginx on port 80, app on 8080
On Kubernetes, app on clusterIP, then ingress, nginx as ingress controller

**Comment by bodewig** [comment]
I don't think I understand what you are trying to do. If you want to implement the Authorization Code Grant Flow yourself with your own callback URI, why do you use `authenticate` at all? Triggering the flow, consuming the code and obtaining the token(s) is the whole purpose of that method.

As for caching, I don't see any configuration of lua-resty-session. By default, the session information is stored inside an encrypted cookie. If you run multiple instances (several pods in k8s for example) they will use different encryption keys and state will be lost whenever you switch between instances. This could explain the behavior you see.

Finally I may be wrong, but I believe setting `ngx.req.set_header` is not enough for the new header to be sent in a proxy request. In similar instances I define an nginx variable, explicitly set that and have a `proxy_set_header` directive. Something like

```
    set $auth '';
    location / {
      access_by_lua_block {
      ...
        mgx.var.auth = Bearer " .. res.access_token
      }
      ...
      proxy_set_header 'Authorization' $auth;
    }
```

**Comment by AramshamFedaykin** [comment]
Well in fact I don't want to implement the authZ code grant flow myself, but then it's something I apparently didn't understand.

So here's the history : I started a java app in Springboot, where I indeed handled myself the flow. But then I wanted to remove the boilerplate for that and let nginx do it for me (and for another app if needed) without java code. So for my app, I asked the team responsible for openam to add my redirect_uri in their whitelist (I asked them for my localhost and for the ingress controller).
So before, I did the check of the authZ code inside my java code, I didn't get that lua-resty-openidc already did...but I also made a redirection to my app rootContext.

Ok then, so I just removed that check in my java code, and added the ngx.var you provided. But then I don't understand. I thought that after the redirect_uri is called, nginx will fwd to the proxy_pass with the new header, but it's not the case, or am I still missing something ?

Forgive me if I ask dumb questions, nginx and lua are something really new for me, so please correct me if I'm wrong.

Ah ok for lua-resty-session, I'll try it on k8s, but for now, if it can work in local I'll be very happy :)

**Comment by AramshamFedaykin** [comment]
In fact it nearly work !

1) I had to add token_endpoint_auth_method = "client_secret_basic" as openam was configured in that mode.
2) Added a a missing dependency to lua-resty-hmac, needed in lua-resty-jwt
3) I still got a prob retrieving the jwk though, but I'm seeing this with the openam team.

So that's why I didn't go to the proxy_pass, I understand better now.
