### ISSUE TITLE
proxy_opts not accepted - what am I doing wrong?

### ISSUE THREAD

**Issue by brianp9906** [zmartzone/lua-resty-openidc#331]
###### Environment

- lua-resty-openidc master (just pulled today as of this post)
- OpenID Connect provider => Okta

###### Expected behaviour
LUA uses proxy to talk to Okta

###### Actual behaviour
LUA chokes at the config or is trying direct internet.

###### Minimized example
I put proxy_opts after opts because if I nest it inside, it chokes with error "failed to load inlined Lua code: access_by_lua ... expected (to close '{' at line 4) near 'local'

If I put it outside local opts variable, it is accepted but not honored.

What am I doing wrong?

`location / {
  access_by_lua_block {
    -- local openidc = require("resty.openidc")
    -- openidc.set_logging(nil, { DEBUG = ngx.INFO })
    local opts = {
      discovery = "https://mytestinstance.okta.com/.well-known/openid-configuration",
      client_id = "test",
      client_secret = "test",
      ssl_verify = "no",
      scope = "openid email profile",
      redirect_uri_scheme = "https",
      accept_unsupported_alg = false,
      token_signing_alg_values_expected = { "RS256" },
      access_token_expires_leeway = 30,
      revoke_tokens_on_logout = true,
      token_endpoint_auth_method = "client_secret_basic"
    }
    local proxy_opts = {
      http_proxy  = "http://10.1.1.1:8080/",
      https_proxy = "http://10.1.1.1:8080/"
    }
    -- call authenticate for OpenID Connect user authentication
    local res, err = require("resty.openidc").authenticate(opts)

    if err then
      ngx.status = 403
      ngx.say(err)
      ngx.exit(ngx.HTTP_FORBIDDEN)
    end

  }
  expires           0;
  add_header        Cache-Control private;
  include conf.d/proxy.common;
  proxy_pass 'http://127.0.0.1:8080';
}`

**Comment by vavra5** [comment]
Hi brianp9906,

Not sure if your still having an issue with this.  What I found out was that the lua-resty-http module did not support proxy authentication.  When installing lua-resty-openidc=1.7.2 it auto installs dependencies defined as ‘requires = openresty, pintsized/lua-resty-http >= 0.08, bungle/lua-resty-session >= 2.8, cdbattags/lua-resty-jwt >= 0.2.0’. I noticed on the latest master branch for lua-resty-openidc these dependencies are now “requires = openresty, ledgetech/lua-resty-http >= 0.13, bungle/lua-resty-session >= 2.8, cdbattags/lua-resty-jwt >= 0.2.0”. I updated the my docker image to now have this new version (ledgetech/lua-resty-http=0.14).  You can verify that you have the current deps by running: 

`docker exec $imagename bash -c "cat /usr/local/openresty/site/lualib/resty/http.lua | grep proxy_authorization"`

Dockerfile:
```
RUN ["opm", "get", "zmartzone/lua-resty-openidc=1.7.2"]
RUN ["opm", "remove", "pintsized/lua-resty-http"]
RUN ["opm", "get", "ledgetech/lua-resty-http=0.14"]
```

OpenResty Config:
```
location / {
access_by_lua_block {
-- local openidc = require("resty.openidc")
-- openidc.set_logging(nil, { DEBUG = ngx.INFO })
local opts = {
discovery = "https://mytestinstance.okta.com/.well-known/openid-configuration",
client_id = "test",
client_secret = "test",
ssl_verify = "no",
scope = "openid email profile",
redirect_uri_scheme = "https",
accept_unsupported_alg = false,
token_signing_alg_values_expected = { "RS256" },
access_token_expires_leeway = 30,
revoke_tokens_on_logout = true,
token_endpoint_auth_method = "client_secret_basic",
proxy_opts = {
  http_proxy  = "http://10.1.1.1:8080/",
  https_proxy = "http://10.1.1.1:8080/",
  no_proxy = "localhost,127.0.0.1",
  http_proxy_authorization = "proxy_user",
  https_proxy_authorization = "proxy_password"
}
}
-- call authenticate for OpenID Connect user authentication
local res, err = require("resty.openidc").authenticate(opts)

if err then
  ngx.status = 403
  ngx.say(err)
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
}
expires 0;
add_header Cache-Control private;
include conf.d/proxy.common;
proxy_pass 'http://127.0.0.1:8080';
}
```

**Comment by bodewig** [comment]
I don't see how `proxy_opts` is ever passed to `authenticate`.

**Comment by stubclan** [comment]
I am having a similar issue. I am getting the following error:
`2020/06/15 23:04:50 [error] 6#6: *26 [lua] openidc.lua:486: openidc_discover(): accessing discovery url (<host>/.well-known/openid-configuration) failed: failed to establish a tunnel through a proxy: 407, client: 100.64.179.109, server: _, request: "GET / HTTP/1.0", host: "<client host>"`

@vavra5 for http_proxy_authorization shouldn't it be something like = "Basic [64base username:password]" ?

**Comment by vavra5** [comment]
@bodewig I not positive but is it using the value here when creating a new http connection?
https://github.com/zmartzone/lua-resty-openidc/blob/9155766ea354cb74c6fe496eaa7545e822f60297/lib/resty/openidc.lua#L493

@stubclan 
Yes you are correct.  I updated my original answer.

**Comment by bodewig** [comment]
@vavra5 this is where lua-resty-openidc uses `opts.proxy_opts`, right.

What I don't see in @brianp9906 original snippet is where `proxy_opts`ever becomes assigned to `opts.proxy_opts`. To me it looks as if the local variable was assigned but never passed to the `authenticate` function.

**Comment by vavra5** [comment]
@vavra5 I agree I don't think @brianp9906 original snippet will work correctly.  It looks like whenever lua-resty-openidc needs to create a new http connection it setups `proxy_opts`.  I was having issues especially with the `discovery_url`.  Naturally because it was an external uri in which I need to go through our corporate proxy.  This is what led me to look and the `openidc_discover` function.

https://github.com/zmartzone/lua-resty-openidc/blob/9155766ea354cb74c6fe496eaa7545e822f60297/lib/resty/openidc.lua#L533

**Comment by bodewig** [comment]
Sorry, I missed you actually provided the solution already @vavra5 Thanks!

So what needs to be done is to install a newer version of lua-resty-http which will be what the next version of lua-resty-openidc requies anyway. When installed vial opm and not luarocks, that is, I don't see us requiring a newer version in the rockspec. This is our users can do by themselves.

**Comment by stubclan** [comment]
Any idea what I'm doing wrong? I'm getting the following error:
> There was an error while logging in: accessing discovery url (https:/<url>/.well-known/openid-configuration) failed: failed to establish a tunnel through a proxy: 407
```
local opts = {
    redirect_uri_path = os.getenv("OID_REDIRECT_PATH") or "/redirect_uri",
    discovery = os.getenv("OID_DISCOVERY"
    client_id = os.getenv("OID_CLIENT_ID"),
    client_secret = os.getenv("OID_CLIENT_SECRET"),
    token_endpoint_auth_method = os.getenv("OIDC_AUTH_METHOD") or "client_secret_basic",
    scope = os.getenv("OIDC_AUTH_SCOPE") or "openid",
    iat_slack = 86400,
    ssl_verify = "no",
    keepalive = "no",
    renew_access_token_on_expiry = false,
    access_token_expires_in = 86400,
    client_jwt_assertion_expires_in = 86400,   
    http_request_decorator = function(req)
      local h = req.headers or {}
      h["Access-Control-Allow-Origin"] = "*"
      h["Access-Control-Allow-Credentials"] = "true"
      h["Access-Control-Max-Age"] = "600"
      h["Access-Control-Allow-Methods"] = "GET,POST,PUT,DELETE,OPTIONS"
      h["Allow"] = "GET,POST,PUT,DELETE,OPTIONS"
      h["Authorization"] = "Basic [64base username:password]"
      req.headers = h
      return req
    end,
    proxy_opts = {
        http_proxy = "http://proxyurl:80/", 
        https_proxy = "http://proxyurl:80/",
        no_proxy = "localhost,127.0.0.1",
        http_proxy_authorization = "Basic  [64base username:password]",
        https_proxy_authorization = "Basic [64base username:password]",
    }
}
local res, err, _target, session = require("resty.openidc").authenticate(opts, nil, nil, nil)
```

**Comment by bodewig** [comment]
are you using lua-resty-http 0.13 or later?

**Comment by stubclan** [comment]
@bodewig I think you just solved the issue for me. I was using 0.12. I'm trying to verify but THANK YOU VERY MUCH 👍
