### ISSUE TITLE
request to the redirect_uri path but there's no session state found

### ISSUE THREAD

**Issue by javalabrep** [zmartzone/lua-resty-openidc#338]
I have an Enpoind which I want to protect using openidc-resty. After the Authorization Flow I want to protect the same endpoint using basic Authentication in backend. Basic Authentication alone works fine but how to put openidc in front of it. Right now I am trying this:
 

 location /myEndpoint {
            access_by_lua_block {
                local opts = {
                    redirect_uri = "https://localhost:myPort/myEndpoint",
                    discovery = "https://HOST/.well-known/openid-configuration",
                    client_id = "myClientId",
                    client_secret = "myClientSecret",
                    scope = "openid",
                    ssl_verify = "no"
                }
                local res, err = require("resty.openidc").authenticate(opts)
                if err then
                    ngx.status = 500
                    ngx.say(err)
                    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                end    
            }
        }
	

I am getting the following Error: request to the redirect_uri path but there's no session state found

**Comment by 1wpro2** [comment]
Can you add the `target_url` to be `/`, see if it works?

**Comment by bodewig** [comment]
The `redirect_uri` is something required by the authorization code grant flow. It is provided and used by lua-resty-openidc should not be the same as the location. Your location should spawn all URIs you want to protect and the redirect_uri may be something inside of this location - the implementation is provided by lua-resty-openidc itself.

**Comment by ledbruno** [comment]
Having similar problems as described here: https://github.com/nokia/kong-oidc/issues/179

**Comment by Chinnuganga** [comment]
Facing the same error while using using openidc-resty to add authentication to an application. The integration works fine when accessed directly through browser.

Now we are looking for SSO while login from Application 1 which is keycloak integrated.
We are trying to load the application2 through an iframe from application1.
The application 2 is integrated with openidc-resty to achieve integration with keycloak.

Now, when we local application2 in an iframe within application1, we are facing the following error

**"There was an error while logging in: request to the redirect_uri_path but there's no session state found"**

Also we could see some of the keycloak cookies are blocked by browser with the following error

**"Set-Cookie didn't specify a "Same-Site" attribute and was defaulted to "Same-Site=Lax", and was blocked because it came from a cross-site response"**

The following Keycloak cookies were blocked by this error

KC_RESTART
KEYCLOAK_IDENTITY_LEGACY
KEYCLOAK_SESSION_LEGACY
KEYCLOAK_REMEMBER_ME

Can someone please suggest a solution to this issue?

**Comment by bodewig** [comment]
You must ensure Keycloak properly sets `SameSite`, please don't expect us to know more about Keycloak than you do.

Please note that 3rd party cookies - in particular in iframes - fall under restrictions that vary from browser to browser and that are becoming more and more strict.

**Comment by chaserb** [comment]
As @bodewig mentioned, the redirect_uri is used in the auth code grant type, which involves redirecting the browser from your client (the one protected by openresty) to the OAuth authorization server (AS), and back to your client. If your client is configured with 'Strict' for the [SameSite policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) on your session cookie, then the browser will not send that cookie to your client when redirecting from the AS back to your client. This forces your client to conclude that "there's no session state found". 

In my case, I solved this problem by removing the following line from my nginx.conf:
```
set $session_cookie_samesite Strict;
```

**Comment by DoublleW** [comment]
in my case, I solved the problem by adding `/redirect_uri` at the end of the location, i.e. `redirect_uri = "/<my_location>/redirect_uri"`

and Firefox begins to process redirects correctly

![изображение](https://github.com/zmartzone/lua-resty-openidc/assets/50780433/18c4c4ee-0189-49a2-9103-b901791650b4)


location description block for openresty
```
            access_by_lua_block {
                local opts = {
                    redirect_uri_path = "/redirect_uri",
                    redirect_uri = "/<my_location>/redirect_uri",
                    accept_none_alg = true,
                    discovery = "http://<ip_keycloak>:<port>/realms/key/.well-known/openid-configuration",
                    client_id = "<client_id>",
                    client_secret = "<sec-key>",
                    ssl_verify = "no",
                    renew_access_token_on_expiry = true,
                    scope = "openid",
                    redirect_uri_scheme = "http",
                    logout_path = "/<my_location>/logout",
                    redirect_after_logout_uri = "http://<ip_keycloak>:<port>/realms/key/protocol/openid-connect/logout?redirect_uri=http://<ip_or_url>/",
                    redirect_after_logout_with_id_token_hint = false,
                    session_contents = {id_token=true}
                }
                local res, err = require("resty.openidc").authenticate(opts)
                if err or not res then
                        ngx.status = 401
                        ngx.log(ngx.ERR, "error: ", err)
                        ngx.say("")
                        ngx.exit(ngx.HTTP_UNAUTHORIZED)
                end
            }
```

In keycloak settings: Clients -> Client details -> Valid redirect URIs = `*`.

In one configuration for openresty you can configure both `bearer_jwt_verify` validation and `require("resty.openidc").authenticate(opts)`.

issue is already closed, but maybe my description will help someone ...
