### ISSUE TITLE
Shoudn't we prevent the regenerate command from flushing the data?

### ISSUE THREAD

**Issue by mcg1969** [zmartzone/lua-resty-openidc#340]
https://github.com/zmartzone/lua-resty-openidc/blob/9155766ea354cb74c6fe496eaa7545e822f60297/lib/resty/openidc.lua#L1342

Here's the source code for the `regenerate` command:
https://github.com/bungle/lua-resty-session/blob/f300870ce4eee3f4903e0565c589f1faf0c1c5aa/lib/resty/session.lua#L325-L337

Furthermore, as this line shows, the default value of `flush` is `true`:
https://github.com/bungle/lua-resty-session/blob/f300870ce4eee3f4903e0565c589f1faf0c1c5aa/lib/resty/session.lua#L325-L337

But this means we're clearing the data we just finished saving, are we not?

**Comment by bodewig** [comment]
We are invoking https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L675 without any arguments, so both flush and close are nil and flush remains nil (while close becomes true).
