### ISSUE TITLE
Is it possible to use basic auth?

### ISSUE THREAD

**Issue by bbigras** [zmartzone/lua-resty-openidc#347]
I saw that I can use lua-resty-openidc with OpenResty to use keycloak with a redirect.

I think I can't use a redirect with my git server. I think I need basic auth for that.

I guess I could use something else for the basic auth but I would prefer using keycloak with the roles I already use.

Is it possible?

**Comment by bodewig** [comment]
It may be possible to use Keycloak for that, but not using lua-resty-openidc. This library only handles the authorization code grant flow and some resource server parts of OAuth2.

**Comment by bbigras** [comment]
Thanks!
