### ISSUE TITLE
Not seeing Authorization header on successful authentication and redirect

### ISSUE THREAD

**Issue by jordanpurinton** [zmartzone/lua-resty-openidc#348]
I have a client application that is gated by `lua-resty-openidc`.

When I finish the following call:
```
local res, err, _target, session = require("resty.openidc").authenticate(opts)
```

I then try to pass the parsed token as a header:
```
ngx.req.set_header("Authorization", "Bearer "..session.data.enc_id_token)
```

However, when I hit my application in the browser and the redirect goes through successfully, I can see the openresty `server` header just fine, but I'm not seeing my authorization header anywhere in the response.

**Question**: How can I consume the token on the client?

**Comment by bodewig** [comment]
I'm not sure I understand the question.

Are you trying to send the `Authorization` header to the caller of your server? In that case you must set it on the response, not on the request.

**Comment by jordanpurinton** [comment]
Hmm, how exactly would I do that?

**Comment by bodewig** [comment]
https://github.com/openresty/lua-nginx-module/#ngxheaderheader

**Comment by jordanpurinton** [comment]
Thanks! That got me exactly what I needed.
