### ISSUE TITLE
Not seeing Code_Challenge and Code_Verifier when PKCE is set.

### ISSUE THREAD

**Issue by devgig** [zmartzone/lua-resty-openidc#349]
###### Environment

- lua-resty-openidc version (e.g. 1.7.2)
- OpenID Connect provider (e.g. Keycloak, Azure AD)

###### Expected behaviour
seeing code_verifier in the post to get a token
###### Actual behaviour
code_verfier is missing
###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*
add  use_pkce = true, to opts
###### Configuration and NGINX server log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by devgig** [comment]
@bodewig 
Looks the pkce stuff is only added for the ```openidc_authorize``` call, and I am not for sure what I need to do to trigger it.  I would expect that ```openidc.authenticate``` would add it, which is what I think I am calling for 
```
local res, err, _target, session = require("resty.openidc").authenticate(opts, nil, nil, nil)
```

**Comment by bodewig** [comment]
Support for PKCE has only been added recently and is not part of 1.7.2.

**Comment by devgig** [comment]
> Support for PKCE has only been added recently and is not part of 1.7.2.

That makes sense.  I did notice that it was like 7 days old.  Do you have a target release date for PKCE?

**Comment by stubclan** [comment]
@bodewig I need this feature as well (use_pkce) same as @devgig. Any idea when the next release would be? Don't want to rely on master.

**Comment by bodewig** [comment]
I don't see any reason why we couldn't release master. So yes, we can.
