### ISSUE TITLE
redirect uri encode twice

### ISSUE THREAD

**Issue by ar30067** [zmartzone/lua-resty-openidc#351]
###### Environment

- lua-resty-openidc-1.7.2 

###### Expected behaviour
it seems that in redirect to openid provider redirect url encode twice !
returnUrl=%2fHome%2fGetAuthorizationCode%3fresponse_type%3dcode%26client_id%3d7sD8RoPChTjnJk1S1zNA%26state%3d87af3be853708b4803f20556c1d698e6%26redirect_uri%3d**http%3A%2F%2Ftest.com**%26nonce%3d659a1b89f102b11f04e487ef7db69b99%26scope%3dopenid%2520email%2520profile

###### Actual behaviour
returnUrl=%2fHome%2fGetAuthorizationCode%3fresponse_type%3dcode%26client_id%3d7sD8RoPChTjnJk1S1zNA%26state%3d87af3be853708b4803f20556c1d698e6%26redirect_uri%3d**http%253A%252F%252Ftest.com**%26nonce%3d659a1b89f102b11f04e487ef7db69b99%26scope%3dopenid%2520email%2520profile
redirect_uri%3Dhttp%3A%2F%2Ftest.com

###########configuration ##############
 local opts = {
             redirect_uri = "http://test.com",

**Comment by zandbelt** [comment]
`returnUrl` is not something constructed by lua-resty-openidc, not sure where you got that value from

**Comment by ar30067** [comment]
thanks for answer
i find out the problem :
lua-resty-openidc first return to my provider by url that encoded :
https://myOIDprovider.com/Home/GetAuthorizationCode?response_type=code&client_id=7sD8RoPChTjnJk1S1zNA&state=fddf34768957923f263ac9159bb318e0&redirect_uri=**http%3A%2F%2Ftest.com**&nonce=cef9da7b5b27864f9bce68049459b554&scope=openid%20email%20profile

then my provider redirect me to 

https://myOIDprovider.com/Home/Login?returnUrl=%2fHome%2fGetAuthorizationCode%3fresponse_type%3dcode%26client_id%3d7sD8RoPChTjnJk1S1zNA%26state%3dfddf34768957923f263ac9159bb318e0%26redirect_uri%3d**http%253A%252F%252Ftest.com**%26nonce%3dcef9da7b5b27864f9bce68049459b554%26scope%3dopenid%2520email%2520profile

is it possible to prevent lua-resty-openidc in first step to not encode redirect url ?

**Comment by zandbelt** [comment]
no, encoding is done according to the spec
