### ISSUE TITLE
Is it possible to explicitly request a new id token?

### ISSUE THREAD

**Issue by emily-ng** [zmartzone/lua-resty-openidc#354]
###### Environment

- lua-resty-openidc version (e.g. 1.5.4)
- OpenID Connect provider (e.g. Keycloak)

Is there something similar to `openidc.access_token(opts, session_opts)` for getting a valid id token? Thanks.

**Comment by bodewig** [comment]
No, there isn't, yet.

It shouldn't be too difficult to implement in particular since our token refresh code already deals with refreshing the `id_token` as well. An extra problem may arise if the OpenID Connect provider doesn't return a new id_token on refresh and the existing one has expired - as you are explicitly asking for a valid token.

**Comment by emily-ng** [comment]
So we want to refresh the id token from the provider because we have a claim on that token that will need to be updated at some point during the user's session hence why we're trying to find a way to do the explicit refresh. But you're saying that explicitly asking for a valid id token might cause issues. Is doing so bad practice?

Not sure if this is the right place to ask but I'm learning as I go and I haven't seen anything that works for our use case yet (if that use case even makes sense).

**Comment by zandbelt** [comment]
the use case makes sense but typically you'd access the userinfo endpoint again with the access token that is stored in the session

**Comment by bodewig** [comment]
OpenID Connect doesn't provide a way to obtain a fresh id token. You obtain one when performing the authorization flow and may receive a new one during refresh. A way to obtain a new one usually is to re-run the authorization flow with `prompt=none`.

If your userinfo endpoint contains the same information that your id token would, then accessing it like @zandbelt suggests is probably the better idea.

**Comment by emily-ng** [comment]
@zandbelt @bodewig Thank you! The userinfo endpoint was what I needed. This was all very helpful.
