### ISSUE TITLE
Support special case for XHR with silent (re-)authorization

### ISSUE THREAD

**Issue by arcivanov** [zmartzone/lua-resty-openidc#357]
XHR behavior is distinctly different from the normal request flow.
Whenever XHR request results in silent reauthorization
https://github.com/zmartzone/lua-resty-openidc/blob/bfcfcce577185a95b019c34e446fe6b089124cbf/lib/resty/openidc.lua#L1490-L1492
the subsequent redirect
https://github.com/zmartzone/lua-resty-openidc/blob/bfcfcce577185a95b019c34e446fe6b089124cbf/lib/resty/openidc.lua#L380-L382
will result in a number of failures:

* To succeed in 302 XHR, the cross-site scripting has to be authorized between the RP and OP which virtually is never the case
* XHR cannot set cookies.
* XHR cannot see the 302 destination and therefore cannot analyze the cause for 302 to respond appropriately.

There is no universal way to handle this scenario without pigeonholing the user into a highly custom solution. It is therefore proposed that redirect handler function is introduced into lifecycle allowing the user to chose the appropriate behavior of the request when redirect is indicated but may not be appropriate.

PR is incoming.

**Comment by bodewig** [comment]
I agree with your description of the problem but wouldn't `unauth_action = deny`give you the opportunity to do whatever is needed after `authenticate` returns?`

**Comment by arcivanov** [comment]
Fair point, but looking at the code there are still changes needed, such as in case of the silent reauth.

**Comment by arcivanov** [comment]
@bodewig bump?

**Comment by arcivanov** [comment]
Closed per #358. Please see https://github.com/zmartzone/lua-resty-openidc/pull/358#issuecomment-704712676 for solution.
