### ISSUE TITLE
Logout users by admin console, single sign off, k_logout, refresh token, destroy session

### ISSUE THREAD

**Issue by barpaw** [zmartzone/lua-resty-openidc#359]
I have a problem with logout people by Admin Console. I can’t do it.
I properly configured Admin URL in Keycloak and my nginx server gets some requests (POST /k_logout and POST /k_push_not_before). Does this library can somehow handle this? (or apache mod_auth_openidc can handle this?)
I also found something strange (I'm new user of keycloak so...). When I destroy a session for specific user (by Admin Console) in realm “A” this user can still send request to the proxied server (probably because user’s token didn't expired?). After that, when I go to realm "B" login page and go back to realm "A" - session "A" is correctly destroyed. Maybe when I do something like that the Realm „A” is requesting KeyCloak and revalidating Token.

Can I get revalidation of the Token by means of this library? Maybe there is other way which I can use to logout users by Admin Console?

**Comment by bodewig** [comment]
Currently this library doesn't support the front- or backchannel-logout specs of OpenID Connect.
