### ISSUE TITLE
Why lua-resty-jwt is fixed to version 0.2.0 in lua-resty-openidc 1.7.3 ?

### ISSUE THREAD

**Issue by kayano** [zmartzone/lua-resty-openidc#362]
Not sure why `lua-resty-jwt` was fixed to `0.2.0` here https://github.com/zmartzone/lua-resty-openidc/commit/985d0c5c3aec8ab917d6b8ea89840e93b68db91c while it was `lua-resty-jwt >= 0.2.0` before.
`lua-resty-jwt 0.2.2` contains fix https://github.com/cdbattags/lua-resty-jwt/pull/26 and without the fix I'm not able to use latest version of `lua-resty-openidc`.

**Comment by zandbelt** [comment]
https://github.com/zmartzone/lua-resty-openidc/issues/326
