### ISSUE TITLE
unhandled request to the redirect_uri

### ISSUE THREAD

**Issue by oliverjoa** [zmartzone/lua-resty-openidc#368]
Hi,

I sometimes get errors about "unhandled requests". I am not sure when it happens, but I guess
that it could be when the session expires or when I am logged out. I am using it against keycloak. I sometimes get:

Error: unhandled request to the redirect_uri: /oidcredirect?error=login_required&state=aa75ff1d3ec0482d6b64e53a782f2f71

###### Environment

- lua-resty-openidc version: 1.7.2
- OpenID Connect provider: keycloak

###### Expected behaviour

I would expect that openidc redirects automatically to the login page again

Keycloak generates a redirect with "login_required". In my opinion openidc should get that and do a redirect to the login-page again. I had a look already into the sourcecode but that error isnt caught. Do I have to catch it
manually in the nginx code and do the redirect there?

###### Actual behaviour

I get a error:
Error: unhandled request to the redirect_uri: /oidcredirect?error=login_required&state=aa75ff1d3ec0482d6b64e53a782f2f71

###### Minimized example

It is not really reproducable.

###### Configuration and NGINX server log files

    set $session_secret <secret>;
    access_by_lua_block {

      local realm,c=string.gsub( ngx.var.host, "^([^.]+).*$", "%1")

      clientid="<clientid>"
      discovery = "https://<hostname>/auth/realms/".. realm .."/.well-known/openid-configuration"

      local opts = {
        redirect_uri = "https://"..ngx.var.host.."/oidcredirect",
        discovery = discovery,
        client_id = clientid,
        session_contents = {id_token=true,access_token=true},
        logout_path = "/logoutlogout",
        post_logout_redirect_uri = "https://"..ngx.var.host,
        refresh_session_interval = 60,
      }

      openidc=require("resty.openidc")
      openidc.set_logging(nil, { DEBUG = ngx.STDERR, ERROR = ngx.STDERR, WARN = ngx.STDERR })
      local res, err = openidc.authenticate(opts)

      function senderror(str)
        local session, session_error = require("resty.session").new()
        session:save()

        local host=ngx.req.get_headers()["Host"]
        ngx.log(ngx.STDERR,"openidc-lua error ("..host.."): "..str.."\n")
        ngx.status = 403
        ngx.header["Content-Type"] = "text/plain"
        ngx.say("Error: "..str)
        ngx.exit(ngx.HTTP_FORBIDDEN)
      end

      if err then
        senderror(err)
      end
     ...

**Comment by bodewig** [comment]
You get "unhandled request" if the `redirect_uri` is invoked without `state` or `code` parameter, In your example `/oidcredirect?error=login_required&state=aa75ff1d3ec0482d6b64e53a782f2f71` there is no `code` - actually because the OIDC provider returned an error.

Your example looks as if a silent auth code grant flow has been started with `prompt=none` and the OP rejected it and requires the user to actually log in.

**Comment by oliverjoa** [comment]
Ok, and what does that mean? What can I do? What is the "OP"?

**Comment by bodewig** [comment]
Sorry, OP == OpenID Connect Provider, i.e. keycloak in your case.

The only place where lua-resty-openidc uses `prompt=none` internally is when `opts.refresh_session_interval` has been hit. The message then means your session has timed out and according to keycloak the user is no longer present so the user needs to log in again. It is a very unfriendly way of telling you the user's session is no longer valid. How your application is supposed to react is something that's difficult to answer in general. Redirect to a non-authenticated place?
