### ISSUE TITLE
Possible session management issues

### ISSUE THREAD

**Issue by bungle** [zmartzone/lua-resty-openidc#374]
It has been reported to `lua-resty-session`:
https://github.com/bungle/lua-resty-session/issues/116

That sessions stay locked after the requests. I did some analysis and found these:
https://github.com/bungle/lua-resty-session/issues/116#issuecomment-735669374
https://github.com/bungle/lua-resty-session/issues/116#issuecomment-735750190

The main issue is in two public apis:
1. https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1385
2. https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1514

The first issue:
https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1393

There you start the session and start holding the possible lock. If any code path after that does return/error the lock will still be held. You must ensure that lock is always released (with `save`, `close`, `regenerate` or `destroy`) when `start` is called. There are a lot of places where the lock is not released, but the code returns. The OpenResty does not have a hook where the session library could hook itself to do it always, so it is library users' responsibility. If it is meant for users to close sessions with `openidc.authenticate` then it is the calling code that needs to do this always. But I think here your library is the user and it is `lua-resty-openidc`'s responsibility to "close" after start.

The second issue is easy to fix, replace:
https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1518
```lua
  return openidc_access_token(opts, session, true)
```
with:
```lua
  local token, err = openidc_access_token(opts, session, true)
  if err then
    session:close()
  end
  return token, err
```

**Comment by bodewig** [comment]
Thanks, @bungle . Have you seen https://github.com/zmartzone/lua-resty-openidc#sessions-and-locking ?

we are deliberately not closing the session as users may want to use it after we have returned from `authenticate`. For `access_token` things are different as we never return the session.

**Comment by bungle** [comment]
@bodewig, thanks for the info. Makes sense.

**Comment by bodewig** [comment]
I'll make sure we close the session in the `access_token` call the coming days.

Is there any reason why you wouldn't call `close` in the error case in your example above?

**Comment by bodewig** [comment]
I've also grep-ed for the places where `authenticate` doesn't return at all (i.e. cases where `ngx.exit` or `ngx.redirect` are invoked) and think only https://github.com/zmartzone/lua-resty-openidc/blob/49be8033b7a3dc0557c133f8616645ca19485950/lib/resty/openidc.lua#L282 might cause issues and I'll ensure we handle that as well - unlikely as the code path may be.

**Comment by bungle** [comment]
@bodewig,

Great findings!

> Is there any reason why you wouldn't call close in the non-error case in your example above?

I don't think there is any reason why `:close` cannot be called on already closed session. You are right, it looks more like a premature optimization.
