### ISSUE TITLE
Is using endpoints instead of discovery possible?

### ISSUE THREAD

**Issue by dlannan-fmad** [zmartzone/lua-resty-openidc#375]
Using openidc 1.7.4-1 and we are connecting to a Ping federate (I think - we are still trying to determine what customer is using).
We are creating a server with authentication using openidc. For reference we examined a grafana config on their network.
They have a grafana server using authentication using (not whole config here):
```
auth_url = "https://<server>/as/authorization.oauth2"
token_url = "https://<server>/as/token.oauth2"
api_url = "https://<server>/idp/userinfo.openid"
```

So, Im wondering if there is an equivalent set of configs for openidc.
From my understanding I should be able to use:

opts.discovery.token_endpoint      which is equivalent of token_url
opts.discovery.authorization_endpoint      which is equivalent of auth_url

But api_url is a bit puzzling. Does opts.discovery.token_endpoint_auth_methods_supported equate to this?
Or should I just use ```discovery = "https://<server>/idp/userinfo.openid"``` and not bother with the others?

I know this is hard to answer without knowing what the server information is providing. According to my Ping documentation their grafana setup doesnt seem to match that config. So its perplexing. Any suggestions/ideas would be greatly appreciated. 

Im sorry if this is the wrong place for this question - remove it, if it is.

**Comment by bodewig** [comment]
I'm pretty sure Ping Federate supports OpenID Connect discovery, but I've never used it myself. You can grab the `iss` claim from an ID Token it has issued, strip the trailing slash if present and add /.well-known/openid-configuration to try, see https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

As for `api_url` the URI looks as if it was the one of the userinfo endpoint, so the key would be `opts.discovery.userinfo_endpoint`

**Comment by dlannan-fmad** [comment]
Thanks very much. You are right it does look more like a userinfo_endpoint.
Hopefully we will be getting some more data on the server soon so we can trial this. Really appreciate the help.

**Comment by dlannan-fmad** [comment]
An update to a working version using a test system with keycloak.
Note: pass config into the authenticate call for openidc.
```
    config = {}
    config.redirect_uri_path = "/redirect_url"
    -- discovery = AUTH_SERVER_HOST.."/.well-known/openid-configuration"
    config.client_id = "<client_id>"
    config.client_secret = "<client_secret>"
    config.ssl_verify = "no"
    config.scope = "openid email profile"
    config.redirect_uri_scheme = "https"

    config.discovery = {}
    config.discovery.issuer = AUTH_SERVER_HOST.."/auth/realms/myrealm"
    config.discovery.jwks_uri = AUTH_SERVER_HOST.."/auth/realms/myrealm/protocol/openid-connect/certs"

    config.discovery.userinfo_endpoint = AUTH_SERVER_HOST.."/auth/realms/myrealm/protocol/openid-connect/userinfo"
    config.discovery.end_session_endpoint = AUTH_SERVER_HOST.."/auth/realms/myrealm/protocol/openid-connect/logout"
    config.discovery.token_endpoint = AUTH_SERVER_HOST.."/auth/realms/myrealm/protocol/openid-connect/token"
    config.discovery.authorization_endpoint = AUTH_SERVER_HOST.."/auth/realms/myrealm/protocol/openid-connect/auth"
    config.discovery.revocation_endpoint = AUTH_SERVER_HOST.."/auth/realms/myrealm/protocol/openid-connect/revoke"

    local authmethods = {}
    authmethods[0] = "private_key_jwt"
    authmethods[1] = "client_secret_basic"
    authmethods[2] = "client_secret_post"
    authmethods[3] = "tls_client_auth"
    authmethods[4] = "client_secret_jwt"
    
    config.discovery.token_endpoint_auth_methods_supported = authmethods
```
Thanks for such an awesome product. Really appreciate it.

**Comment by dlannan-fmad** [comment]
Our customer changed to using discovery. So, these problems have been solved. I think its pretty awesome you can still use standard endpoints with openidc. Thanks for the assist @bodewig.
