### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by KwadwoObeng** [zmartzone/lua-resty-openidc#377]
I used instructions from the documentaion; https://support.gluu.org/single-sign-on/9347/gluu-lua-resty-openidc-internal-server-error/ but when I try acessing the nginx proxy i get an Internal Server Error.This is from my logs

2021/01/27 13:44:20 [error] 15143#0: *6 lua entry thread aborted: runtime error: access_by_lua(nginx.conf:54):14: module 'resty.openidc' not found: no field package.preload['resty.openidc'] no file '/usr/local/openresty/resty/openidc.lua' no file '/usr/local/openresty/site/lualib/resty/openidc.ljbc' no file '/usr/local/openresty/site/lualib/resty/openidc/init.ljbc' no file '/usr/local/openresty/lualib/resty/openidc.ljbc' no file '/usr/local/openresty/lualib/resty/openidc/init.ljbc' no file '/usr/local/openresty/site/lualib/resty/openidc.lua' no file '/usr/local/openresty/site/lualib/resty/openidc/init.lua' no file '/usr/local/openresty/lualib/resty/openidc.lua' no file '/usr/local/openresty/lualib/resty/openidc/init.lua' no file './resty/openidc.lua' no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/openidc.lua' no file '/usr/local/share/lua/5.1/resty/openidc.lua' no file '/usr/local/share/lua/5.1/resty/openidc/init.lua' no file '/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua' no file '/usr/local/openresty/luajit/share/lua/5.1/resty/openidc/init.lua' no file '/usr/local/openresty/site/lualib/resty/openidc.so' no file '/usr/local/openresty/lualib/resty/openidc.so' no file './resty/openidc.so' no file '/usr/local/lib/lua/5.1/resty/openidc.so' no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/openidc.so' no file '/usr/local/lib/lua/5.1/loadall.so' no file '/usr/local/openresty/site/lualib/resty.so' no file '/usr/local/openresty/lualib/resty.so' no file './resty.so' no file '/usr/local/lib/lua/5.1/resty.so' no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so' no file '/usr/local/lib/lua/5.1/loadall.so' stack traceback:

**Comment by bodewig** [comment]
module 'resty.openidc' not found

means you either haven't installed lua-resty-openidc at all or the Lua sytems running inside nginx doesn't find it because it is looking for it in a different place than you have placed it.

The log message says where Lua has searched for it, you'll need to compare this with where your Lua file is. You may need to configure `lua_package_path` correctly or check permissions (nginx may be unable to read the file) or just make sure the library really is where you expect it to be.

**Comment by KwadwoObeng** [comment]
Yeahh the lua-resty-openidc wasn't installed.I just did and it works like a charm.Thank You
