### ISSUE TITLE
Failed to Load inline lua code

### ISSUE THREAD

**Issue by KwadwoObeng** [zmartzone/lua-resty-openidc#378]
I am trying to configure openidc on top of an already existing nginx reverse proxy. I followed instructions from
https://medium.com/@technospace/nginx-as-an-openid-connect-rp-with-wso2-identity-server-part-2-492ab6bf5cc9
but I get this error when I try to access the page
 failed to load inlined Lua code: access_by_lua(nginx.conf:102):12: unexpected symbol near '▒'

**Comment by bodewig** [comment]
Please don't expect us to follow random installation instructions of others. This is not really a question about lua-resty-openidc.

You should have a look at your nginx.conf file, there seems to be some kind of illegal character. Possibly some kind of encoding or transfer error when you've created the config file on a different machine.

**Comment by KwadwoObeng** [comment]
Yeahh there were some mistakes in my nginx.conf file.Issue has been resolved Thanks
