### ISSUE TITLE
Enable clients to us Basic-Auth

### ISSUE THREAD

**Issue by rfx77** [zmartzone/lua-resty-openidc#379]
is it possible to configure this library so that a client can use a simple curl command like:

`curl -u user:pass http://secure.test.com/ `

to access the service without getting redirected?

like the enable-basic-auth in the keycloak java-adaper

**Comment by bodewig** [comment]
I'm not familiar with the keycloak java-adapter, so I'm not sure what it does.

This module is exclusively about the OAuth2 authorization code grant flow. For basic auth you'd use a different module: https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html
