### ISSUE TITLE
Keycloak integration is failing with a stacktrace/error

### ISSUE THREAD

**Issue by jeblackburn** [zmartzone/lua-resty-openidc#382]
Hello,

I can't complete the authentication cycle with OpenResty + this library + Keycloak. I'm getting a stacktrace in the nginx server logs and a 500 server error to the browser. 

The exception looks like this:

2021/03/10 12:13:57 [error] 68433#5010831: *1 lua entry thread aborted: runtime error: ...ellar/openresty/1.19.3.1_1/site/lualib/resty/openidc.lua:309: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'find'
	...ellar/openresty/1.19.3.1_1/site/lualib/resty/openidc.lua:309: in function 'openidc_combine_uri'
	...ellar/openresty/1.19.3.1_1/site/lualib/resty/openidc.lua:382: in function 'openidc_authorize'
	...ellar/openresty/1.19.3.1_1/site/lualib/resty/openidc.lua:1478: in function 'authenticate'
	access_by_lua(nginx.conf:83):23: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8090"

Any thoughts?  Thanks.

###### Environment

openresty/1.19.3.1_1

cdbattags/lua-resty-jwt                                      0.2.0
openresty/lua-resty-string                                   0.11
zmartzone/lua-resty-openidc                                  1.7.4
jkeys089/lua-resty-hmac                                      0.05
ledgetech/lua-resty-http                                     0.14
bungle/lua-resty-session                                     3.8

Provider: Keycloak.

All running locally on my Mac.

###### Expected behaviour
Redirect to my localhost instance of Keycloak

###### Actual behaviour
The stacktrace above.

###### Minimized example

Keycloak realm export:
[realm-export (2).json.txt](https://github.com/zmartzone/lua-resty-openidc/files/6119122/realm-export.2.json.txt)

Nginx config:
        location / {
            root   html;
            index  index.html index.htm;
            access_by_lua_block {
                local opts = {
                    redirect_uri = "http://localhost:8090/redirect_uri",
                    -- had to use the loopback ip bc openresty couldn't resolve the keycloak at localhost
                    discovery = "http://127.0.0.1:10000/auth/realms/sandbox-realm",
                    token_endpoint_auth_method = "client_secret_basic",
                    client_id = "openresty",
                    client_secret = "f3658688-e28b-460f-8b66-9f33e70f07e6"
                }
                local res, err = require("resty.openidc").authenticate(opts)
                if err then
                    ngx.status = 500
                    ngx.say(err)
                    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                end
            }
        }

###### Configuration and NGINX server log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by bodewig** [comment]
I can't see any stacktrace.

**Comment by jeblackburn** [comment]
Sorry @bodewig, the stacktrace got commented out somehow. Weird.

**Comment by jeblackburn** [comment]
Bah, found the configuration error. The discovery URL in our nginx.conf file was incomplete. 

`discovery = "http://127.0.0.1:10000/auth/realms/sandbox-realm"`

should have been
`discovery = "http://127.0.0.1:10000/auth/realms/sandbox-realm/.well-known/openid-configuration"`
