### ISSUE TITLE
How to get authentication working with ping federated

### ISSUE THREAD

**Issue by Joe-joe67** [zmartzone/lua-resty-openidc#383]
Hi,
I apologize if I am not posting this on the right section. But not sure where to get help.
I have installed openresty on a ubuntu machine. My objective is to setup a reverse proxy that perform authentication for users agains  ping federate. I have used the Sample Configuration for Google+ Signin provided on the website. I am able to reach the proxy, authenticate on the idp and then I receive a code with a status from the idp. Then I am stuck. I am not sure how to verify that the code is a valide code and then allow user to access the backedn site.

Can you pls guide me ? Any help would be much appreciated.

My configuration is :

events {
  worker_connections 128;
}

http {

  lua_package_path '~/lua/?.lua;;';

  resolver 127.0.0.53;

  lua_ssl_trusted_certificate /usr/local/openresty/nginx/certi.pem;
  lua_ssl_verify_depth 5;

  # cache for validation results
  lua_shared_dict introspection 10m;

  server {
    
    listen 443 ssl;
    server_name XXXXX;
    
    set $session_secret XXXX;
    set $session_name nginx_session;

    ssl_certificate           /usr/local/openresty/nginx/cert.crt;
    ssl_certificate_key       /usr/local/openresty/nginx/cert.key;
    ssl_password_file /usr/local/openresty/nginx/ssl_passwords.txt;
    
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /usr/local/openresty/nginx/logs/my.access.log;
    
  
    
    location / {

    access_by_lua_block {
          local opts = {            
             redirect_uri = "https://myserver.com/mysite", 
             discovery = "https://XXXXX/.well-known/openid-configuration",           
             client_id = "XXXX",
             client_secret = "XXXXXX",   
            ssl_verify = "no"
          }
         
          -- call authenticate for OpenID Connect user authentication
          local res, err = require("resty.openidc").authenticate(opts)

         if err then
           ngx.status = 500
           ngx.say(err)
           ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
         end

         
        ngx.req.set_header("X-USER", res.id_token.sub)
      }
      
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      
      proxy_pass          https://XXXXX;
      proxy_read_timeout  90;
     
      
    }
  }
}

**Comment by bodewig** [comment]
I'm not sure I understand your question. What does you receive the code mean? lua-resty-openidc is supposed to handle the redirect uri itself, it will receive the code and exchange it for a token and if it succeeds with all of these steps will exit `authenticate` without an error - in which case you can forward the request to your backend.
