### ISSUE TITLE
Cannot get id_token from RP.

### ISSUE THREAD

**Issue by kpsuri7** [zmartzone/lua-resty-openidc#387]
I am new to nginx + openidc + lua-resty. I tried an initial set up as suggested in https://github.com/zmartzone/lua-resty-openidc and trying to use one of lifecycle hooks to get user id (in id_token) after authentication from OP and do a separate authorization. However, I cannot get past the first step to set user id in ngx request header. i.e.

ngx.req.set_header("X-USER", res.id_token.sub)

Everytime I try the URL authentication happens and it get redirected appropriately. However, I do not see any user id info. I never get any session.data set in openidc.authenticate method.

###### Environment

- lua-resty-openidc version (e.g. 1.7.4-1)
- OpenID Connect provider (Inhouse OP)

###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*

###### Configuration and NGINX server log files
*Config and logs for the minimized example, possibly provided as attachments.*
[auth.lua.txt](https://github.com/zmartzone/lua-resty-openidc/files/6594838/auth.lua.txt)
[nginx.conf.txt](https://github.com/zmartzone/lua-resty-openidc/files/6594840/nginx.conf.txt)

Following debug logs in error.log keep repeating:

2021/06/03 23:31:06 [debug] 14#14: *1 [lua] openidc.lua:1446: authenticate(): session.present=true, session.data.id_token=false, session.data.authenticated=nil, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=true, try_to_renew=true, token_expired=false
2021/06/03 23:31:06 [debug] 14#14: *1 [lua] openidc.lua:553: openidc_discover(): openidc_discover: URL is: https://111.22.33.444/mmm/sss/oauth/oauth20/metadata/PPPOIDC/.well-known/openid-configuration
2021/06/03 23:31:06 [debug] 14#14: *1 [lua] openidc.lua:115: openidc_cache_get(): cache hit: type=discovery key=https://111.22.33.444/mmm/sss/oauth/oauth20/metadata/PPPOIDC/.well-known/openid-configuration
2021/06/03 23:31:06 [debug] 14#14: *1 [lua] openidc.lua:688: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_basic
2021/06/03 23:31:06 [debug] 14#14: *1 [lua] openidc.lua:1477: authenticate(): Authentication is required - Redirecting to OP Authorization endpoint

**Comment by bodewig** [comment]
The log ends before the authentication code is returned from the OP and thus before your code has even had a chance to run.

**Comment by kpsuri7** [comment]
[error.log](https://github.com/zmartzone/lua-resty-openidc/files/6600425/error.log)

**Comment by kpsuri7** [comment]
Thanks for your immediate reply. First of all, are nginx.conf and auth.lua file correctly configured? Above is the error.log I regenerated. FYI, I added some custom logs in openidc.lua file to see what is going on.

**Comment by bodewig** [comment]
we never see when your OP redirect back to your redirect_uri. Are you sure your redirect_uri is set up correctly, where correctly means it targets a location that lua-resty-openidc intercepts?

Sorry for asking this obvious question but a common theme with questions lately have been people who didn't understand what the OpenID Connect redirect_uri would do and assumed it should be part of their application rather than something completely and solely controlled by lua-resty-openidc.

**Comment by kpsuri7** [comment]
Yes sir! The redirect_uri is set up correctly as far as I know. I do appropriately redirected to my application after authentication except I do not get any user info. "res" seems to be nil? I say it is appropriately setup for one I see my app frontend with state and code as query params. Second, in the error.log I attached above, on line 95, you can see the state & redirect_uri ending in 11932.

However, I do have a question regarding redirect_uri. The one that was setup with OP ends with port number 11932. The application URL that we get redirected to after the authentication has a trailing "/" and then the query params: state and code. 

Sorry but I dont understand why we keep getting into this ( https://github.com/zmartzone/lua-resty-openidc/blob/59d01573d7d8eeed4cd60666af1cdc90ff8be80b/lib/resty/openidc.lua#L1458 ) if block every time. I wanted to investigate this and I added those custom logs. It seems to me that session.data.authenticated is never set to true except in function: openidc_authorization_response ( https://github.com/zmartzone/lua-resty-openidc/blob/59d01573d7d8eeed4cd60666af1cdc90ff8be80b/lib/resty/openidc.lua#L1415 ). Also, session.data.id_token is checked ( https://github.com/zmartzone/lua-resty-openidc/blob/59d01573d7d8eeed4cd60666af1cdc90ff8be80b/lib/resty/openidc.lua#L1459)..not sure where it is set or retrieved.

**Comment by bodewig** [comment]
At least your log never shows lua-resty-openidc was handling the state and code, You should find this log https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1407 once it start doing so.

To me it looks as if lua-resty-openidc doesn't recognize the redirect_uri is currently navigated, this can very well be the case if the local path is different from the public path and lua.resty-openidc doesn't see any of the `X-Forwarded` headers that would help it to properly "find itself".

`session.data.authenticated` is only set to true if lua-resty-openidc has handled the code and obtained a token from the OP. According to your log this never happens.

**Comment by kpsuri7** [comment]
Alright sir! Let me quickly check with OP team once and will get back to you. Appreciate your quick response. Cheers!

**Comment by kpsuri7** [comment]
Ok Stefan. I created a local WS02 Identity server..added in the redirect URL (https://yyyy-xxxx.zzzz.ssss.ccc.ooo.mmm:11932/). Updated my auth.lua to use the same with trailing / at the end. I think I get to the line 1407 you suggested. However, see an error.


error.log below:
2021/06/04 22:41:31 [debug] 12#12: *1 [lua] openidc.lua:1400: authenticate(): kpsuri7 added: session is:{}
2021/06/04 22:41:31 [debug] 12#12: *1 [lua] openidc.lua:1402: authenticate(): kpsuri7 added: target_url:/
2021/06/04 22:41:31 [debug] 12#12: *1 [lua] openidc.lua:1407: authenticate(): kpsuri7 added: path in openidc.authenticate:/
2021/06/04 22:41:31 [debug] 12#12: *1 [lua] openidc.lua:1408: authenticate(): kpsuri7 added: openidc_get_redirect_uri_path(opts) in openidc.authenticate:/
**2021/06/04 22:41:31 [debug] 12#12: *1 [lua] openidc.lua:1410: authenticate(): Redirect URI path (/) is currently navigated -> Processing authorization response coming from OP**
2021/06/04 22:41:31 [error] 12#12: *1 [lua] openidc.lua:1414: authenticate(): request to the redirect_uri path but there's no session state found, client: 444.55.66.777, server: yyyy-xxxx.zzzz.ssss.ccc.ooo.mmm, request: "GET / HTTP/1.1", host: "yyyy-xxxx.zzzz.ssss.ccc.ooo.mmm:11934"
2021/06/04 22:41:31 [error] 12#12: *1 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/main.lua:20: attempt to index local 'res' (a nil value)

**Comment by bodewig** [comment]
> request to the redirect_uri path but there's no session state found

in most cases means the browser didn't send the session cookie back. Can observe the authorization flow with your browser's developers tools and see whether it sends back a cookie when invoking the redirect_uri?

If your OP and your server are in different domains your cookies are cross-site cookies when the browser is redirected back to the return_uri and the Cookie's `SameSite` value becomes important. I believe the default setting of lua-resty-session is to set it to `Lax` which is good enough for most browsers. You could try to set it to `None` to see whether this changes anything for the one you are using.

```
set $session_cookie_samesite   None;
```

in nginx.conf. See https://github.com/bungle/lua-resty-session#nginx-configuration-variables

Be aware that `None` could cause problems with old browser versions, though.

It is probably best to analyze what is going on with the developer tools as the console there may already explain why the browser decides to not send a cookie.
