### ISSUE TITLE
request to the redirect_uri path but there's no session state found 

### ISSUE THREAD

**Issue by Chinnuganga** [zmartzone/lua-resty-openidc#388]
Facing the same error while using using openidc-resty to add authentication to an application. The integration works fine when accessed directly through browser.

Now we are looking for SSO while login from Application 1 which is keycloak integrated.
We are trying to load the application2 through an iframe from application1.
The application 2 is integrated with openidc-resty to achieve integration with keycloak.

Now, when we local application2 in an iframe within application1, we are facing the following error

"There was an error while logging in: request to the redirect_uri_path but there's no session state found"

Also we could see some of the keycloak cookies are blocked by browser with the following error

"Set-Cookie didn't specify a "Same-Site" attribute and was defaulted to "Same-Site=Lax", and was blocked because it came from a cross-site response"

The following Keycloak cookies were blocked by this error

KC_RESTART
KEYCLOAK_IDENTITY_LEGACY
KEYCLOAK_SESSION_LEGACY
KEYCLOAK_REMEMBER_ME

Can someone please suggest a solution to this issue?

**Comment by bodewig** [comment]
https://github.com/zmartzone/lua-resty-openidc/issues/338#issuecomment-855426638

Please don't hijack unrelated tickets but rather open new ones. In this particular case it is not a lua-resty-openidc but a Keycloak question, so please use Keycloak's channels to ask over there.

**Comment by Chinnuganga** [comment]
@bodewig i will close this issue.
