### ISSUE TITLE
How to write access token to a cookie ?

### ISSUE THREAD

**Issue by omasseau** [zmartzone/lua-resty-openidc#389]
###### Environment

- lua-resty-openidc 1.7.4
- Keycloak

###### Expected behaviour
I would like to write the access token to a cookie so that my application (Angular application) can read it.

###### Actual behaviour
I only get a session and a session_2 cookies

I am able to set the access_token in an Authorization header by doing this : 
```
local result, err = require("resty.openidc").authenticate(opts)
ngx.req.set_header("Authorization", "Bearer " .. result.access_token)
```

The problem is that an Angular application cannot read the request headers, So I would like to create a cookie (access_token) with the value of the access_token.

I have already tried this : 
```
local result, err = require("resty.openidc").authenticate(opts)
ngx.req.set_header("Set-Cookie", "access_token=" .. result.access_token .. "; path=/")
```

But when I am redirected to my application I do not have any access_token cookie set.
I only see the session and session_2 cookies.

Is there maybe a way to get the access_token value from one of these 2 cookies ? Is yes, how do I decode them ?

**Comment by bodewig** [comment]
you are setting the `Set-Cookie` header as part of your client request and not sending it back to the browser (`ngx.req` vs ngx.resp`). But even if you set it on the response the very first request to your target would be handeled before the Cookie was set.

You can achieve what you want with an `on_authenticated` lifecycle function which would be able to add the cookie to the response sent back to the browser when the browser is redirected back to the original URL it asked for.
