### ISSUE TITLE
Can't access proxy pass 

### ISSUE THREAD

**Issue by mjordanovski** [zmartzone/lua-resty-openidc#390]
I started configuring nginx for the first time, have very little experience, and I have a question:

In the sample nginx.conf configuration for authenticating users against Google+ Signin, at the bottom there is proxy_pass http://localhost:80; 

But I'm never redirected to localhost:80 because I first need to specify discovery  and redirect_uri inside opts, and after successful authentication with Google I'm redirected to the redirect_uri and not to my http://localhost:80 .

So question is: How to access proxy_pass and not be redirected to the redirect_uri ?

My config:
```
 location /validateapp1{
      access_by_lua_block {

          local opts = {
             ssl_verify = "no",

             discovery = "https://accounts.google.com/.well-known/openid-configuration",
             client_id = "<my-client-id>",
             client_secret = "<my-client-secret>",
             redirect_uri = "https://my-public-url/application1"
           }        
             local res, err = require("resty.openidc").authenticate(opts)

             if err then
               ngx.status = 500
               ngx.say(err)
               ngx.exit(ngx.HTTP_FORBIDDEN)
             end
             ngx.req.set_header("X-USER", res.id_token.sub)
      }
       proxy_pass http://my-kubernetes-service-app1:80;
    }
```

Additional info: I'm running two applications on kubernetes, in the same namespace as nginx controller. I don't want those two apps to be accessible on public url right away, but rather I want to have https://my-public-url/validateapp1 and https://my-public-url/validateapp2 , and inside each of those two locations user will first need to authenticate with google, and then to be able to access applications.

Thank you.

**Comment by bodewig** [comment]
`proxy_pass` means you will never get redirect at all. nginx is acting as a reverse proxy and will make a call to your target URL and forward the response back to the browser. This really is an nginx question and not a lua-resty-openidc question.
