### ISSUE TITLE
no access_token in response after local res, err = require("resty.openidc").authenticate(opts)

### ISSUE THREAD

**Issue by VitoKovacic** [zmartzone/lua-resty-openidc#392]
Hi, 

following this README https://github.com/zmartzone/lua-resty-openidc
-- at this point res is a Lua table with 3 keys:
          --   id_token    : a Lua table with the claims from the id_token (required)
          --   access_token: the access token (optional)
          --   user        : a Lua table with the claims returned from the user info endpoint (optional)
          
 i would like to extract the access_token from the response of this function call
 local res, err = require("resty.openidc").authenticate(opts)
 
 
 But I only get id_token in response 
 
 How to force the access_token to be part of the response?

**Comment by bodewig** [comment]
The access token will only be included if you store it inside of the session, are you setting `session_contents` in any way?
