### ISSUE TITLE
Does openidc support multiple client ids?

### ISSUE THREAD

**Issue by Subbu3992** [zmartzone/lua-resty-openidc#398]
**Scenario:** Configured App1 and App2 with respective client Ids[both different] in a single Kong Instance. User logs into App1 and works for say 3 minutes. Now the user logs into App2, this time the user is not prompted for authentication. User continues to work and when the token is refreshed after 5mins from the login, it fails with errors like scope narrowing, wrong client id, nounce mismatch or nounce is nil etc.

**Error messages from openidc:**

- openidc.lua:1438: authenticate(): lost access token:response indicates failure, status=400, body={"error":"invalid_scope","error_description":"Unable to narrow the scope of the client authentication to [app2.access:read, app.access, openid].","scope":"app.access openid"}
- openidc.lua:1438: authenticate(): lost access token:response indicates failure, status=400, body={"error":"invalid_grant","error_description":"Wrong client for this refresh token: app1"}
- nonce "nil" in id_token is not equal to the nonce that was sent in the request "35f8e53698d08098ad318969cd0063a4"

**Open Questions:**

- If openidc, by default doesn't support multiple client ids, then what customization needs to be done in openidc plugin to make this supported.
- Any other approaches to overcome this.

**Comment by bodewig** [comment]
I don't know much about the way Kong uses lua-resty-openidc. If you are using different locations on the same server with different configurations of lua-resty-openidc (like different clients) then you must ensure they do not share the same session - by using different cookie names and potentially different server side storage configurations.
