### ISSUE TITLE
Successful authentication followed by CORS error after some time

### ISSUE THREAD

**Issue by bjonen** [zmartzone/lua-resty-openidc#403]
Hello everyone, 

We are using lua-resty-openidc behind a corporate OP. Similar to this issue (https://github.com/zmartzone/lua-resty-openidc/issues/381), we succeed in authenticating. We are testing with a minimal react (single-page) application with a simple callback that updates a component every 20 seconds. 
After some time (which seems to vary at least by browser) the site starts to contact the OP again in the background. However this time, the contact ends in a CORS error and the site becomes unresponsive. 

We have tried the authentication against the corporate OP as well as the Azure SSO. Both times we experience the same issue. We have also tried disabling token refresh as much as possible (see config), however with no success. 

In the following you can see the details of our configuration as well as log and browser console errors. 

We do not control the OP side but if needed we can obtain information about the OP. 

Any help is much appreciated! 

###### Environment

- lua-resty-openidc version (e.g. 1.7.4)
- OpenID Connect provider: Internal Corporate OP and Azure AD

###### Expected behaviour
Token refresh should not result in page crashing. 

###### Actual behaviour
Page unresponsive after some random time. 

###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*

Nginx config
---
```
worker_processes auto;
events {
    worker_connections 1024;
}
http {
    ssl_certificate …
    ssl_certificate_key …
    include /usr/local/openresty/nginx/conf/mime.types;
    # cache for discovery metadata documents
    lua_shared_dict discovery 1m;
    #     cache for JWKs
    lua_shared_dict jwks 1m;
    # same dns as /etc/resolv.conf
    resolver ….
    server {
        listen 7098 ssl;
        access_log /mnt/fineng/logging/bonds/credici/access_log;
        access_by_lua_file "/auth.lua";
        location / {
            proxy_pass https://landing:8050/;
            # Fix bad gateway when using auth: https://stackoverflow.com/a/52270770/2146052
            proxy_set_header Host $http_host;
        }
    }
}
```

Auth.lua
------------
```lua
local opts = {
    -- Could be changed to host/redirect_uri
    redirect_uri = "host/login_callback?next=%2F",
    token_endpoint_auth_method = "client_secret_post",
    -- token_endpoint_auth_method = "client_secret_simple",
    -- id_token already includes all claims we need. No need for renewing access token
    renew_access_token_on_expiry = false,
    proxy_opts = {
        http_proxy  = "…",
        https_proxy = "…",
    },
    -- otherwise will need to add SL root certificate
    ssl_verify = "no",
    keepalive = "no",
    refresh_session_interval = nil,
    access_token_expires_leeway = 10,
    session_contents = {id_token=true, access_token=true},
    --renew_access_token_on_expiry = false,
}
local identity_provider_sl = {
    discovery = "…",
    client_id = "…",
    client_secret = "…"
}

print('identity_provider: ', identity_provider['discovery'])
for k, v in pairs(identity_provider) do
    opts[k] = v
end
-- call authenticate for OpenID Connect user authentication
local res, err = require("resty.openidc").authenticate(opts)
if err then
    ngx.status = 500
    ngx.say(err)
    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
end

ngx.req.set_header("X-USER", res.id_token.sub)
ngx.req.set_header("X-USER-NAME", res.id_token.name)
ngx.req.set_header("X-USER-EMIAL", res.id_token.email)
```

dash app (https://dash.plotly.com/)
-----------
```python
import dash
from dash import dcc
from dash import html
from dash import Output, Input
import plotly.express as px
import pandas as pd

from flask import Flask
server = Flask(__name__)

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")


def getapp(server=None):
    app = dash.Dash(name=__name__, server=server)
    app.layout = html.Div(children=[
        html.H1(children='Hello Dash'),

        html.Div(children='''
            Dash: A web application framework for your data.
        '''),

        dcc.Graph(
            id='example-graph',
            figure=fig
        ),
        dcc.Interval(id='token_update_timer', interval=20*1000, n_intervals=0),
        html.Div(id='abc')

    ])
    @app.callback(
        [
            Output('abc', 'children'),
        ],
        [
            Input("token_update_timer", "n_intervals"),
        ],
    )
    def update_options(n_intervals):
        from flask import request
        try:
            headers = request.headers
        except:
            headers = {}
        user = headers.get('X-USER-NAME', 'anonymous')
        return user,



# app needs to be created also when the file is not __main__ when running with uwsgi
app = getapp(server=server)


if __name__ == '__main__':
    ssl_context = get_ssl_context()
    app.run_server(host='0.0.0.0',
                   debug=True,
                   threaded=False,
                   ssl_context=ssl_context)

```

Error_log
------------
```
2021/10/21 09:30:02 [notice] 8#8: *2399 [lua] auth.lua:38: Access/Auth from remote address: …, client: …, server: , request: "POST /…/_dash-update-component HTTP/1.1", host: "…:7098", referrer: "host/app/"
2021/10/21 09:30:02 [notice] 8#8: *2399 [lua] auth.lua:56: identity_provider: OP, client: …, server: , request: "POST /app/_dash-update-component HTTP/1.1", host: "host:7098", referrer: "host:7098/app/"
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:1446: authenticate(): session.present=true, session.data.id_token=false, session.data.authenticated=nil, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=false, try_to_renew=false, token_expired=false
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:553: openidc_discover(): openidc_discover: URL is: OP
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:115: openidc_cache_get(): cache hit: type=discovery key=OP
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:658: openidc_get_token_auth_method(): 1 => client_secret_post
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:660: openidc_get_token_auth_method(): configured value for token_endpoint_auth_method (client_secret_post) found in token_endpoint_auth_methods_supported in metadata
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:688: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_post
2021/10/21 09:30:02 [debug] 8#8: *2399 [lua] openidc.lua:1477: authenticate(): Authentication is required - Redirecting to OP Authorization endpoint
2021/10/21 09:30:07 [notice] 8#8: *2400 [lua] auth.lua:38: Access/Auth from remote address: …, client: …, server: , request: "GET /login_callback?next=%2F HTTP/1.1", host: "host:7098"
2021/10/21 09:30:07 [notice] 8#8: *2400 [lua] auth.lua:56: identity_provider: OP, client: …, server: , request: "GET /login_callback?next=%2F HTTP/1.1", host: "host:7098"
2021/10/21 09:30:07 [debug] 8#8: *2400 [lua] openidc.lua:1406: authenticate(): Redirect URI path (/login_callback) is currently navigated -> Processing authorization response coming from OP
2021/10/21 09:30:07 [error] 8#8: *2400 [lua] openidc.lua:1410: authenticate(): request to the redirect_uri path but there's no session state found, client: …, server: , request: "GET /login_callback?next=%2F HTTP/1.1", host: "host"
```

browser errors
----------------
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at Oredirect_uri=host%3A7098%2Flogin_callback%3Fnext%3D%252F&nonce=...&state=...&response_type=code&client_id=...&scope=openid%20email%20profile. (Reason: CORS request did not succeed).

XHR OPTIONS OP?redirect_uri=host/login_callback?next=%2F&nonce=...&state=...&response_type=code&client_id=...&scope=openid email profile
CORS Missing Allow Origin
```

**Comment by bjonen** [comment]
Thanks a lot for summarizing the problem with SPAs and CORS. I investigated a bit and now I believe I understand your proposed solution (paragraph 2). Unfortunately the library we are using (`dash`) does not allow us to catch a 401 response on AJAX calls. So "catching" API requests inside the lua block and returning 401 will not work for us at this time. 

For the  moment a reasonable workaround for us is to extend the session lifetime. We have done this via `set $session_cookie_lifetime 2147483648;` (see below). This works well as long as we have only one nginx worker process. However, as soon as we switch to 2+ worker_processes, the session drops after some time (~20 minutes). 

Do you have any idea why this might be happening, or how the session is related to the # of worker processes in nginx?  

Many thanks for your help on this!

```nginx
worker_processes 1;
pid /run/nginx.pid;
events {
    worker_connections 1024;
}
http {
    ssl_certificate …;
    ssl_certificate_key …;
    ssl_session_cache shared:SSL:100m;
    ssl_session_timeout 1440m;
    ssl_session_tickets off;
    lua_ssl_trusted_certificate …;
    lua_ssl_verify_depth 10;

    include /usr/local/openresty/nginx/conf/mime.types;
    # cache for discovery metadata documents
    lua_shared_dict discovery 1m;
    #     cache for JWKs
    lua_shared_dict jwks 1m;
    

    resolver …;
    server {
        listen 7098 ssl;
        set $session_name auth_cookie_7098;
        set $session_cookie_lifetime 2147483648;
        set $session_cookie_renew 10;
        set $session_check_ssi off;
        set $session_storage cookies;

        location /hello {
            proxy_pass https://hello_dash:8050;
            proxy_set_header Host $http_host;
        }
	   # … several other locations
    }
}
```

**Comment by bodewig** [comment]
you are using Cookies to store the session content (which is where lua-resty-opeindc stores the tokens, for example). This cookie is encrypted and if you don't provide an encryption key to lua-resty-session explicitly then it will generate a new one every time the nginx process starts. I'm not quite sure whether lua-resty-session does anything to ensure worker processes that belong to the same server share the same secret, but what you see could be easily explained by switching workers and the next worker is unable to decrypt your session cookie.

I'd first try to explicitly configure `$session_secret` (see lua-resty-session's docs for details as the secret needs to be in a specific format).

**Comment by UberMeatShield** [comment]
First off thanks for doing so much of the heavy lifting on this SSO; it is not simple in an already complex web ecosystem.  I think my group is running into the same issue after porting a very heavy ajax single page app to using Azure + openidc (full cross domain using microsoft services directly).  Login works initially but then eventually the token needs a renewal and everything will blow up till a full page reload actually refreshes the token without a CORs error.

The app already has some cors calls so my hypothesis for fixing this in a sort of hacky way is to have a periodic status api created and behind azure.   

/check_azure => poll every 60 seconds, enable credentials in the ajax call, make the ajax call CORs enabled 

Does this seem like a viable pattern for a very heavy ajax enabled app or is the only way really going to be offline token renewal (we unfortunately do have admin rights on the azure side and have to request changes).   If so are there any examples of a friendly ajax handler for flask or purely in lua to do something like that?

**Comment by bodewig** [comment]
A team I've worked with has used a similar approach to what you describe @UberMeatShield - at least IIUC. When they got a 4xy for their "heartbeat" they knew a full page reload was the only thing that would bring back sanity.

SPAs combined with expiring tokens are bound to cause race-conditions. Some of them can be avoided by having the server obtain new tokens using a refresh token, some can be made less frequent by prolonging the token lifetime - and some cases are easier to handle with a server-side session storage. But in my experience, you never get rid of all strange situations if your application fires requests left and right in erratic patterns.

**Comment by bjonen** [comment]
@bodewig Thanks a lot, your comment was spot on. The setup described above is now working with dash/react. From my side the ticket can be closed.

**Comment by bodewig** [comment]
glad it worked
