### ISSUE TITLE
validation breaks if x5c array is empty

### ISSUE THREAD

**Issue by jluinstra-figure** [zmartzone/lua-resty-openidc#406]
https://github.com/zmartzone/lua-resty-openidc/blob/8c75bc1fec534a7e6f0412ec27ba37063b330dfe/lib/resty/openidc.lua#L917

Could we get `and #jwk.x5c > 0` added here? Token validation breaks if the array is empty and it's referenced as a TODO in two spots.
It doesn't look like public contributions are enabled on this repo..

**Comment by bodewig** [comment]
My interpretation of RFC 7517 is the x5c array must contain at least one element for the JWKS to be valid. The claim itself is optional but to me an empty array is different from a claim not being present. I'd recommend you contact your vendor.

At least I don't recall putting in the TODOs. :-)

Of course we could make the parser more lenient, issue a warning here and treat the JWK as if the x5c claim was missing.

Not sure what you mean with "public contributions enabled". Obviously it is possible to create issues and pull requests are supported as well. Is there anything specific you are missing?

**Comment by bodewig** [comment]
fixed in master branch
