### ISSUE TITLE
Content of table res after authentication

### ISSUE THREAD

**Issue by xamadev** [zmartzone/lua-resty-openidc#408]
Hi, I'm trying to forward all headers sent by OIDC provider. Therefore I'm trying to determine the content of `res`:
`local res, err = require("resty.openidc").authenticate(opts)`

The OIDC provider sends a lot of headers which are also non standard and I just like to forward everthing to the client. I know the folowing piece of code but can't find any documentation about the structure of res. Neither could I print the whole table to the logs for determining the structure.
`      ngx.req.set_header("X-USER", res.id_token.sub)`

**How to just forward any header sent by OIDC provider?** 

Another question about the documentation:

> It maintains sessions for authenticated users by leveraging lua-resty-session thus offering a configurable choice between storing the session state in a client-side browser cookie or use in of the server-side storage mechanisms shared-memory|memcache|redis.

**How to setup storing the session state in cookies? Can't find any documentation about it either.**

Thanks for your help.

**Comment by bodewig** [comment]
I'm afraid I don't understand under what circumstances you expect the OpenID Connect Provider to provide additional headers at all. The only point during the authorization code grant flow nginx and your OIDC provider are talking with each other is after ther OIDC redirect_uri has been navigated by the browser and lua-resty-openidc invokes the token endpoint. The provider may send some HTTP-headers in its response but most of them are ignored. After that lua-resty-openidc redirects the browser to the URL it tried to reach before the auth flow started. `authenticate` doesn't return for the request that triggers the token endpoint invocation.

When I look at your example of

```
ngx.req.set_header("X-USER", res.id_token.sub)
```

I see you are not talking about headers at all. `id_token` is the id token issued by your OIDC provider - and it will be null unless you store it inside the session. The id token is a a Lua table and its structure mirrors that of the OpenID Connect id token - see https://openid.net/specs/openid-connect-core-1_0.html#IDToken

The `res` structure itself is documented inside the README:

```
          -- at this point res is a Lua table with 3 keys:
          --   id_token    : a Lua table with the claims from the id_token (required)
          --   access_token: the access token (optional)
          --   user        : a Lua table with the claims returned from the user info endpoint (optional)
```

For documentation about lua-resty-session please see https://github.com/bungle/lua-resty-session
