### ISSUE TITLE
Possible to configure skew time?

### ISSUE THREAD

**Issue by klodoma** [zmartzone/lua-resty-openidc#410]
Hi, 

This is a question rather than an issue. 

We use https://github.com/zmartzone/lua-resty-openidc to verify an Auth0 Token by this code. 
```
        access_by_lua '

          local opts = {
            discovery = "https://foo.bar.auth0.com/.well-known/openid-configuration",
            auth_accept_token_as = "cookie:Bearer-token"
          }

          -- call bearer_jwt_verify for OAuth 2.0 JWT validation
          local res, err = require("resty.openidc").bearer_jwt_verify(opts)
```

This is running in a docker container on azure Container Instances. It is working. 

We have the issue, that for some reason the Azure Container Time gets out of sync and then we get invalid authentications or tokens released in the "future". It is very difficult to reproduce. 
With other services we were able to add a "skew" time to work around this issue, and I was wondering if it's possible to add also here a "skew time". 

For example:
https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt.html#configuring-jwt-mode, see 
```
 "allowed_skew": "<optional-number-of-seconds-in-integer>",
```

We appreciate any help/input.

**Comment by bodewig** [comment]
`bearer_jwt_verify` accepts optional arguments after `opts` that are "claim specs" as defined by [lua-resty-jwt](https://github.com/cdbattags/lua-resty-jwt). If you leave them off (which you do) the default of checking `exp` and `nbf` applies and lua-resty-openidc sets the ["system leeway"](https://github.com/cdbattags/lua-resty-jwt#validatorsset_system_leewayleeway) to `opts.iat_slack` which defaults to 120 seconds.

So the short answer probably is "you are looking for `opts.iat_slack` which is the acceptable skew in seconds.

**Comment by klodoma** [comment]
Thank you for the clarification. 

I will check this again on our side, actually if its 120 seconds by default that should be enough. 
I'll close this for the moment.
