### ISSUE TITLE
[BUG] OIDC with TLS 1.3 not working, ssl handshake failed

### ISSUE THREAD

**Issue by flo-mic** [zmartzone/lua-resty-openidc#411]
###### Environment

- lua-resty-openidc version: master Branch of Repo
- OpenID Connect provider: Keycloak

###### Expected behaviour

When disabling old TLS < 1.3 and SSL versions on nginx the openid connect module should be able to connect via TLS 1.3 to keycloak. Please not that an OIDC conenction from e.g. Gitea is still working even if I force TLS 1.3 on nginx for the app and keycloak itself. But connecting with this nginx module is not more working. Do I miss any setting or is this module just not prepared for TLS 1.3?

###### Actual behaviour

The connection is refused due to SSL handshake error. I get the following details in the nginx log:

```
2021/12/08 11:13:04 [error] 6067#6067: *68 SSL_do_handshake() failed (SSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:SSL alert number 70), client: 192.168.178.26, server: app.example.com, request: "GET / HTTP/2.0", host: "app.example.com"
2021/12/08 11:13:04 [error] 6067#6067: *68 [lua] openidc.lua:577: openidc_discover(): accessing discovery url (https://keycloak.example.com/auth/realms/example.com/.well-known/openid-configuration) failed: handshake failed, client: 192.168.178.26, server: app.example.com, request: "GET / HTTP/2.0", host: "app.example.com"
```

**Comment by bodewig** [comment]
lua-resty-openidc uses OpenSSL supported crypt stack provided by your Lua environment. The call is made via [lua-resty-http](https://github.com/ledgetech/lua-resty-http) - it is quite possible you need to ensure your OpenResty stack and OS are ready for TLS 1.3. lua-resty-openidc doesn't do anything explicitly to configure the TLS stack.
