### ISSUE TITLE
Make it possible to store a summary of id_token in session?

### ISSUE THREAD

**Issue by alexdowad** [zmartzone/lua-resty-openidc#413]
(If you feel this suggestion is not worth implementing because it will not benefit the majority of users, please close the ticket.)

I have an application which receives a large amount of data in the ID token from the OAuth server. This data is needed on subsequent requests to determine what the user is allowed to do. But the relevant part of the ID token data could really be summarized as a handful of booleans (`user_is_foo`, `user_is_bar`, etc) rather than keeping the whole ID token in the session. If that was possible, the size of the session cookie would shrink vastly.

`lua-resty-openidc` has a nice feature whereby the user can decide whether to retain the ID token in the session or not. This is helpful, but really what is needed in this case is to retain *part* of the ID token data, not all of it.

If you feel this suggested feature is something you would like to include in `lua-resty-openidc`, I can send a PR. I can think of a couple ways to do it:

1) Include user-supplied function in `opts` which takes the ID token (and possibly other inputs) and returns the part which should be retained in the session
2) Include user-supplied function in `opts` which takes the ID token and session, stores whatever it wants in the session, and doesn't return anything

Hope to hear your comments on this.

**Comment by bodewig** [comment]
when `authorize` returns your code gets the id token as well as the session object as part of the response. So you don't really need a hook, you can simply add to the `session` and `save` it.

**Comment by alexdowad** [comment]
Thanks for the quick response!!

Here is what I am still wondering. `lua-resty-openidc` calls `session:save()` internally after it receives the ID token, access token, etc. I believe that `session:save()` will serialize the session and instruct Nginx to send it as a cookie. Now my code modifies `session.data` and calls `session:save()` again, will that not tell Nginx to send a second cookie in the response?

Sorry if I'm not understanding properly how this stuff works.

**Comment by alexdowad** [comment]
Got it, thanks!

**Comment by bodewig** [comment]
you're welcome

**Comment by alexdowad** [comment]
OK, I tried following the suggestion from @bodewig and discovered something interesting. The suggestion didn't work as desired... but it seems the problem is in `lua-resty-session`, not `lua-resty-openidc`.

Opened a PR over there: https://github.com/bungle/lua-resty-session/issues/137

**Comment by alexdowad** [comment]
Hmm, OK, it seems like the kind suggestion from @bodewig really does not work, and here is why...

https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1199-L1203

When `openidc` is processing the redirect back from OAuth, it hits the token endpoint to get the ID token, stores that in the session, saves the session, and... redirects to the originally requested URI. The call to `ngx.redirect` on line 1203 stops processing of Lua code (line 1204 is not executed), so `openidc.authenticate` never returns to its caller, so the calling code does not have the opportunity to modify what is actually stored in the session.

When the browser processes the redirect back to the originally requested URI, and Nginx processes *that* request, we can look at what is in the session and modify it. But by that time, a bunch of chunked cookies have already been set on the client, and modifying the session and saving it does not do anything to remove them.

I'm trying to figure out whether the problem here is `lua-resty-openidc`, or `lua-resty-session`, or both...

**Comment by alexdowad** [comment]
Closed the previous (incorrect) issue on `lua-resty-session` and opened another one with what I now believe is a correct analysis of this problem: https://github.com/bungle/lua-resty-session/issues/138

**Comment by bodewig** [comment]
ah, my fault, sorry. I overlooked (or rather neglected) you explicitly said you did not want to store the id token - in that case it is not there when `authorize` returns. The issue you opened in lua-resty-session is separate one (and an interesting one).

Coming back to this one, the existing lifecycle-hooks could work, if only they received more data. In particular `opts.lifecycle.on_authenticated` is invoked just before the session is saved after the token has been obtained - this would be exactly the point where you could add the information you need. I think we can "simply" add more arguments to `on_authenticated` and pass in the tokens as well and you should get what you need. Before I do so, I'll look through all callbacks to see whether there is any useful context information we could/should add.

**Comment by alexdowad** [comment]
OK, thanks for checking into that!

**Comment by bodewig** [comment]
for the other hooks all context information is already present in the session object, so I only extended `on_authenticated`.

**Comment by alexdowad** [comment]
@bodewig's commit is here: https://github.com/zmartzone/lua-resty-openidc/commit/84629795d18e51f6af2331d05eb54490ab2776f4

Thank you very much for this!

When is it likely to go into a release?

**Comment by bodewig** [comment]
@zandbelt has just created 1.7.5, thank you.
