### ISSUE TITLE
configuration parameter to pass claim to upstream server

### ISSUE THREAD

**Issue by tropas2001** [zmartzone/lua-resty-openidc#417]
I'm trying to figure out how I would configure nginx such one or more of the [userinfo] claims from the OIDC server can be set as headers/passed to upstream servers. 

is this something this code can support?

thanks

Andy

**Comment by bodewig** [comment]
It is not possible to do anything like this by pure configuration, it will always require some Lua code.

The information read from the userinfo endpoint is not available to the code invoking `authenticate` but the id token is - if you store it inside of the session. If the claim you need is present inside of the id token, you can extract it from `authenticate`'s response and create extra headers via nginx's Lua interface.
