### ISSUE TITLE
Impersonate user using his access token

### ISSUE THREAD

**Issue by naelbaw** [zmartzone/lua-resty-openidc#418]
###### Environment

- lua-resty-openidc version: 1.7.5)
- OpenID Connect provider: Keycloak

###### Expected behaviour
Login as the impersonated user 

###### Actual behaviour
Not working

###### Minimized example
I'm trying to authenticate using the implicit flow by sending a request to Keycloak's API to get the access token of the user, then I provide the access token in Authorization header 

###### Configuration and NGINX server log files
```
        -- call authenticate for OpenID Connect user authentication
        local res, err, _target, session = require("resty.openidc").authenticate(opts)

        ngx.log(ngx.INFO, tostring(res))

        ngx.log(ngx.INFO,
        "session.present=", session.present,
        ", session.data.id_token=", session.data.id_token ~= nil,
        ", session.data.authenticated=", session.data.authenticated,
        ", opts.force_reauthorize=", opts.force_reauthorize,
        ", opts.renew_access_token_on_expiry=", opts.renew_access_token_on_expiry,
        ", try_to_renew=", try_to_renew,
        ", token_expired=", token_expired
        )

        if err then
          ngx.log(ngx.ERR, "error: ",err)
          if (err == "state from argument does not match state restored from session") then
            ngx.redirect("https://url")
          else
            -- show the erorr
            --ngx.status = 500
            --ngx.header.content_type = 'text/html';

            --ngx.say("There was an error while logging in: " .. err)
            --ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
            -- or, just redirect
            ngx.redirect("https://url")
          end
        end

        ngx.log(ngx.INFO, "Authentication successful, setting Auth header...")
        ngx.req.set_header("X-USER", session.data.id_token.sub)
        --ngx.req.set_header("Authorization", "Bearer "..session.data.enc_id_token)
        ngx.req.set_header("Authorization", session.data.id_token.sub)
```

**Comment by bodewig** [comment]
`authenticate` is for the OpenID Connect Authorization Code Grant Flow - and only for that.

If you are using a Bearer token, then `bearer_jwt_verify` or `introspect` is for you.

**Comment by naelbaw** [comment]
I used ```introspect``` but in this case I need to provide the access token in every request, but I'm trying to initiate the impersonation in a popup from my application.

here is my full code:
```
if ngx.req.get_headers()["Authorization"] then
        local res, err = require("resty.openidc").introspect(opts)
        if err then
            ngx.status = 403
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
        end
        ngx.req.set_header("X-USER", "")
        ngx.req.set_header("Authorization", "")
else
  -- call authenticate for OpenID Connect user authentication
        local res, err, _target, session = require("resty.openidc").authenticate(opts)

        ngx.log(ngx.INFO, tostring(res))

        ngx.log(ngx.INFO,
        "session.present=", session.present,
        ", session.data.id_token=", session.data.id_token ~= nil,
        ", session.data.authenticated=", session.data.authenticated,
        ", opts.force_reauthorize=", opts.force_reauthorize,
        ", opts.renew_access_token_on_expiry=", opts.renew_access_token_on_expiry,
        ", try_to_renew=", try_to_renew,
        ", token_expired=", token_expired
        )

        if err then
          ngx.log(ngx.ERR, "error: ",err)
          if (err == "state from argument does not match state restored from session") then
            ngx.redirect("https://url")
          else
            -- show the erorr
            --ngx.status = 500
            --ngx.header.content_type = 'text/html';

            --ngx.say("There was an error while logging in: " .. err)
            --ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
            -- or, just redirect
            ngx.redirect("https://url")
          end
        end

        ngx.log(ngx.INFO, "Authentication successful, setting Auth header...")
        ngx.req.set_header("X-USER", session.data.id_token.sub)
        --ngx.req.set_header("Authorization", "Bearer "..session.data.enc_id_token)
        ngx.req.set_header("Authorization", session.data.id_token.sub)
```

I need to start a session and use it for next requests.

**Comment by bodewig** [comment]
There is no built-in support for that in lua.resty-openidc. You can certainly use lua-resty-session from your Lua code directly and set whatever you need after an initial `introspect` call has been successful.

**Comment by naelbaw** [comment]
What does ```authenticate``` put inside session and session_2 cookies? In other words, how can I mimic the behavior that ```authenticate``` does to the session?

**Comment by bodewig** [comment]
The relevant section of code start here: https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1151

You will need to set the `authenticated`, `access_token` and `access_token_expiration` fields and a `refresh_token` if you've got one. You can leave out the other fields, but should ensure lua-resty-openidc know you are not storing other things (like the id_token) inside the session by configuring `opts.session_content`.

Of course once the token expires the whole idea will break down when the token expires as `authenticate` will either try to use the refresh token, which has been issued for a different OAuth2 client and thus will not work or start a new authorization code grant flow via a redirect.

**Comment by bodewig** [comment]
come to think of it, you could probably just set `authenticated` - but if you do that, then you don't really need to use lua-resty-openidc at all :-)

**Comment by naelbaw** [comment]
It works fine now, thanks.

**Comment by mike391** [comment]
> Authorization

Do you have an example? Ive also been trying to get this working

**Comment by mike391** [comment]
> It works fine now, thanks.

Do you have an example? Im also trying to get this working
