### ISSUE TITLE
request to the redirect_uri path but there's no session state found and attempt to index local 'result' (a nil value) in openresty and keycloak

### ISSUE THREAD

**Issue by sanawictco** [zmartzone/lua-resty-openidc#422]
Hi. I'm using lua-resty-openidc in front of protected resources and keycloak as an IDP. I use this config in my Nginx.conf 

access_by_lua '
         local opts = {
           redirect_uri_path = "/redirect_uri",
           accept_none_alg = true,
           discovery = "https://www.example.com/auth/realms/test/.well-known/openid-configuration",
	   client_id = "myClientId",
           client_secret = "myClientSecret",
           redirect_uri_scheme = "https",
           logout_path = "/logout",
           redirect_after_logout_uri = "https://www.example.com/auth/realms/test/protocol/openid-connect/logout?redirect_uri=https://www.example.com/",
           redirect_after_logout_with_id_token_hint = false,
           revoke_tokens_on_logout = true,
           post_logout_redirect_uri= "https://www.example.com/auth/realms/test/protocol/openid-connect/logout?redirect_uri=https://www.example.com/",
           renew_access_token_on_expiry = true,
           access_token_expires_leeway = 10,
           session_contents = {id_token=true, access_token=true},
	   scope = "openid",
           ssl_verify="no"
         }
         -- call introspect for OAuth 2.0 Bearer Access Token validation
         local oidc = require("resty.openidc")
         local result, err, _, session = oidc.authenticate(opts) 

         ngx.req.set_header("Authorization", "Bearer " .. result.access_token)
         if err then
           ngx.status = 403
           ngx.say(err)
           ngx.exit(ngx.HTTP_FORBIDDEN)
         end
  
         -- solve websocket connection bug
         session:hide()
       ';

but sometimes I get two errors:
1- attempt to index local 'result' (a nil value)
2- request to the redirect_uri path but there's no session state found

###### Environment

- openresty/openresty:alpine-fat docker image
- OpenID Connect provider: Keycloak v11

I see #338 but that did not solve my problem.
@bodewig

**Comment by bodewig** [comment]
I don't see you checking the response of 

```
local result, err, _, session = oidc.authenticate(opts)
```

for errors. Most likely authentication has failed and this is why `response` is `nil` in your first error.

"no session state found" means your user's browser has invoked the redirect_uri but the request does not contain a session cookie (or it has expired). There are many reasons why a browser does not send the cookie, the cookie's `SameSite` setting mentioned in #338 is only one of them. I don't think it is possible to guess why it happens on your side, the best you can do is try to reproduce the problem and watch the developer tools of your browser to see why it does not send the cookie - it usually will tell you.

If the cookie has been set at all, that is. One reason for your second error message simply can be that people navigate to the redirect_uri directly without ever getting a cookie set in the first place.
