### ISSUE TITLE
Revoke token when the `sesison` cookie is deleted from the browser?

### ISSUE THREAD

**Issue by mike391** [zmartzone/lua-resty-openidc#423]
I notices 2 things:
- Restarting nginx still allows the user to remain logged in.  Shouldnt this clear all the sessions and force the user to have to re-authenticate?
-  After successfully logging in, if a user deleted the `session` cookie from their browser, refreshing the page still allows them to be logged into the session.  How do we invalidate the session if a user were to delete their session cookie?

**Comment by bodewig** [comment]
I believe many people will disagree with your expectation about restarting nginx. It is pretty common to have a cluster of nodes running the same application with nodes coming and going and you do not want to kill sessions whenever this happens.

For the second case what happens is your OpenID Connect Provider still has a session with your user and silently re-authenticates them. They'd need to clear all cookies (or local storage or whatever your provider uses) tied to your OIDC provider. If your OIDC provider supports [OpenID Connect RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0-01.html) then you can use lua-resty-openidc's /logout mechanism which not only removes the session but can also tell the OIDC provider to log out the user as well.
