### ISSUE TITLE
Avoid extra HTTP redirect by using originally requested page as OAuth "redirect URI"?

### ISSUE THREAD

**Issue by alexdowad** [zmartzone/lua-resty-openidc#424]
Just a question here. I don't know if what I'm suggesting is silly, crazy, impossible, or some combination of all 3.

The workflow for a client to authenticate with a web site which uses `lua-resty-openidc` is something like:

1) Client tries to load page. `openidc.authenticate` redirects client to OAuth provider, while also setting session cookie.
2) OAuth provider does what it does and then sends client to `https://my.web.site/redirect_uri`.
3) `openidc.authenticate` gets data submitted by OAuth provider, does some stuff in the background, and then redirects client to originally requested page (while setting a new session cookie).
4) Client requests original page, gets content, and displays to user.

I am thinking that steps 3 and 4 may be redundant and could be combined to avoid one round-trip between client and server.

Specifically, this means that the URL of the "originally requested page" would be used as the OAuth redirect URI. Instead of sending the client back to `https://my.web.site/redirect_uri` after authentication, the OAuth provider would send it to `https://my.web.site/page-i-actually-want-to-see`.

This would make page load time noticeably faster for clients with a high-latency Internet connection (or those in parts of the world which are far away from our servers).

One problem seems to be here:

https://github.com/zmartzone/lua-resty-openidc/blob/3aac462f8206b8553cd1f34bb99b1788efbc2140/lib/resty/openidc.lua#L1204-L1206

`openidc.authenticate` is programmed to always generate an HTTP redirect after successful authentication. To return content from the "redirect URI", I guess those lines could be patched out... but then there is this as well:

https://github.com/zmartzone/lua-resty-openidc/blob/3aac462f8206b8553cd1f34bb99b1788efbc2140/lib/resty/openidc.lua#L1471-L1482

`openidc.authenticate` uses the requested URI to detect whether the current request is a successful authentication just coming in and process it accordingly. If content was to be returned from the redirect URI, there would need to be some other way of detecting that. Maybe just checking for POST/GET args named "code" and "state" would do the trick?

Do you have any thoughts about this? Is what I'm suggesting impossible for some other reason?

**Comment by bodewig** [comment]
OAuth2 expects the client to register the valid redirect-uris with the Authorization Server and OpenID Connect inherits this. Your OIDC provider must not redirect users to a URI that is not registered explictily in order to avoid open redirect attacks.

Some providers allow redirect uris to be specified as wildcards, but many do not and I believe it is frowned upon. So you'd have to register all possible application URIs as permitted redirect targets.

Having just a handful or more common just a single redirect URI per client is what you usually do when you use OAuth2/OpenID Connect.

As for your idea of intercepting all calls with code and/or state parameters I'm afraid this is going to be tricky as you'd have to tell you application developers to restrict their choice of query parameters to not run into difficult to debug bugs that never happen in local development without an nginx in front of the application but only when deployed in protected environments.

**Comment by alexdowad** [comment]
@bodewig Thank you for those insightful comments.

It looks like this idea _may_ still be something which would work for my use case. But I understand it will not work for most users and don't expect it to ever be supported officially.

If I decide to go that way, I understand it will require a private fork of `lua-resty-openidc`.

**Comment by zandbelt** [comment]
The suggested approach will lead to authorization codes being sent to - sometimes unexpected - places that are not guaranteed to be safe and secure. This is why the spec dictates fixed redirection endpoints that exist only for the purpose of handling this credential. This plugin will remain compliant with the spec for a good reason.

**Comment by alexdowad** [comment]
@zandbelt Could you please elaborate? How would this idea lead to authorization codes being sent to unexpected places?

**Comment by zandbelt** [comment]
The security considerations about the redirection endpoint in the spec go in detail but sone examples are leaking through resources loaded from 3rd party sites (images, analytics), vulnerable discussion forum software hosted on the same domain, open redirects, etc. Protecting literally every endpoint that matches the - suggested -  loose redirection endpoint matching at the OP  is unrealistic.

**Comment by alexdowad** [comment]
> The security considerations about the redirection endpoint in the spec go in detail but sone examples are leaking through resources loaded from 3rd party sites (images, analytics), vulnerable discussion forum software hosted on the same domain, open redirects, etc. Protecting literally every endpoint that matches the - suggested - loose redirection endpoint matching at the OP is unrealistic.

Thanks for the reference to the spec. I may look at that before going any further.

In the specific use case in mind, I am thinking of applying this idea only to 3 specific URLs, all of which point to pages on my own server.

Thanks again.
