### ISSUE TITLE
Making internal "discovery" URI and external Keycloak authentication URI different

### ISSUE THREAD

**Issue by flavienbwk** [zmartzone/lua-resty-openidc#425]
Hi,

I am [making a NGINX reverse-proxy authentication project](https://github.com/flavienbwk/nginx-keycloak/) with Keycloak to restrain access to my apps.

###### Environment

- [Docker](https://github.com/flavienbwk/nginx-keycloak/blob/main/Dockerfile)
- lua-resty-openidc version : 1.7.5-1
- OpenID Connect provider : Keycloak 15.1.1

###### Actual behaviour

Currently, setting the `discovery` parameter (as in NGINX configuration below) requires the KEYCLOAK_ENDPOINT to be accessible both FROM the container AND BY the user (external to the container). **User get redirected to the [`discovery` URI](https://github.com/flavienbwk/nginx-keycloak/blob/ca4904659649f003291b7bd3d32143fa855fc628/nginx.conf.template#L14)**.

So I can't set an internal Keycloak endpoint for the container. E.g: `discovery = "http://keycloak:8080/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"` : user browser don't have access to `http://keycloak:8080`. 

So I have no choice using the Docker network interface IP : `172.17.0.1`. E.g: `discovery = "http://172.17.0.1:3333/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"` for URI to be accessible both from container and from user browser (similar to setting a domain name).

This is not desirable because internal Keycloak URI and Keycloak authentication interface URI may be monitored differently (e.g : firewall, logs).

###### Expected behaviour

Be able to configure the `discovery` URI as internal URI and be able to configure another _external Keycloak endpoint_ for the user to authenticate in its browser.

- Does such an _external Keycloak authentication endpoint_ parameter exist in lua-resty-openidc ? 

###### Minimized example

Quick and documented example here : https://github.com/flavienbwk/nginx-keycloak

###### NGINX configuration

```nginx
upstream app_a {
    server app_1:80;
}

server {
    listen   3002;
    root     /opt/nginx/html;
    resolver 127.0.0.11 valid=1s ipv6=off;
    
    access_by_lua '
        local opts = {
            redirect_uri_path = "/redirect_uri",
            accept_none_alg = true,
            discovery = "${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration",
            client_id = "${KEYCLOAK_CLIENT}",
            client_secret = "${KEYCLOAK_SECRET}",
            logout_path = "/logout",
            redirect_after_logout_uri = "${KEYCLOAK_ENDPOINT}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/logout?redirect_uri=http://localhost:3002/",
            redirect_after_logout_with_id_token_hint = false,
            scope = "openid",
            session_contents = {id_token=true}
        }
        -- call introspect for OAuth 2.0 Bearer Access Token validation
        local res, err = require("resty.openidc").authenticate(opts)
        if err then
            ngx.status = 403
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
        end
    ';

    # I disabled caching so the browser won't cache the site.
    expires           0;
    add_header        Cache-Control private;

    location / {
        proxy_pass http://app_a;
        proxy_set_header X-Forwarded-For \\$remote_addr; 
    } 
    # [...]
}
```

Thank you,

**Comment by bodewig** [comment]
I'm pretty sure lua-resty-openidc will never redirect the user to the discovery endpoint by itself. Under which circumstances do you see such a redirect?

lua-resty-opneidc will certainly redirect the user to keycloak's authorization endpoint, as this is how the OAuth2 Authorization Code Grant Flow works. The value of the authorization endpoint is read from the discovery document. It is quite possible Keycloak uses absolute URIs using the same scheme and authorities inside of the discovery that has been used to obtain the discovery document in the first place.

**Comment by flavienbwk** [comment]
Indeed it might be more correct to say user get redirected to the discovery domain name.

- If I set `http://172.17.0.1:3333/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration` as discovery endpoint, user get redirected to `http://172.17.0.1:3333/auth/realms/master/protocol/openid-connect[...]`
- If I set `http://localhost:3333/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration` as discovery endpoint, user get redirected to `http://localhost:3333/auth/realms/master/protocol/openid-connect[...]`

> The value of the authorization endpoint is read from the discovery document

Does this mean lua-resty-openidc have no control over this behavior ?  
Would you have an idea on how to configure this _authorization endpoint_ ?

**Comment by bodewig** [comment]
Yes, lua-resty-openidc trust what the discovery endpoint says.

You can completely skip automatic discovery by providing the things yourself. lua-resty-openidc replaces the discovery key in `opts` with the OIDC provide's response. You can directly provide the required data yourself (which is a lot less convenient, of course):

```
   discovery = {
       issuer = must match what the iss claim of the id_token says,
      authorization_endpoint = URL of authorization endpoint, must be accessible by browser,
      token_endpoint = URL of token endpoint, must be accessible by container
      jwks_uri = URL of the  JWKS endpoint unless you explictly specifiy the key material used to sign the id token, only accessed by container,
     id_token_signing_alg_values_supported = {algorithms supported when the id_token is signed},
      -- optionally
      userinfo_endpoint = URL of user info endpoint, will be accessed by container if set,
      revocation_endpoint = URL of revocation endpoint if you want to revoke tokens, will be accessed by container if at all,
      end_session_endpoint = URL of endpoint used for relying party initiated logout if you intend to use that, would be access by browser,
     introspection_endpoint = URL of introspection endpoint if you want to introspect the token,  will be accessed by container if at all,
   },
   token_endpoint_auth_method = whatever your Keycloak supports, likely client_secret_basic or client_secret_post
```

**Comment by flavienbwk** [comment]
Thank you very much for this snippet. I'll try this !

For those looking for these endpoints. You can find them here : `http://localhost:3333/auth/realms/master/.well-known/openid-configuration`.

**Comment by flavienbwk** [comment]
Works [as a charm](https://github.com/flavienbwk/nginx-keycloak/blob/53085654c229f768105abf722c55a0cef14f13dd/nginx.conf.template#L34). Thank you.

**Comment by bodewig** [comment]
I recommend you explicitly set token_signing_alg_values_expected as well. Most likely Keycloak uses an RSA signature (otherwise you wouldn't need the JWKS endpoint) , so 

```
token_signing_alg_values_expected = { "RS256", "RS384", "RS512", }
```

would be a good option. See https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/#RSA-or-HMAC- for why I recommend being more explicit with what you accept.

**Comment by omasseau** [comment]
@flavienbwk In Keycloak in the "General" tab of the realm you have a parameter called "Frontend URL".
This parameter is used by Keycloak to generate the authorization endpoint that has to be returned by .well-known/openid-configuration.
If you define it you can use the internal uri for the discovery parameter used by lua-resty-openidc.

When you do not define explicitely the "Frontend URL" parameter in Keycloak then Keycloak will use the scheme, hostname and port on which the .well-known/openid-configuration url has been called.

So try to play around with the "Frontend URL" parameter in Keycloak.
Il you change it, to see the changes, don't forget to restart nginx (as .well-known/openid-configuration is cached by lua-resty-openidc)

**Comment by omasseau** [comment]
@flavienbwk Note that if you use a docker image there is a KEYCLOAK_FRONTEND_URL environement variable that you can pass to your image. I've not tested it but it is worth looking at it (I guess it will apply to all realms).

See "Specifiy Frontend base url" here : https://hub.docker.com/r/jboss/keycloak/

**Comment by flavienbwk** [comment]
Thank you @omasseau, this is a good idea.
