### ISSUE TITLE
Support Hybrid flow

### ISSUE THREAD

**Issue by octomad** [zmartzone/lua-resty-openidc#426]
###### Environment

- lua-resty-openidc version (e.g. 1.7.5)
- OpenID Connect provider -- Custom IdentityServer 4

###### Expected behaviour
This module should send a request that kicks off an OIDC Hybrid flow.

###### Actual behaviour
Only does Authorization Code flow

###### Minimized example
You can see here https://github.com/zmartzone/lua-resty-openidc/blob/a468d13283d62ef5e3d14f02404294f7777c053d/lib/resty/openidc.lua#L334 that the it only sends `response_type=code` when it should be sending both `code` and `id_token`.

Here is an example of the authorize redirect url that it generates.

http://www.sample.com/connect/authorize?code_challenge=something&response_type=code&redirect_uri=http%3A%2F%2Fauth.sample.local%2Fredirect_uri&scope=openid%20email%20profile&code_challenge_method=S256&nonce=115ffb24cce8d6ab7bd650a85cfb992f&client_id=asdfoo&state=somestate

###### Configuration and NGINX server log files
none

**Comment by bodewig** [comment]
you are correct, lua-resty-openidc does not support the hybrid flow.

**Comment by octomad** [comment]
Ok we can close.
