### ISSUE TITLE
Send Authorization to backend

### ISSUE THREAD

**Issue by Pythonov** [zmartzone/lua-resty-openidc#432]
Hi!
Could you help me please?
Is it possible to send Authorization header to app behind the nginx? 
Thank you!

**Comment by bodewig** [comment]
This really is an nginx question more than a lua-resty-openidc one. By "the app behind nginx" I assume you've got an application for which nginx acts as reverse proxy using the proxy module. In that case [`proxy_set_header`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header) is your friend.
