### ISSUE TITLE
How to log the userid from access_by_lua block

### ISSUE THREAD

**Issue by rprasaath** [zmartzone/lua-resty-openidc#433]
I have openresty setup with OpenID connect provider setup with Keycloak. In the nginx configuration "access_log" i would like to get the userid after doing the sso authentication. I tried using $remote_user but that always returns empty string. Does it support logging of userid ? If so what configuration needs to be done within lua block to get the userid.

**Comment by bodewig** [comment]
the access token which may or may not contain something like a userid. `$remote_user` is something completely different, see https://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_user

It is possible to set an nginx variable from a lua variable, see the lua-module's documentation. I don't know whether it is possible to log arbitrary nginx variables, you may want to consult the nginx documentation for this.
