### ISSUE TITLE
Support for lua-resty-session >= 3.0 ?

### ISSUE THREAD

**Issue by audunmeltzer** [zmartzone/lua-resty-openidc#436]
Requirements at https://luarocks.org/manifests/hanszandbelt/lua-resty-openidc-1.7.5-1.rockspec
Is lua-resty-session >= 3.0 supported for version = 1.7.5-1

**Comment by bodewig** [comment]
I believe lua-resty-session 3.x is not fully compatible with 2.x so it may cause problems. I haven't tried it myself but I'm afraid you may find older issues here that report problems.
