### ISSUE TITLE
Possible Release

### ISSUE THREAD

**Issue by usysrc** [zmartzone/lua-resty-openidc#442]
###### Environment

- lua-resty-openidc version 1.7.5
- bearer_jwt_verify

###### Expected behaviour
The Problem is that https://github.com/zmartzone/lua-resty-openidc/pull/431 was merged but no release was created.

###### Actual behaviour
The Problem persists in the release.

Can we get a new release?

**Comment by jykae** [comment]
@bodewig interested in local_redirect_uri_path option, any idea when new release would happen?

**Comment by bodewig** [comment]
@zandbelt  has been kind enough to push out 1.7.6 at luarocks. Thank you for your patience.
