### ISSUE TITLE
outgoing proxy support

### ISSUE THREAD

**Issue by ConanMalone** [zmartzone/lua-resty-openidc#45]
Hi, we've got lua-resty-openidc working, and are now trying to get it to work in an environment that requires all traffic to go through an outbound proxy.  We are getting a connection refused error when trying to access the discovery URL.  We have installed the lua-resty-socket module but we're amateurs at lua.  Could you point us in the right direction to get openidc to use a proxy?

**Comment by zandbelt** [comment]
I would have liked to point you to the support for that in the underlying lua-resty-http module that lua-resty-openidc uses to make such calls. But apparently that support does not exist there, see: https://github.com/pintsized/lua-resty-http/issues/63

So it would require modifications to lua-resty-openidc (or preferably lua-resty-http...) to make this work. Making this an enhancement request

**Comment by zandbelt** [comment]
there's work-in-progress here: https://github.com/sjakthol/lua-resty-http/commit/0939833b0cca2a50054bf1db437db62295c1e299

**Comment by grrolland** [comment]
Hello,

I create a pull request to fix this issue. Let me know if this could be merged with the master branche.

Regards.

**Comment by zandbelt** [comment]
Nice work! Does it require a particular version of lua-resty-http?

**Comment by grrolland** [comment]
Yes, this patch require the version 0.11 of lua-resty-http.
