### ISSUE TITLE
Ability to configure an "external" redirect_uri, as well as a "local" path to recognize as an authorization callback

### ISSUE THREAD

**Issue by raythree** [zmartzone/lua-resty-openidc#453]
As mentined in this comment:

https://github.com/zmartzone/lua-resty-openidc/issues/450#issuecomment-1258701480

Our application is using an nginx sidecar with lua-resty-openidc, and our application is behind an inbound reverse proxy that uses URLs with a prefix like "app-name" as in "https://app-name/some/path" to route. But our application is not aware of "app-name" and only looks for paths like /some/path. We thought that we could use:

opts.redirect_uri => Configure the full redirection URI to give to the auth server (https://host/app-name/callback)
opts.redirect_uri_path => Configure the path to recognize as in inbound authorization callback (/callback)

It seems that if we put the "opts.redirect_uri_path" in FRONT of the "and" statement that this would work:

https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1437

However the code also indicates that "redirect_uri_path" is deprecated. It would be nice if it could be used as suggested above, where the external URL that the authorization server needs to redirect to is different from the path used to recognize it as an authorization callback.

**Comment by bodewig** [comment]
Not sure when I will get to this, but I think I'd prefer a new separate configuration parameter to make its purpose more clear. Need to think about it again, though.

**Comment by bodewig** [comment]
Sorry, it took longer than I had hoped. A new `opts.local_redirect_uri_path` has been added to the master branch just now.

**Comment by raythree** [comment]
Thank you! Just saw this now, which is good timing as we are updating our sidecar. Will give this a try.

**Comment by bodewig** [comment]
this is part of the 1.7.6 release.
