### ISSUE TITLE
Avoid session_state in openidc auth redirect url

### ISSUE THREAD

**Issue by hemahhari** [zmartzone/lua-resty-openidc#454]
###### Environment

- lua-resty-openidc
- Nginx access by lua block

**Comment by bodewig** [comment]
I'm not sure I understand this issue. The "redirecturi" is something that is completely controlled by lua-resty-openidc. Are you referring to the URI lua-resty-openidc redirects to after successful login (i.e. the redirect *after* the redirecturi has been processed)?

**Comment by bodewig** [comment]
please reopen with more information.
