### ISSUE TITLE
bearer_jwt_verify() can't pass `Accept:` header

### ISSUE THREAD

**Issue by jameskhedley** [zmartzone/lua-resty-openidc#458]
The jwks_uri I need to get the public key from to validate my bearer token, only responds if `Accept: application/json` is set explicitly but I don't think I can pass that, did try using the headers but it doesn't get passed:

```
local opts = {
  ssl_verify = 'no',
  headers = {
    ['Accept'] = 'application/json'
  },
  discovery = {
    jwks_uri = my_jwks_uri
  }
}
local res, err = oidc.bearer_jwt_verify(opts)
```
Log looks like:
```
2023/01/10 12:49:33 [error] 549749#549749: *58 [lua] openidc.lua:1006: openidc_load_jwt_and_verify_crypto(): response indicates failure, status=400, body={"status":400,"message":["Accept header needed"]}, client: 127.0.0.1, server: <remote_server>, request: "POST /ingestion HTTP/1.1", host: "localhost:4443"
```

Is there a workaround where I could use `httpc.request` to get the jwks_uri?

###### Environment

- lua-resty-openidc version: 1.7.5-1
- OpenID Connect provider: proprietary :( 

###### Expected behaviour
I could just set discovery.headers in the same way as elsewhere, if it were passed along in the call to `openidc_jwks()`

###### Actual behaviour
No way of specifying headers

###### Minimized example
*Minimal, complete configuration that reproduces the behavior.*

###### Configuration and NGINX server log files
See above

**Comment by bodewig** [comment]
`opts.http_request_decorator` can be a function receiving the request object before sending the request. You should be able to add the header there.

**Comment by jameskhedley** [comment]
@bodewig Thanks Stefan, that worked. In case it helps anyone else, this should do the trick:

```
function decorate_me_header(req)
  local headers = {}
  headers['Accept'] = 'application/json'
  req['headers'] = headers
  return req
end
```
(I'm quite new to Lua so please correct any bad practice)

**Comment by bodewig** [comment]
there is an example in this repo's readme:

```
             -- Optional : add decorator for HTTP request that is
             -- applied when lua-resty-openidc talks to the OpenID Connect
             -- provider directly. Can be used to provide extra HTTP headers
             -- or add other similar behavior.
             -- http_request_decorator = function(req)
             --   local h = req.headers or {}
             --   h[EXTRA_HEADER] = 'my extra header'
             --   req.headers = h
             --   return req
             -- end,
```

Your function will overwrite all existing headers as you create a fresh map. I'd recommend to stick to the pattern of the example and use `local headers = req.headers or {}` instead.

In Lua `a.b` on a table can be used as a shorthand for `a['b']` - at least as long as `b` is a valid Lua identifier - which is more convenient to write most of the time.

**Comment by jameskhedley** [comment]
Thanks again, I will do that instead.
