### ISSUE TITLE
x5c not being parsed correctly in bearer_jwt_verify()

### ISSUE THREAD

**Issue by jameskhedley** [zmartzone/lua-resty-openidc#459]
###### Environment

- lua-resty-openidc version 1.7.5-1
- OpenID Connect provider: proprietary

###### Expected behaviour
Call to `bearer_jwt_verify()` should load and parse the public keys from my `jwks_uri`

###### Actual behaviour
Stacktrace in the nginx log, authentication doesn't complete.

Looks like there's meant to be an array [here](https://github.com/zmartzone/lua-resty-openidc/blob/6f0f1e07bde5f132fedf09601292f6215b0fe0a1/lib/resty/openidc.lua#L847) but it's a string.

There's also a check [here](https://github.com/zmartzone/lua-resty-openidc/blob/6f0f1e07bde5f132fedf09601292f6215b0fe0a1/lib/resty/openidc.lua#L911) that looks like it's guarding against a zero-length array but of course a string length will be a non-zero integer.

So I'm not sure if there's something wrong with the code or my jwks is malformed somehow (or non-standard). Not sure why `x5c` would be an array?

Any help greatly appreciated!

###### Minimized example
```
local jwt = require 'resty.jwt'
local oidc = require 'resty.openidc'
local headers = ngx.req.get_headers()
...
local jwt_token = jwt:load_jwt(bearer_token);

local opts = {
  ssl_verify = 'no',
  http_request_decorator = decorate_http_accept_header,
  discovery = {
    jwks_uri = <my_jwks_uri>
  }
}
local res, err = oidc.bearer_jwt_verify(opts)
```

My JWKS looks like:
```
{
    "keys": [
        {
            "e": "AQAB",
            "n": "blah",
            "alg": "RS256",
            "kid": "blah",
            "kty": "RSA",
            "use": "sig",
            "x5c": "blah"
        },
        {
            "e": "AQAB",
            "n": "blah",
            "alg": "RS256",
            "kid": "blah",
            "kty": "RSA",
            "use": "sig",
            "x5c": "blah"
        },
        {
            "e": "AQAB",
            "n": "blah",
            "alg": "RS256",
            "kid": "blah",
            "kty": "RSA",
            "use": "sig",
            "x5c": "blah"
        }
    ]
}
```

###### Configuration and NGINX server log files
```
2023/01/11 11:23:16 [error] 571236#571236: *97 lua entry thread aborted: runtime error: /usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:291: attempt to get length of local 'input' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua: in function 'openidc_base64_url_decode'
	/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:853: in function 'openidc_pem_from_x5c'
	/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:926: in function 'openidc_pem_from_jwk'
	/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:1007: in function 'openidc_load_jwt_and_verify_crypto'
	/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:1824: in function 'jwt_verify'
	/usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:1862: in function 'bearer_jwt_verify'
	/home/james/Documents/847/openresty/conf/apim_access.lua:64: in main chunk, client: 127.0.0.1, server: <my_server>, request: "POST /ingestion HTTP/1.1", host: "localhost:4443"
```

**Comment by bodewig** [comment]
just added an extra check

**Comment by jameskhedley** [comment]
Thanks again. I think you are correct about the spec. However I did try this with the Python equivalent and it did seem to be happy - would you maybe take a PR to make it work either way?

**Comment by jameskhedley** [comment]
Alternatively, is it possible monkey patch the relevant function? I tried this but no effect:
```
local oidc = require 'resty.openidc'
oidc.openidc_pem_from_x5c = patched_openidc_pem_from_x5c
```

I'm trying to get the OIDC provider module fixed (it's our own one) but would like to get it to work in the meantime.

**Comment by bodewig** [comment]
TBH, I'd rather not add workarounds for servers who don't obey the spec.

I don't think you can override local functions in a module the way you try (then again I'm not an expert in Lua myself). The easiest approach may be to use a patched version by overwriting openidc.lua in your installation until you've gotten you provider fixed.

**Comment by jameskhedley** [comment]
That's fair, no problem.

I read you can monkeypatch Lua normally but maybe LuaJIT is a bit different, just a guess though!

Thanks for the help!
