### ISSUE TITLE
Missing session when user already connected

### ISSUE THREAD

**Issue by JaquierM** [zmartzone/lua-resty-openidc#461]
Hi,

I need to create a proxy to authorize some user to access a internal service.
The internal service is display inside another page with a iframe.

I used [keycloak-nginx](https://edhull.co.uk/blog/2018-06-06/keycloak-nginx) as a starting point.

So the proxy have three tasks:
1. Define a endpoint for the service
2. Define the authorization for this endpoint
3. Proxy the request and if necessary clean the iframe parameter

The app is logged on the same keycloak realm as the proxy. 

###### Environment

- lua-resty-openidc version : 1.7.5-1
- OpenID Connect provider : Keycloak
- Openresty version : 1.21.4.1

###### Expected behaviour

I was expecting to see the targeted page.
I don't need to connect which is good because I'm already connected (via app.example).

###### Actual behaviour

If I use directly the endpoint (proxy.example), I can log with keycloak and access the page correctly.

When I access it with the iframe, I have the following error:
```log
023/01/18 11:40:09 [error] 7#7: *42 [lua] openidc.lua:1475: authenticate(): request to the redirect_uri path but there's no session state found, client: 10.0.0.2, server: app.example, request: "GET /redirect?state=b3e961e7ad10e83813a392c5e1cafd35&session_state=18d0e120-47ec-4917-a029-0565b98b9a19&code=fae22fca-8db5-4317-a9ed-58efd554bbb4.18d0e120-47ec-4917-a029-0565b98b9a19.4279ba3a-4698-462f-8dea-a08cf269c106 HTTP/1.1", host: "proxy.example"
```

I have try to use the same hostname for both and if I connect directly on app.example/proxy then I go to app.example the connection work properly.

Base on that, I think the problem is link to the cookie or the session management.
It might be a wrong or missing configuration but I cannot find it.

###### Minimized example

I don't have minimal example yet.

###### Configuration and NGINX server log files

```conf
server {
    listen       80;
    server_name  proxy.examplel;

    resolver local=on ipv6=off;

    error_log /dev/stderr;
    access_log /dev/stdout;

    lua_code_cache on;
    # Necessary if lua_code_cache off
    # set $session_secret 723p4hR234t36VsCD8g565325IC0022G;

    lua_ssl_trusted_certificate /run/secrets/ca.crt;
    lua_ssl_verify_depth 5;
    lua_ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2  TLSv1.3;

    access_by_lua '
        local openidc = require("resty.openidc")
        openidc.set_logging(nil, { DEBUG = ngx.INFO })
        local opts = {
            redirect_uri = "http://proxy.example/redirect",
            accept_none_alg = true,
            discovery = "https://keycloak.example/auth/realms/onsphere/.well-known/openid-configuration",
            client_id = "client",
            client_secret = "*****************",
            ssl_verify = true,
            logout_path = "/logout",
            redirect_after_logout_uri = "https://keycloak.example/auth/realms/onsphere/protocol/openid-connect/logout",
            redirect_after_logout_with_id_token_hint = false,
            renew_access_token_on_expiry = true,
            session_contents = {id_token=true}
        }
        local res, err = openidc.authenticate(opts)

        if err then
            ngx.status = 403
            ngx.header["Content-type"] = "text/plain"
            ngx.say(err)
            ngx.exit(ngx.HTTP_FORBIDDEN)
        end

        -- Check authorization
    ';

    location / {
        proxy_pass https://www.google.ch/;
        proxy_hide_header x-frame-options;
        proxy_redirect https://www.google.ch/ http://proxy.example/;
    }
}
```

**Comment by bodewig** [comment]
when using an IFrame your browser most likely doesn't send the Cookie lua-resty-openidc needs in order to identify your session. If your IFrame is loaded from a different site than the containing page, then setting the Cookie's `SameSite` attribute may help. See https://github.com/bungle/lua-resty-session#string-sessioncookiesamesite - for some browsers IFrames require `None` for Cookies to work.

Most likely even this will not be enough if modern browsers are among your targets. You may want to read up on "intelligent tracking prevention" in Safari for example. In order to make Cookies work inside of IFrames new browsers will need you use the StorageAPI or similar techniques.

**Comment by JaquierM** [comment]
Thanks for the explication.

Adding `set $session_cookie_samesite   None;` seems to solve my problem.
