### ISSUE TITLE
v1.7.5 no longer works due to dependency on lua-resty-session

### ISSUE THREAD

**Issue by Scorpion1091** [zmartzone/lua-resty-openidc#463]
https://github.com/zmartzone/lua-resty-openidc/blob/85e30a13e08156ef3d782ecf7236758334234c6c/lua-resty-openidc-1.7.5-1.rockspec#L27

lua-resty-session released a Version 4.0 with breaking changes. the dependency in the mentioned line is to Version >=2.8

The dependency should be >=2.8; <4.0

**Comment by bodewig** [comment]
Hans has released 2.7.6-2 with just that fix a few hours ago.

**Comment by nikitamendelbaum** [comment]
Can we expect 1.7.6 on OPM? I've been using `opm` as package manager in my docker images for years and with that problem now, the only solution currently is to switch to luarocks and install `lua-resty-openidc=1.7.6-3` with it.

**Comment by nikitamendelbaum** [comment]
For those having the same problem with opm package, the temporary solution until the 1.7.6-3+ is published in OPM:
```
opm get zmartzone/lua-resty-openidc=1.7.4
opm remove bungle/lua-resty-session && \
opm get bungle/lua-resty-session=3.10
```

**Comment by nikitamendelbaum** [comment]
Found in the main README.md:
> Older versions of lua-resty-openidc could also be installed using opm but this is no longer supported.

SO I guess it's either luarocks (which requires the build from source) or:
> Otherwise copy openidc.lua somewhere in your lua_package_path under a directory named resty. If you are using [OpenResty](http://openresty.org/), the default location would be /usr/local/openresty/lualib/resty
