### ISSUE TITLE
Migrate `lua-resty-session` to v4 

### ISSUE THREAD

**Issue by pankgeorg** [zmartzone/lua-resty-openidc#464]
I've found this nice PR where the author of `lua-resty-session` bumps the usage of the library to v4.

https://github.com/Kong/kong/pull/10199/files

We've had our fair share of problems with cookies in the v3 version (some of them are in open issues), and while it's hard to trust a codebase that is two weeks old, it's scary not to trust it too. 

What do you think about making the migration? Is that something aligned with the project goals? I could potentially also find time in the next 3 months, if the consensus is that it will work better.

**Comment by bodewig** [comment]
Given that we just found lua-resty-session 4 breaks backwards compatibility the hard way - see #463 - I guess we will want to migrate to it eventually. Personally I haven't followed the development "over there" and can not judge whether 4.x is "better" for any kind of better - but it is going to be the version that is under active development and receives bug fixes in the future.

**Comment by balajiv113** [comment]
Any updates on this ??

If contributions are welcome am happy to take this and provide support for lua-resty-session 4.x
