### ISSUE TITLE
lua-resty-openidc 1.7.5 forces lua-resty-session to be updated into 4.X version

### ISSUE THREAD

**Issue by ColinBurgess** [zmartzone/lua-resty-openidc#465]
###### Environment

- lua-resty-openidc version 1.7.5, 1.7.6
- OpenID Connect provider does not matter

###### Expected behavior

Actual 1.7.5 version should not be forcing the update of lua-resty-session beyond 3.10

###### Actual behavior

Dependency tree while installing with opm forces the update of lua-resty-session to 4.X which is breaking our actual implementation

Please tag the latest changes pushed into master to a tag that can be used by opm that does not force lua-resty-sesion update

**Comment by bodewig** [comment]
right now 1.7.6 is not published to opm and we are considering dropping support for opm completely
