### ISSUE TITLE
Question - redirect after auth including fragment part of the URL

### ISSUE THREAD

**Issue by cilf** [zmartzone/lua-resty-openidc#469]
Is there some way I could keep the hash fragment part of the URL to be part of the after-login redirect?

I know that part of the URL is not sent to the server and nginx along with this library doesn't see it. Just wondering if there's some way I could achieve this behaviour.

###### Environment

- lua-resty-openidc version 1.7.6
- OpenID Connect provider Keycloak

###### Expected behaviour

1. Go to https://example.com/app/dashboards#/view/CI01154077
2. Gets redirected to Keycloak login page
3. After successful login, the page in the browser is still https://example.com/app/dashboards#/view/CI01154077

###### Actual behaviour

1. Go to https://example.com/app/dashboards#/view/CI01154077
2. Gets redirected to Keycloak login page
3. After successful login, the page in the browser is https://example.com/app/dashboards

**Comment by bodewig** [comment]
as you already say yourself, the server doesn't know the fragment at all.

The way this is handled nowadays AFAIU is by not using fragments in frontend applications (i.e you dashboard) but rather use the history API to rewrite `/app/dashboards#/view/CI01154077` to `/app/dashboards/view/CI01154077` and have the backend return your dashboard page for URI that starts with `/app/dashboards`. In other words I don't believe there is a server-side solution but there are very common solution that avoid using fragments for routing and state.
