### ISSUE TITLE
Session cookie secure

### ISSUE THREAD

**Issue by kratosmat** [zmartzone/lua-resty-openidc#470]
###### Environment

- lua-resty-openidc version (e.g. 1.7.6)
- WSO2 Identity Server as OpenID Connect provider

Hello everyone,
I need to set some properties on session cookie such as cookie_http_only, cookie_secure, but I wasn't able to do it, could you help me.

Thanks a lot,
Matteo.

**Comment by bodewig** [comment]
all settings of the session cookie are directly controlled by lua-resty-session, see the documentation at https://github.com/bungle/lua-resty-session/tree/v3.10 . You can either configure things globally via the nginx configuration or on a session by session bases via the `session_or_opts` parameter of `openidc.authenticate`.

**Comment by kratosmat** [comment]
Hello,
thanks for the quick answer, but I don't understand how I can do this.

Here you can find my configuration:

          location /local {
            access_by_lua_block {
                local opts = {
                    redirect_uri_path = "/local/redirect_uri",
                    discovery = "https://is.local.it/oauth2/token/.well-known/openid-configuration",
                    client_id = "XXXX",
                    client_secret = "XXX",
                    ssl_verify = "no",
                    scope = "openid email profile",
                    redirect_uri_scheme = "https"
                }

                -- call authenticate for OpenID Connect user authentication
                local res, err = require("resty.openidc").authenticate(opts)

                if err then
                    ngx.status = 500
                    ngx.say(err)
                    ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
                end

            }

            proxy_pass https://xxxx.it/hdi;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_hide_header x-frame-options;
          }


How can I put, for example, session.cookie.secure in opts? I don't find an example.

Thanks a lot,
Matteo.

**Comment by bodewig** [comment]
There are examples over at lua-resty-session. 

Globally - https://github.com/bungle/lua-resty-session/tree/v3.10#nginx-configuration-variables:

```
set $session_cookie_secure     on;
```

per request https://github.com/bungle/lua-resty-session/tree/v3.10#functions-and-methods

```Lua
local res, err = require("resty.openidc").authenticate(opts, nil, nil, { cookie = { secure = true  } })
```

**Comment by kratosmat** [comment]
Hello,
I have used the second option and it worked, many thanks.
