### ISSUE TITLE
Question: is there a way to handle temporary 503 from JWKS endpoint?

### ISSUE THREAD

**Issue by jameskhedley** [zmartzone/lua-resty-openidc#471]
Hi, just a general question at this stage but one thing we noticed was that if the cache expires at a bad time then the GET to the JWKS url can fail with a 503 (happily the endpoint is behind a proxy so we don't need to wait for a timeout).

This is probably mostly an edge case but for functional requirement reasons, we need a way to deal with these 503 errors without returning an error. 

So is there a way to catch specific return codes from the JWKS endpoint? If not should there be? Happy to make a PR if so.

**Comment by bodewig** [comment]
well, the request could also fail at the very first time before the cache has even been filled. What would you want to do in such a situation? I hope you do not want to accept a signature you can not verify.

Technically once the cache has expired the library doesn't know it ever had a valid JWKS at all, it either is inside the cache or it gets retrieved. Caching is handled outside of lua-resty-openidc.

Right now there is no way to handle certain HTTP status codes in any special way. There is a decorator one can attach to requests, but none that would see responses - it would be possible to add that, of course. I'm not sure what kind of fallback you'd want to provide in a situation like this, though.

**Comment by jameskhedley** [comment]
Thanks Stefan. I was thinking when I asked this that we could tolerate tokens that had expired, if and only if the JWKS was returning a temporary failure. However I see now that's not possible without retaining the previous set of JWKS, which as you said is not how the caching works.

I think if I have to deal with edge cases like this, I might as well put an extra service in between this OIDC client and the JWKS endpoint, then I can do whatever I like with it - rather than hacking at this client.
