### ISSUE TITLE
Bug: cannot auth with login.microsoftonline.com: bad argument #1 to 'match' (string expected, got nil)in function 'openidc_load_jwt_and_verify_crypto'

### ISSUE THREAD

**Issue by andgineer** [zmartzone/lua-resty-openidc#472]
###### Environment
      FROM openresty/openresty:alpine-fat
      RUN luarocks install lua-resty-openidc 1.7.6

Keycloak (reference, works successfully),  login.microsoftonline.com(fail)

###### Expected behaviour

Work without errors

###### Actual behaviour

I replaced secrets and IDs with three dots.

        access_by_lua(access-include.conf:27):21: in main chunk, client: 127.0.0.1, server: 127.0.0.1, request: "GET /login?code=....&session_state=... HTTP/1.1", host: "...", referrer: "https://login.microsoftonline.com/"
        
        /usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:1150: in function 'authenticate'
        /usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:1052: in function 'openidc_load_and_validate_jwt_id_token'
        /usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:966: in function 'openidc_load_jwt_and_verify_crypto'
        [C]: in function 'match'
        coroutine 0:
        *249 lua entry thread aborted: runtime error: /usr/local/openresty/luajit/share/lua/5.1/resty/openidc.lua:966: bad argument #1 to 'match' (string expected, got nil)
        
        [debug] 7#7: *249 [lua] openidc.lua:529: call_token_endpoint(): token endpoint response: {"token_type":"Bearer","scope":"profile openid email 00000003-0000-0000-c000-000000000000/Group.Read.All 00000003-0000-0000-c000-000000000000/User.Read 00000003-0000-0000-c000-000000000000/User.Read.All 00000003-0000-0000-c000-000000000000/.default","expires_in":3688,"ext_expires_in":3688,"access_token":...
        
        *249 [lua] openidc.lua:575: openidc_discover(): response data: {"token_endpoint":"https://login.microsoftonline.com/.../oauth2/v2.0/token","token_endpoint_auth_methods_supported":["client_secret_post","private_key_jwt","client_secret_basic"],"jwks_uri":"https://login.microsoftonline.com/.../discovery/v2.0/keys","response_modes_supported":["query","fragment","form_post"],"subject_types_supported":["pairwise"],"id_token_signing_alg_values_supported":["RS256"],"response_types_supported":["code","id_token","code id_token","id_token token"],"scopes_supported":["openid","profile","email","offline_access"],"issuer":"https://login.microsoftonline.com/.../v2.0","request_uri_parameter_supported":false,"userinfo_endpoint":"https://graph.microsoft.com/oidc/userinfo","authorization_endpoint":"https://login.microsoftonline.com/.../oauth2/v2.0/authorize","device_authorization_endpoint":"https://login.microsoftonline.com/.../oauth2/v2.0/devicecode","http_logout_supported":true,"frontchannel_logout_supported":true,"end_session_endpoint":"https://login.microsoftonline.com/.../oauth2/v2.0/logout","claims_supported":["sub","iss","cloud_instance_name","cloud_instance_host_name","cloud_graph_host_name","msgraph_host","aud","exp","iat","auth_time","acr","nonce","preferred_username","name","tid","ver","at_hash","c_hash","email"],"kerberos_endpoint":"https://login.microsoftonline.com/.../kerberos","tenant_region_scope":"EU","cloud_instance_name":"microsoftonline.com","cloud_graph_host_name":"graph.windows.net","msgraph_host":"graph.microsoft.com","rbac_url":"https://pas.windows.net"}
        
        *249 [lua] openidc.lua:674: openidc_get_token_auth_method(): 1 => client_secret_post

###### Minimized example

        access_by_lua_block {
            local opts = {
                client_id = os.getenv("OPENID_CLIENT_ID"),
                client_secret = os.getenv("OPENID_CLIENT_SECRET"),
                discovery = os.getenv("OPENID_DISCOVERY"),
                scope = os.getenv("OPENID_SCOPE"),
                redirect_uri = os.getenv("OPENID_REDIRECT_URI"),
        
                -- When using https to any OP endpoints, enforcement of SSL certificate check can be mandated ("yes") or not ("no").
                ssl_verify = "no",
        
                -- Refresh the users id_token after 900 seconds without requiring re-authentication
                refresh_session_interval = 900,
        
                redirect_after_logout_uri = "/",
                -- token_endpoint_auth_method = "client_secret_basic",
                accept_none_alg = true,
                session_contents = {id_token=true}
            }

    local res, err = require("resty.openidc").authenticate(opts);
    if err or not res then
        ngx.print(err)
        ngx.exit(ngx.HTTP_FORBIDDEN)
    end
    ngx.req.set_header("X-USER", res.id_token.sub)
}

###### Configuration and NGINX server log files
see above

**Comment by andgineer** [comment]
This configuration successfully works with Keycloak.
But when I switch to login.microsoftonline.com if fail with this error

**Comment by bodewig** [comment]
it looks as if the token endpoint didn't return an id_token at all.

Seems as if one has to perform extra steps to make Azure AD emit id_tokens: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#enable-id-tokens - this may be a red herring, but can you verify your client is expected to be granted an id_token?

**Comment by andgineer** [comment]
In the manifest I see

    "oauth2AllowIdTokenImplicitFlow": true

But it strange - in the log I see `"response_types_supported":["code","id_token"`
But then `token endpoint response: {"token_type":"Bearer",.., "access_token":..`

Not sure should "id_token" be here and why it is not.
In the response Azure said it is supported..

**Comment by andgineer** [comment]
In fact that was my stupid error.
As scope I use some ID that Azure returned me in some error about wrong scope, it was long time ago and I do not remember what caused this error.

So I replaced `scope =  "openid email profile"` and now it works.

Thank you for your time, it really helped me to understand that this is not lib bug and I should recheck my settings.
