### ISSUE TITLE
why the userinfo scop is not from discover 

### ISSUE THREAD

**Issue by bluceyan** [zmartzone/lua-resty-openidc#492]
![image](https://github.com/zmartzone/lua-resty-openidc/assets/137409967/4eea69a4-aeaa-433b-9bdb-cc1f483f75a5)

**Comment by bodewig** [comment]
I don't believe I understand the question. The only thing discovery provides is the list of supported scopes of the OpenID Connect provider. To me it seems very unlikely that "asking for all supported scopes" would be a good default for any client. If this is it wha you are asking for, then I don't really know. There is no "userinfo" scope in the OpenID Connect standard.
