### ISSUE TITLE
How to set a cookie domain in openidc.authenticate()

### ISSUE THREAD

**Issue by marinator86** [zmartzone/lua-resty-openidc#493]
I think that is a quick one for you guys.
I have tried setting a cookie_domain in the session_or_opts argument, but that didn't work.
Can you help me out?
Thank you

**Comment by bodewig** [comment]
According to https://github.com/bungle/lua-resty-session/tree/v3.10 the option should be something like `{ cookie = { domain = "mydomain.com" } }`, so it is `cookie.domain` (nested table) rather than `cookie_domain`.
