### ISSUE TITLE
Raw id_token

### ISSUE THREAD

**Issue by mhaagens** [zmartzone/lua-resty-openidc#494]
Is there a way to get the raw id token and pass it along as a header?

**Comment by bodewig** [comment]
It is stored as `enc_id_token` in the session. If you enable storing it, that is.

**Comment by mhaagens** [comment]
Thanks for the swift reply.
So it would go something like this?
```
  local opts = {
    ...,
    session_contents = {
      enc_id_token = true
    }
  }
```
```
  local res, err, target, session = require("resty.openidc").authenticate(opts)
  ngx.req.set_header("my-id-token-header", session.enc_id_token)
```
Can't seem to get anything from session.enc_id_token.

**Comment by bodewig** [comment]
should be `session.data.enc_id_token`. The session itself has a few more properties and the actual stored data is inside a table called `data`.
