### ISSUE TITLE
bug: Returns 'request to the redirect_uri path but there's no session state found' when the original request URL and redirect_uri are equal.

### ISSUE THREAD

**Issue by luoluoyuyu** [zmartzone/lua-resty-openidc#499]
## Description

Hi all,

When the resource address I need to access is '127.0.0.1:8080/test', but I am not logged in, I hope that I can jump to '127.0.0.1:8080/test' after logging in. However, when I configure the value of 'redirect_uri' to '127.0.0.1:8080/test', the login success does not jump to '127.0.0.1:8080/test', and an exception is thrown `'request to the redirect_uri path but there's no session state found'`.

## Environment

- **lua-resty-openidc version:** e.g., 1.7.6
- **OpenID Connect provider:** e.g., Keycloak, Azure AD

## Expected Behaviour

The configuration is as below. When I visit http://127.0.0.1:9080/anything/test without logging in, I should be redirected to the login page and redirected to http://127.0.0.1:9080/anything/test when I am done logging in.

## Actual Behaviour

When the login is complete, it fails to jump to http://127.0.0.1:9080/anything/test and instead returns the error: `'request to the redirect_uri path but there's no session state found'`.

## Minimized Example

*Minimal, complete configuration that reproduces the behavior.*

## Configuration and NGINX Server Log Files

The configuration is as follows:

```lua
local opts = {
    client_id = "myclient",
    client_secret = "N6V0pf0xr3GPeoGLcVOgw2G67i5MxTfd",
    discovery = "http://localhost:8080/realms/myrealm/.well-known/openid-configuration",
    scope = "openid profile",
    realm = "myrealm",
    redirect_uri = "http://127.0.0.1:9080/anything/test",
}
```

The login process is as follows.
``` lua
local unauth_action = opts.unauth_action
if unauth_action ~= "auth" then
    unauth_action = "deny"
end
openidc.authenticate(opts, nil, unauth_action, opts.session)

```

**Comment by luoluoyuyu** [comment]
The problem is https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1467-L1477
```lua
  if path == openidc_get_redirect_uri_path(opts) then
    log(DEBUG, "Redirect URI path (" .. path .. ") is currently navigated -> Processing authorization response coming from OP")

    if not session.present then
      err = "request to the redirect_uri path but there's no session state found"
      log(ERROR, err)
      return nil, err, target_url, session
    end

    return openidc_authorization_response(opts, session)
  end
```
In this code causes the bug

**Comment by luoluoyuyu** [comment]
# Proposal: fix 'no Session State' error

## Motivation

When users need to access the resource at `127.0.0.1:8080/test` without being logged in, they expect to be redirected to `127.0.0.1:8080/test` after a successful login. However, when users configure the `redirect_uri` value as `127.0.0.1:8080/test`, the redirection does not occur after a successful login, leading to an exception.

## Goals

The goal is to fix this issue so that after logging in, users are redirected to their originally requested resource path.

## Problem Analysis

As depicted in the flowchart below, upon entering the `authenticate` function, the first task is to check if a redirect address is configured. If a redirect address is configured, it then checks whether the user is logged in to avoid redirection without authentication. Therefore, when the user's requested path matches the configured redirect path, an exception is thrown.
![image](https://github.com/zmartzone/lua-resty-openidc/assets/82068138/27b4125a-9c49-4c85-9489-13ddb12880bd)

## Solution

To address this issue, modify the code as follows. If the request is a redirect and the current session is not logged in, continue with the login process instead of throwing an exception:

```lua
-- see if this is a request to the redirect_uri i.e. an authorization response
local path = openidc_get_path(target_url)
if path == openidc_get_redirect_uri_path(opts) and session.present then
    log(DEBUG, "Redirect URI path (" .. path .. ") is currently navigated -> Processing authorization response coming from OP")

    return openidc_authorization_response(opts, session)
end

**Comment by luoluoyuyu** [comment]
Hi @bodewig 
I would like to submit a pr for this issue, what do you think of the above proposal, can you give me some suggestions?

**Comment by bodewig** [comment]
I still don't understand what problem you are trying to address. There is no reason why anybody would want to navigate the redirect_uri outside of the OIDC authentication flow. This should never be a "normal" URI of your application. The premise "when users configure the redirect_uri value as 127.0.0.1:8080/test" simply should never happen. 

IMHO the current behavior is exactly what one should expect.

**Comment by luoluoyuyu** [comment]
Okay, got it. Thanks for the answer.

> I still don't understand what problem you are trying to address. There is no reason why anybody would want to navigate the redirect_uri outside of the OIDC authentication flow. This should never be a "normal" URI of your application. The premise "when users configure the redirect_uri value as 127.0.0.1:8080/test" simply should never happen.
> 
> IMHO the current behavior is exactly what one should expect.
