### ISSUE TITLE
CORS error on xhr request if logged out

### ISSUE THREAD

**Issue by MelnykVL** [zmartzone/lua-resty-openidc#504]
Hello,

I have a problem with working in two tabs.
When I log in to an app, duplicate tab, log out from the second tab, and return to the first tab where I am still "logged" and make xhr request, I get CORS error.

<img width="1512" alt="image" src="https://github.com/zmartzone/lua-resty-openidc/assets/61125444/102a6345-4731-4774-aa8a-491b0ff5af3b">
<img width="1512" alt="image" src="https://github.com/zmartzone/lua-resty-openidc/assets/61125444/3ca370b6-6293-4020-a420-1db441378398">

But if I do the same steps but make not xhr request, everything is ok (I'm redirected to the login page).

<img width="1512" alt="image" src="https://github.com/zmartzone/lua-resty-openidc/assets/61125444/8adeafaa-3845-4397-89bb-cbdff5736902">

I tried adding Access-Control-Allow-Origin = * header using nginx.conf and lua, set Web origins = * in Keycloak but nothing helps
**Someone can answer why?**

###### Expected behaviour
Redirect to the login page

###### Actual behaviour
Get CORS error

**Comment by ogun-** [comment]
@MelnykVL I ran into the same issue. Where you able to solve it? If yes how?
