### ISSUE TITLE
Session issue

### ISSUE THREAD

**Issue by alexandrst88** [zmartzone/lua-resty-openidc#83]
Hi! I have this issue, I dont know what's cause an issue.
```request to the redirect_uri_path but there's no session state found```
Also, intersting, when i set:
```    
lua_code_cache off;
set $session_secret 623q4hR325t36VsCD3g567922IC0073T;
```
 I get 
```
unhandled request to the redirect_uri: /example/url
```

Or here, I did 
```function openidc.authenticate(opts, target_url)

  local err

  local session = require("resty.session").start()
```

then restart nginx and did:

```function openidc.authenticate(opts, target_url)

  local err

  local session = require("resty.session").open()
```

 I get 

```
unhandled request to the redirect_uri: /example/url
```

**Comment by zandbelt** [comment]
You're not supposed to call `resty.session` directly, that is handled for you by including something like:
```
          local res, err = require("resty.openidc").authenticate(opts)
```

it would be good to show the error/access log as to see what the unhandled request looks like

**Comment by alexandrst88** [comment]
I didn't call it directly, only change in openidc.lua, for test purpose. I think that session store or file not creating.

**Comment by bungle** [comment]
@alexandrst88 does it only happen when you have `lua_code_cache off;`

**Comment by alexandrst88** [comment]
Not really, when my location match `redirect_uri`. When I changed location to `/` it's starts working fine.

**Comment by noqcks** [comment]
I have this issue as well. Im using the basic Google OIDC example.

Im not a lua pro, do I just need to create a function to handle the oidc redirect uri, or is there a method already baked in for doing this ?

**Comment by bodewig** [comment]
openidc is supposed to handle the `redirect_uri` location internally inside of `oidc.authenticate`.

@noqcks what exactly do you see as "the issue"? If you are using a recent version of openidc and you set nginx' log level to `debug` we should be able get some information that helps us tracking down what is happening on your side.

**Comment by zandbelt** [comment]
The redirect uri is a "vanity url", a special handler processed by lua-resty-openidc. You should not access it directly.
